package com.shell.siep.gto.commons.enums;

public enum WEBErrorCodeEnum {

	/*----GENDREAL ERROR'S----*/
	INTERNAL_SERVER_EXCEPTION(100,"INTERNAL_SERVER_EXCEPTION"),
	INPUT_VALIDATION_EXCEPTION(101,"INPUT_VALIDATION_EXCEPTION"),
	SERVICE_LAYER_EXCEPTION(102, "SERVICE_LAYER_EXCEPTION"),
	INVALID_API_REQUEST(103, "INVALID_API_REQUEST"),
	NULL_POINTER_EXCEPTION(104, "NULL_POINTER_EXCEPTION"),
	
	INVALID_AUTH_TOKEN(1000,"INVALID_AUTH_TOKEN"),
	NO_DATA_FOUND(1001,"NO_DATA_FOUND"),
	INPUT_MISSING(1002,"INPUT_MISSING"),
	INPUT_FORMAT_INVALID(1003,"INPUT_FORMAT_INVALID"),
	INPUT_PASSWORD_FORMAT_INVALID(1004,"INPUT_PASSWORD_FORMAT_INVALID"),
	
	
	/*LOGIN PAGE ERROR'S*/	
	AUTHENTICATION_FALIED_EXCEPTION(3000,"AUTHENTICATION_FALIED_EXCEPTION"),
	USER_NOT_FOUND(3001,"USER_NOT_FOUND"),
	USER_DISABLED(3002,"USER_DISABLED"),
	INVALID_FORGOT_PASSWORD_LINK(3003,"INVALID_FORGOT_PASSWORD_LINK"),
	INVALID_LOGIN_REQUEST(3004,"INVALID_LOGIN_REQUEST"), 
	AUTH_TOKEN_CREATION_ERROR(3005, "AUTH_TOKEN_CREATION_ERROR"),
	
	MAINTENANCE_MODE(2002, "System under maintenance."),
	DATA_ACCESS_ERROR(2003, "Datasource is not available.");
	
	
	
	
	private int code;
	private String message;
	
	private WEBErrorCodeEnum(int code, String message){
		this.code	= code;
		this.message	= message;
	}

	public int getCode() {
		return code;
	}

	public String getMessage() {
		return message;
	}

}
