package com.shell.siep.gto.persistence.model;

import java.util.Date;

public interface GTOFpcIsotopesRock extends GTODatabaseObject {
	public String getDRRunNumber();
	public void setDRRunNumber(String dRRunNumber);
	public Double getDcRSat();
	public void setDcRSat(Double dcRSat);
	public String getDRQc();
	public void setDRQc(String dRQc);
	public Double getDcRSid();
	public void setDcRSid(Double dcRSid);
	public Double getDcRExt();
	public void setDcRExt(Double dcRExt);
	public Double getDcRNhc();
	public void setDcRNhc(Double dcRNhc);
	public Double getDcRAnk();
	public void setDcRAnk(Double dcRAnk);
	public Double getDcRNcc();
	public void setDcRNcc(Double dcRNcc);
	public Double getDcRCalcite();
	public void setDcRCalcite(Double dcRCalcite);
	public Date getDRLastUpdate();
	public void setDRLastUpdate(Date dRLastUpdate);
	public Double getDcRDolomite();
	public void setDcRDolomite(Double dcRDolomite);
	public Date getDcQcDate();
	public void setDcQcDate(Date dcQcDate);
	public Double getDcRAro();
	public void setDcRAro(Double dcRAro);
	public String getDRRequest();
	public void setDRRequest(String dRRequest);
	public String getDRJobId();
	public void setDRJobId(String dRJobId);
	public Double getDsRKero();
	public void setDsRKero(Double dsRKero);
	public Double getDsRAs();
	public void setDsRAs(Double dsRAs);
	public String getDRComments();
	public void setDRComments(String dRComments);
	public String getDRSampleId();
	public void setDRSampleId(String dRSampleId);
	public Double getDcRDecalc();
	public void setDcRDecalc(Double dcRDecalc);
	public Double getDoRDolomite();
	public void setDoRDolomite(Double doRDolomite);
	public String getDRDataType();
	public void setDRDataType(String dRDataType);
	public Double getDcRNp();
	public void setDcRNp(Double dcRNp);
	public String getDRSvcCode();
	public void setDRSvcCode(String dRSvcCode);
	public String getDRMethod();
	public void setDRMethod(String dRMethod);
	public Double getDcRPyr();
	public void setDcRPyr(Double dcRPyr);
	public Double getDdRKero();
	public void setDdRKero(Double ddRKero);
	public Date getDRAcqDate();
	public void setDRAcqDate(Date dRAcqDate);
	public Double getDsRSulfSilver();
	public void setDsRSulfSilver(Double dsRSulfSilver);
	public Double getDoRAnk();
	public void setDoRAnk(Double doRAnk);
	public Double getDoRNcc();
	public void setDoRNcc(Double doRNcc);
	public Double getDsRH2s();
	public void setDsRH2s(Double dsRH2s);
	public String getDRAuthor();
	public void setDRAuthor(String dRAuthor);
	public Double getDcRBitumen();
	public void setDcRBitumen(Double dcRBitumen);
	public String getDcQcUser();
	public void setDcQcUser(String dcQcUser);
	public Double getDnRN2();
	public void setDnRN2(Double dnRN2);
	public String getDRSampleIdVend();
	public void setDRSampleIdVend(String dRSampleIdVend);
	public Double getDcRChi();
	public void setDcRChi(Double dcRChi);
	public Double getDcRChs();
	public void setDcRChs(Double dcRChs);
	public Double getDsRSulfAnh();
	public void setDsRSulfAnh(Double dsRSulfAnh);
	public Double getDsRSulfPyrite();
	public void setDsRSulfPyrite(Double dsRSulfPyrite);
	public Double getDoROid();
	public void setDoROid(Double doROid);
	public Double getDcRAs();
	public void setDcRAs(Double dcRAs);
	public Double getDnRAs();
	public void setDnRAs(Double dnRAs);
	public Double getDoRCalcite();
	public void setDoRCalcite(Double doRCalcite);
	public Double getDcROid();
	public void setDcROid(Double dcROid);
	public Double getDoRSid();
	public void setDoRSid(Double doRSid);
	public Double getDcRIc();
	public void setDcRIc(Double dcRIc);
	public Double getDsRSulfOrganic();
	public void setDsRSulfOrganic(Double dsRSulfOrganic);
	public String getDcIqmCode();
	public void setDcIqmCode(String dcIqmCode);
	public String getDRLab();
	public void setDRLab(String dRLab);
	public Double getDcRKer();
	public void setDcRKer(Double dcRKer);
}
