package com.shell.siep.gto.persistence.model;

import java.util.Date;

import java.util.List;

public interface GTOSample extends GTODatabaseObject {
	Double getShTvdTop();
	void setShTvdTop(Double shTvdTop);
	String getShComment();
	void setShComment(String shComment);
	String getShFormBot();
	void setShFormBot(String shFormBot);
	String getShWellId();
	void setShWellId(String shWellId);
	String getShRsvr();
	void setShRsvr(String shRsvr);
	String getShLith();
	void setShLith(String shLith);
	String getShParent();
	void setShParent(String shParent);
	String getSampleId();
	void setSampleId(String sampleId);
	String getShAgeYoungMy();
	void setShAgeYoungMy(String shAgeYoungMy);
	GTOSampleType getSampleType();
	String getShUomOrig();
	void setShUomOrig(String shUomOrig);
	String getShForm();
	void setShForm(String shForm);
	String getShOrig();
	void setShOrig(String shOrig);
	String getShAgeOldMy();
	void setShAgeOldMy(String shAgeOldMy);
	Double getShTvdBot();
	void setShTvdBot(Double shTvdBot);
	String getShCommentStrat();
	void setShCommentStrat(String shCommentStrat);
	String getShTvdRef();
	void setShTvdRef(String shTvdRef);
	String getShSampleSubType();
	String getShOrigDesc();
	void setShOrigDesc(String shOrigDesc);
	String getExtSampleVendor();
	void setExtSampleVendor(String extSampleVendor);
	String getShTreatmentDesc();
	void setShTreatmentDesc(String shTreatmentDesc);
	String getShFractionDesc();
	void setShFractionDesc(String shFractionDesc);
	String getShSampleTypeDesc();
	void setShSampleTypeDesc(String shSampleTypeDesc);
	Double getShDepthBot();
	void setShDepthBot(Double shDepthBot);
	Date getShCdate();
	void setShCdate(Date shCdate);
	String getShAgeYoung();
	void setShAgeYoung(String shAgeYoung);
	String getShAgeOld();
	void setShAgeOld(String shAgeOld);
	String getShTreatment();
	void setShTreatment(String shTreatment);
	String getSampleIdExt();
	void setSampleIdExt(String sampleIdExt);
	Double getShDepthTop();
	void setShDepthTop(Double shDepthTop);
	List<GTOSample> getSamples();
	GTOWell getWell();
	Double getShCollTemp();
	void setShCollTemp(Double shCollTemp);
	String getSampleQc();
	void setSampleQc(String sampleQc);
	Date getSampleQcDate();
	void setSampleQcDate(Date sampleQcDate);
	String getShTempUnits();
	void setShTempUnits(String shTempUnits);
	Integer getSampleIdGdb();
	void setSampleIdGdb(Integer sampleIdGdb);
	Date getShSdateField();
	void setShSdateField(Date shSdateField);
	Date getShCreatedDate();
	void setShCreatedDate(Date shCreatedDate);
	String getShGrp();
	void setShGrp(String shGrp);
	Double getShCollVol();
	void setShCollVol(Double shCollVol);
	String getSampleQcUser();
	void setSampleQcUser(String sampleQcUser);
	String getShPresUnits();
	void setShPresUnits(String shPresUnits);
	String getShRsvrTempUnits();
	void setShRsvrTempUnits(String shRsvrTempUnits);
	String getShCreatedUser();
	void setShCreatedUser(String shCreatedUser);
	String getSampleIqmCode();
	void setSampleIqmCode(String sampleIqmCode);
	String getShContainerId();
	void setShContainerId(String shContainerId);
	String getShTemperatureUnits();
	void setShTemperatureUnits(String shTemperatureUnits);
	String getShAge();
	void setShAge(String shAge);
	String getShVendJobId();
	void setShVendJobId(String shVendJobId);
	Double getShPres();
	void setShPres(Double shPres);
	Double getShTemperature();
	void setShTemperature(Double shTemperature);
	Double getShGasUnits();
	void setShGasUnits(Double shGasUnits);
	String getShFocalPt();
	void setShFocalPt(String shFocalPt);
	Integer getShProdVolUnits();
	void setShProdVolUnits(Integer shProdVolUnits);
	Double getShRsvrPres();
	void setShRsvrPres(Double shRsvrPres);
	Integer getSampleCountryId();
	void setSampleCountryId(Integer sampleCountryId);
	Date getShSdateLab();
	void setShSdateLab(Date shSdateLab);
	String getShMbr();
	void setShMbr(String shMbr);
	String getShCollPresUnits();
	void setShCollPresUnits(String shCollPresUnits);
	Double getShCollPres();
	void setShCollPres(Double shCollPres);
	String getShAppearReceived();
	void setShAppearReceived(String shAppearReceived);
	String getShColl();
	void setShColl(String shColl);
	String getShContainerType();
	void setShContainerType(String shContainerType);
	String getShAgeBot();
	void setShAgeBot(String shAgeBot);
	String getShRsvrPresUnits();
	void setShRsvrPresUnits(String shRsvrPresUnits);
	String getSampleIdStorage();
	void setSampleIdStorage(String sampleIdStorage);
	String getShAuthor();
	void setShAuthor(String shAuthor);
	String getShUpdatedUser();
	void setShUpdatedUser(String shUpdatedUser);
	Integer getShFluidType();
	void setShFluidType(Integer shFluidType);
	Double getShRsvrTemp();
	void setShRsvrTemp(Double shRsvrTemp);
	Double getShTemp();
	void setShTemp(Double shTemp);
	Integer getShCollVolUnits();
	void setShCollVolUnits(Integer shCollVolUnits);
	Date getShUpdatedDate();
	void setShUpdatedDate(Date shUpdatedDate);
	String getShCollTempUnits();
	void setShCollTempUnits(String shCollTempUnits);
	String getSampleIdGm();
	void setSampleIdGm(String sampleIdGm);
	String getShAppearField();
	void setShAppearField(String shAppearField);
	Double getShProdVol();
	void setShProdVol(Double shProdVol);
	Integer getShGasUnitsId();
	void setShGasUnitsId(Integer shGasUnitsId);
	String getSampleIdSam();
	void setSampleIdSam(String sampleIdSam);
	Integer getShReportCount();
	void setShReportCount(Integer shReportCount);
	Date getShRdate();
	void setShRdate(Date shRdate);
	String getShCtime();
	void setShCtime(String shCtime);
	Date getShLastUpdate();
	void setShLastUpdate(Date shLastUpdate);
	String getShCompletion();
	void setShCompletion(String shCompletion);
	String getSampleIdImsa();
	void setSampleIdImsa(String sampleIdImsa);
	String getShAppear();
	void setShAppear(String shAppear);
	Date getShSdate();
	void setShSdate(Date shSdate);
	String getShVolUnits();
	void setShVolUnits(String shVolUnits);
	String getShVolProdUnits();
	void setShVolProdUnits(String shVolProdUnits);
	Double getShVolRec();
	void setShVolRec(Double shVolRec);
	String getSampleName();
	void setSampleName(String sampleName);
	String getShMdRef();
	void setShMdRef(String shMdRef);
	String getShFocalPoint();
	void setShFocalPoint(String shFocalPoint);
	Double getShVolProd();
	void setShVolProd(Double shVolProd);
	String getSampleIdOp();
	void setSampleIdOp(String sampleIdOp);
	String getShRsvrId();
	void setShRsvrId(String shRsvrId);
	String getSampleIdFpc();
	void setSampleIdFpc(String sampleIdFpc);
	String getSampleIdAms();
	void setSampleIdAms(String sampleIdAms);
	String getShSamplingPoint();
	void setShSamplingPoint(String shSamplingPoint);
}
