package com.shell.siep.gto.persistence.model;

import java.util.Date;
import java.util.List;

public interface GTOWell extends GTODatabaseObject {
	Long getWellIdIhs();
	void setWellIdIhs(Long wellIdIhs);
	Double getWhDepthTvd();
	void setWhDepthTvd(Double whDepthTvd);
	Integer getWhSpudYear();
	void setWhSpudYear(Integer whSpudYear);
	String getWhComments();
	void setWhComments(String whComments);
	String getWhField();
	void setWhField(String whField);
	String getWhCoordSys();
	void setWhCoordSys(String whCoordSys);
	Double getWhTd();
	void setWhTd(Double whTd);
	String getWhProspect();
	void setWhProspect(String whProspect);
	Double getWhWaterDepth();
	void setWhWaterDepth(Double whWaterDepth);
	Integer getWhCountryId();
	void setWhCountryId(Integer whCountryId);
	String getWhBlockBh();
	void setWhBlockBh(String whBlockBh);
	String getWhCompDate();
	void setWhCompDate(String whCompDate);
	String getWhAltWellName();
	void setWhAltWellName(String whAltWellName);
	Double getWhLat();
	void setWhLat(Double whLat);
	String getWhLease();
	void setWhLease(String whLease);
	String getWhCounty();
	void setWhCounty(String whCounty);
	String getWhSpudDate();
	void setWhSpudDate(String whSpudDate);
	String getWellIdCds();
	void setWellIdCds(String wellIdCds);
	String getWhUom();
	void setWhUom(String whUom);
	String getWhDepthRef();
	void setWhDepthRef(String whDepthRef);
	String getWhArea();
	void setWhArea(String whArea);
	String getWhProvince();
	void setWhProvince(String whProvince);
	Double getWhDepthMd();
	void setWhDepthMd(Double whDepthMd);
	String getWellName();
	void setWellName(String wellName);
	String getWhBasin();
	void setWhBasin(String whBasin);
	Double getWhLong();
	void setWhLong(Double whLong);
	String getWhBlock();
	void setWhBlock(String whBlock);
	Double getWhDrElev();
	void setWhDrElev(Double whDrElev);
	String getWhSitetype();
	void setWhSitetype(String whSitetype);
	String getWellId();
	void setWellId(String wellId);
	String getWhOperator();
	void setWhOperator(String whOperator);
	String getWhAreaBh();
	void setWhAreaBh(String whAreaBh);
	GTOCountry getCountry();
	List<GTOSample> getSamples();
	String getWhCurrentStatus();
	void setWhCurrentStatus(String whCurrentStatus);
	String getWhFormationAtTd();
	void setWhFormationAtTd(String whFormationAtTd);
	Integer getWhReportCount();
	void setWhReportCount(Integer whReportCount);
	String getWhOnshoreOrOffshore();
	void setWhOnshoreOrOffshore(String whOnshoreOrOffshore);
	Double getWhLatIhs();
	void setWhLatIhs(Double whLatIhs);
	Double getWhBhLatCds();
	void setWhBhLatCds(Double whBhLatCds);
	String getWhBhCoordSysIhs();
	void setWhBhCoordSysIhs(String whBhCoordSysIhs);
	String getWellQc();
	void setWellQc(String wellQc);
	Double getWhBhLon();
	void setWhBhLon(Double whBhLon);
	Integer getWellAnalyses();
	void setWellAnalyses(Integer wellAnalyses);
	String getWhResponsibleOrg();
	void setWhResponsibleOrg(String whResponsibleOrg);
	Double getWhLongCds();
	void setWhLongCds(Double whLongCds);
	String getWellQcUser();
	void setWellQcUser(String wellQcUser);
	String getWhFormationFluid();
	void setWhFormationFluid(String whFormationFluid);
	Date getWhFormationFluidDate();
	void setWhFormationFluidDate(Date whFormationFluidDate);
	String getWhCoordSysCds();
	void setWhCoordSysCds(String whCoordSysCds);
	String getWhFluid();
	void setWhFluid(String whFluid);
	String getWhCurrentPurpose();
	void setWhCurrentPurpose(String whCurrentPurpose);
	String getWellIdApi();
	void setWellIdApi(String wellIdApi);
	Double getWhBhLongCds();
	void setWhBhLongCds(Double whBhLongCds);
	String getWhCoordSysIhs();
	void setWhCoordSysIhs(String whCoordSysIhs);
	Double getWhGrndEl();
	void setWhGrndEl(Double whGrndEl);
	String getWhSubBasin();
	void setWhSubBasin(String whSubBasin);
	String getWellNameIhs();
	void setWellNameIhs(String wellNameIhs);
	String getWellIdHid();
	void setWellIdHid(String wellIdHid);
	String getWhRigName();
	void setWhRigName(String whRigName);
	Date getWhCurrentStatusDate();
	void setWhCurrentStatusDate(Date whCurrentStatusDate);
	Date getWellQcDate();
	void setWellQcDate(Date wellQcDate);
	Double getWhLongIhs();
	void setWhLongIhs(Double whLongIhs);
	String getWhPadPlatformName();
	void setWhPadPlatformName(String whPadPlatformName);
	String getWhLicenseNo();
	void setWhLicenseNo(String whLicenseNo);
	Double getWhBhLat();
	void setWhBhLat(Double whBhLat);
	Date getWhFluidDate();
	void setWhFluidDate(Date whFluidDate);
	Integer getWellPnc();
	void setWellPnc(Integer wellPnc);
	Integer getWellSamples();
	void setWellSamples(Integer wellSamples);
	Double getWhBhLatIhs();
	void setWhBhLatIhs(Double whBhLatIhs);
	String getWhProducingFormation();
	void setWhProducingFormation(String whProducingFormation);
	String getWellNameCds();
	void setWellNameCds(String wellNameCds);
	String getWhWellNbr();
	void setWhWellNbr(String whWellNbr);
	String getWellIqmCode();
	void setWellIqmCode(String wellIqmCode);
	Double getWhBhLongIhs();
	void setWhBhLongIhs(Double whBhLongIhs);
	String getWhCompletionStatus();
	void setWhCompletionStatus(String whCompletionStatus);
	String getWhBhCoordSysCds();
	void setWhBhCoordSysCds(String whBhCoordSysCds);
	Double getWhLatCds();
	void setWhLatCds(Double whLatCds);
	Date getWhFracDate();
	void setWhFracDate(Date whFracDate);
	Double getWhLonSurf();
	void setWhLonSurf(Double whLonSurf);
	Integer getWhRefElevM();
	void setWhRefElevM(Integer whRefElevM);
	String getWellLicenseNo();
	void setWellLicenseNo(String wellLicenseNo);
	String getWellSpudDate();
	void setWellSpudDate(String wellSpudDate);
	Integer getWhPnc();
	void setWhPnc(Integer whPnc);
	String getWellCompDate();
	void setWellCompDate(String wellCompDate);
	String getWellIdUwbi();
	void setWellIdUwbi(String wellIdUwbi);
	Double getWhWaterMd();
	void setWhWaterMd(Double whWaterMd);
	Date getWhLastUpdate();
	void setWhLastUpdate(Date whLastUpdate);
	Double getWhWaterTvd();
	void setWhWaterTvd(Double whWaterTvd);
	String getWellIdUwbiSrc();
	void setWellIdUwbiSrc(String wellIdUwbiSrc);
	String getWhFieldCommon();
	void setWhFieldCommon(String whFieldCommon);
	Double getWhLatSurf();
	void setWhLatSurf(Double whLatSurf);
	Date getWhProdStartDate();
	void setWhProdStartDate(Date whProdStartDate);
	String getWhNbr();
	void setWhNbr(String whNbr);
	String getWhAreablockSurf();
	void setWhAreablockSurf(String whAreablockSurf);
	String getWhCoordDatum();
	void setWhCoordDatum(String whCoordDatum);
	String getWhAreablockBh();
	void setWhAreablockBh(String whAreablockBh);
	Double getWhTdMd();
	void setWhTdMd(Double whTdMd);
	String getWhDatumCds();
	void setWhDatumCds(String whDatumCds);
	Double getWhLatSam();
	void setWhLatSam(Double whLatSam);
	String getWellNameGeomark();
	void setWellNameGeomark(String wellNameGeomark);
	Double getWhLongGdb();
	void setWhLongGdb(Double whLongGdb);
	Double getWhLatGeomark();
	void setWhLatGeomark(Double whLatGeomark);
	String getWellNameUsgs();
	void setWellNameUsgs(String wellNameUsgs);
	String getWhIdFpc();
	void setWhIdFpc(String whIdFpc);
	String getWellNameRobertson();
	void setWellNameRobertson(String wellNameRobertson);
	String getWhNameFpc();
	void setWhNameFpc(String whNameFpc);
	String getWhDatumIhs();
	void setWhDatumIhs(String whDatumIhs);
	Double getWhLongSam();
	void setWhLongSam(Double whLongSam);
	Double getWhLongGeomark();
	void setWhLongGeomark(Double whLongGeomark);
	String getWellNameSam();
	void setWellNameSam(String wellNameSam);
	String getWellNameGdb();
	void setWellNameGdb(String wellNameGdb);
	Double getWhLongUsgs();
	void setWhLongUsgs(Double whLongUsgs);
	Double getWhLatGdb();
	void setWhLatGdb(Double whLatGdb);
	String getRlocWellId();
	void setRlocWellId(String rlocWellId);
	String getWellNameVen();
	void setWellNameVen(String wellNameVen);
	Integer getLocType();
	void setLocType(Integer locType);
	Double getWhLongRobertson();
	void setWhLongRobertson(Double whLongRobertson);
	Double getWhLatUsgs();
	void setWhLatUsgs(Double whLatUsgs);
	Double getWhLatRobertson();
	void setWhLatRobertson(Double whLatRobertson);
}
