package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOCsiaC7 extends GTOAnalysisData {
	public String getCsiaC7Comment();
	public void setCsiaC7Comment(String csiaC7Comment);
	public Date getCsiaC7QcDate();
	public void setCsiaC7QcDate(Date csiaC7QcDate);
	public String getCsiaC7QcUser();
	public void setCsiaC7QcUser(String csiaC7QcUser);
	public Double getCsiaC724dmh();
	public void setCsiaC724dmh(Double csiaC724dmh);
	public Double getCsiaC724dmp();
	public void setCsiaC724dmp(Double csiaC724dmp);
	public Double getCsiaC71c2dmcp();
	public void setCsiaC71c2dmcp(Double csiaC71c2dmcp);
	public Double getCsiaC71t2dmcp();
	public void setCsiaC71t2dmcp(Double csiaC71t2dmcp);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getCsiaC7113tmcp();
	public void setCsiaC7113tmcp(Double csiaC7113tmcp);
	public Double getCsiaC7Cp();
	public void setCsiaC7Cp(Double csiaC7Cp);
	public Double getCsiaC7Ch();
	public void setCsiaC7Ch(Double csiaC7Ch);
	public Double getCsiaC7N2();
	public void setCsiaC7N2(Double csiaC7N2);
	public Double getCsiaC7224tmp();
	public void setCsiaC7224tmp(Double csiaC7224tmp);
	public Double getCsiaC725dmh();
	public void setCsiaC725dmh(Double csiaC725dmh);
	public Date getCsiaC7LastUpdate();
	public void setCsiaC7LastUpdate(Date csiaC7LastUpdate);
	public String getCsiaC7DataType();
	public void setCsiaC7DataType(String csiaC7DataType);
	public Double getCsiaC7Tol();
	public void setCsiaC7Tol(Double csiaC7Tol);
	public Double getCsiaC72mh();
	public void setCsiaC72mh(Double csiaC72mh);
	public Double getCsiaC72mp();
	public void setCsiaC72mp(Double csiaC72mp);
	public String getCsiaC7Qc();
	public void setCsiaC7Qc(String csiaC7Qc);
	public Double getCsiaC7Ecp();
	public void setCsiaC7Ecp(Double csiaC7Ecp);
	public Double getCsiaC73ep();
	public void setCsiaC73ep(Double csiaC73ep);
	public Date getCsiaC7AcqDate();
	public void setCsiaC7AcqDate(Date csiaC7AcqDate);
	public Date getCsiaC7Date();
	public void setCsiaC7Date(Date csiaC7Date);
	public Double getCsiaC7223tmb();
	public void setCsiaC7223tmb(Double csiaC7223tmb);
	public Double getCsiaC73mp();
	public void setCsiaC73mp(Double csiaC73mp);
	public Double getCsiaC7223tmp();
	public void setCsiaC7223tmp(Double csiaC7223tmp);
	public Double getCsiaC73mh();
	public void setCsiaC73mh(Double csiaC73mh);
	public Double getCsiaC7123tmcp();
	public void setCsiaC7123tmcp(Double csiaC7123tmcp);
	public Double getCsiaC71t3dmcp();
	public void setCsiaC71t3dmcp(Double csiaC71t3dmcp);
	public Double getCsiaC71c3dmcp();
	public void setCsiaC71c3dmcp(Double csiaC71c3dmcp);
	public String getCsiaC7Author();
	public void setCsiaC7Author(String csiaC7Author);
	public Double getCsiaC7Ethene();
	public void setCsiaC7Ethene(Double csiaC7Ethene);
	public Double getCsiaC733dmp();
	public void setCsiaC733dmp(Double csiaC733dmp);
	public Double getCsiaC7Ic4();
	public void setCsiaC7Ic4(Double csiaC7Ic4);
	public Double getCsiaC7Ic5();
	public void setCsiaC7Ic5(Double csiaC7Ic5);
	public Double getCsiaC7Propene();
	public void setCsiaC7Propene(Double csiaC7Propene);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getCsiaC7Nc10();
	public void setCsiaC7Nc10(Double csiaC7Nc10);
	public String getCsiaC7SvcCode();
	public void setCsiaC7SvcCode(String csiaC7SvcCode);
	public Double getCsiaC711dmcp();
	public void setCsiaC711dmcp(Double csiaC711dmcp);
	public Double getCsiaC7Nc3();
	public void setCsiaC7Nc3(Double csiaC7Nc3);
	public Double getCsiaC7Nc4();
	public void setCsiaC7Nc4(Double csiaC7Nc4);
	public Double getCsiaC7Nc1();
	public void setCsiaC7Nc1(Double csiaC7Nc1);
	public Double getCsiaC7Nc2();
	public void setCsiaC7Nc2(Double csiaC7Nc2);
	public Double getCsiaC7Nc7();
	public void setCsiaC7Nc7(Double csiaC7Nc7);
	public Double getCsiaC7Nc8();
	public void setCsiaC7Nc8(Double csiaC7Nc8);
	public Double getCsiaC7Nc5();
	public void setCsiaC7Nc5(Double csiaC7Nc5);
	public Double getCsiaC7Nc6();
	public void setCsiaC7Nc6(Double csiaC7Nc6);
	public String getCsiaC7SampleIdVend();
	public void setCsiaC7SampleIdVend(String csiaC7SampleIdVend);
	public Double getCsiaC722dmp();
	public void setCsiaC722dmp(Double csiaC722dmp);
	public Double getCsiaC722dmh();
	public void setCsiaC722dmh(Double csiaC722dmh);
	public Double getCsiaC722dmb();
	public void setCsiaC722dmb(Double csiaC722dmb);
	public String getCsiaC7RunNumber();
	public void setCsiaC7RunNumber(String csiaC7RunNumber);
	public Double getCsiaC7Benz();
	public void setCsiaC7Benz(Double csiaC7Benz);
	public String getCsiaC7Method();
	public void setCsiaC7Method(String csiaC7Method);
	public String getCsiaC7IqmCode();
	public void setCsiaC7IqmCode(String csiaC7IqmCode);
	public String getCsiaC7JobId();
	public void setCsiaC7JobId(String csiaC7JobId);
	public String getCsiaC7Lab();
	public void setCsiaC7Lab(String csiaC7Lab);
	public Double getCsiaC7124tmcp();
	public void setCsiaC7124tmcp(Double csiaC7124tmcp);
	public Double getCsiaC723dmp();
	public void setCsiaC723dmp(Double csiaC723dmp);
	public Double getCsiaC723dmb();
	public void setCsiaC723dmb(Double csiaC723dmb);
	public Double getCsiaC7Mch();
	public void setCsiaC7Mch(Double csiaC7Mch);
	public Double getCsiaC7Mcp();
	public void setCsiaC7Mcp(Double csiaC7Mcp);
}
