package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOChnos extends GTOAnalysisData {
	public String getChnosCQ();
	public void setChnosCQ(String chnosCQ);
	public String getChnosSampleIdVend();
	public void setChnosSampleIdVend(String chnosSampleIdVend);
	public Double getChnosFe();
	public void setChnosFe(Double chnosFe);
	public String getChnosQc();
	public void setChnosQc(String chnosQc);
	public String getChnosSQ();
	public void setChnosSQ(String chnosSQ);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getChnosIqmCode();
	public void setChnosIqmCode(String chnosIqmCode);
	public String getChnosComments();
	public void setChnosComments(String chnosComments);
	public Double getChnosN();
	public void setChnosN(Double chnosN);
	public Double getChnosO();
	public void setChnosO(Double chnosO);
	public Double getChnosH();
	public void setChnosH(Double chnosH);
	public Double getChnosC();
	public void setChnosC(Double chnosC);
	public Double getChnosS();
	public void setChnosS(Double chnosS);
	public String getChnosHQ();
	public void setChnosHQ(String chnosHQ);
	public Date getChnosLastUpdate();
	public void setChnosLastUpdate(Date chnosLastUpdate);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getChnosAshQ();
	public void setChnosAshQ(String chnosAshQ);
	public String getChnosRunNumber();
	public void setChnosRunNumber(String chnosRunNumber);
	public Date getChnosQcDate();
	public void setChnosQcDate(Date chnosQcDate);
	public String getChnosSvcCode();
	public void setChnosSvcCode(String chnosSvcCode);
	public Date getChnosAcqDate();
	public void setChnosAcqDate(Date chnosAcqDate);
	public String getChnosLab();
	public void setChnosLab(String chnosLab);
	public String getChnosQcUser();
	public void setChnosQcUser(String chnosQcUser);
	public Double getChnosAsh();
	public void setChnosAsh(Double chnosAsh);
	public String getChnosFeQ();
	public void setChnosFeQ(String chnosFeQ);
	public String getChnosAuthor();
	public void setChnosAuthor(String chnosAuthor);
	public String getChnosJobId();
	public void setChnosJobId(String chnosJobId);
	public String getChnosOQ();
	public void setChnosOQ(String chnosOQ);
	public String getChnosMethod();
	public void setChnosMethod(String chnosMethod);
	public String getChnosNQ();
	public void setChnosNQ(String chnosNQ);
	public Double getChnosNCRatio();
	public void setChnosNCRatio(Double chnosNCRatio);
	public Double getChnosHCRatio();
	public void setChnosHCRatio(Double chnosHCRatio);
	public String getChnosQcFlag();
	public void setChnosQcFlag(String chnosQcFlag);
	public Date getChnosUpdatedDate();
	public void setChnosUpdatedDate(Date chnosUpdatedDate);
	public Double getChnosHNRatio();
	public void setChnosHNRatio(Double chnosHNRatio);
	public Double getChnosSCRatio();
	public void setChnosSCRatio(Double chnosSCRatio);
	public String getChnosUpdatedUser();
	public void setChnosUpdatedUser(String chnosUpdatedUser);
	public String getChnosRequestIdVend();
	public void setChnosRequestIdVend(String chnosRequestIdVend);
	public Date getChnosCreatedDate();
	public void setChnosCreatedDate(Date chnosCreatedDate);
	public Double getChnosOCRatio();
	public void setChnosOCRatio(Double chnosOCRatio);
	public String getChnosComment();
	public void setChnosComment(String chnosComment);
	public String getChnosIqmFlag();
	public void setChnosIqmFlag(String chnosIqmFlag);
	public String getChnosCreatedUser();
	public void setChnosCreatedUser(String chnosCreatedUser);
}
