package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcMdgc extends GTOAnalysisData {
	public Double getGm1e2mbz();
	public void setGm1e2mbz(Double gm1e2mbz);
	public Date getGmDate();
	public void setGmDate(Date gmDate);
	public String getGmLab();
	public void setGmLab(String gmLab);
	public Double getGmIpbz();
	public void setGmIpbz(Double gmIpbz);
	public String getGmDataType();
	public void setGmDataType(String gmDataType);
	public Double getGmMustPeak2();
	public void setGmMustPeak2(Double gmMustPeak2);
	public Double getGmMustPeak1();
	public void setGmMustPeak1(Double gmMustPeak1);
	public String getGmMethod();
	public void setGmMethod(String gmMethod);
	public Double getGm135Tmbz();
	public void setGm135Tmbz(Double gm135Tmbz);
	public String getGmComments();
	public void setGmComments(String gmComments);
	public Date getGmAcqDate();
	public void setGmAcqDate(Date gmAcqDate);
	public Double getIBBenzC();
	public void setIBBenzC(Double iBBenzC);
	public String getGmJobId();
	public void setGmJobId(String gmJobId);
	public Double getGm13Dmbz();
	public void setGm13Dmbz(Double gm13Dmbz);
	public String getGmSampleIdVend();
	public void setGmSampleIdVend(String gmSampleIdVend);
	public Double getMdgcCisC();
	public void setMdgcCisC(Double mdgcCisC);
	public Double getMdgcCisP();
	public void setMdgcCisP(Double mdgcCisP);
	public Double getGmEbz();
	public void setGmEbz(Double gmEbz);
	public Date getGmQcDate();
	public void setGmQcDate(Date gmQcDate);
	public Double getGm124Tmbz();
	public void setGm124Tmbz(Double gm124Tmbz);
	public Double getMdgcSolvAmt();
	public void setMdgcSolvAmt(Double mdgcSolvAmt);
	public Double getGm1e4mbz();
	public void setGm1e4mbz(Double gm1e4mbz);
	public String getGmAuthor();
	public void setGmAuthor(String gmAuthor);
	public Double getGmNPbz();
	public void setGmNPbz(Double gmNPbz);
	public Double getMdgcSampAmt();
	public void setMdgcSampAmt(Double mdgcSampAmt);
	public Double getMdgcApolar();
	public void setMdgcApolar(Double mdgcApolar);
	public String getGmQcUser();
	public void setGmQcUser(String gmQcUser);
	public Double getGm14Dmbz();
	public void setGm14Dmbz(Double gm14Dmbz);
	public String getGmQc();
	public void setGmQc(String gmQc);
	public String getGmIqmCode();
	public void setGmIqmCode(String gmIqmCode);
	public String getGmRunNumber();
	public void setGmRunNumber(String gmRunNumber);
	public Double getMdgc5m3hP();
	public void setMdgc5m3hP(Double mdgc5m3hP);
	public Double getMdgc5m3hC();
	public void setMdgc5m3hC(Double mdgc5m3hC);
	public Double getGm1e3mbz();
	public void setGm1e3mbz(Double gm1e3mbz);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getGmSvcCode();
	public void setGmSvcCode(String gmSvcCode);
	public Double getGm12Dmbz();
	public void setGm12Dmbz(Double gm12Dmbz);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Date getGmLastUpdate();
	public void setGmLastUpdate(Date gmLastUpdate);
	public Double getGmNc9();
	public void setGmNc9(Double gmNc9);
	public Double getGmNc8();
	public void setGmNc8(Double gmNc8);
}
