package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcWholeOil extends GTOAnalysisData {
	public Double getOilPhen();
	public void setOilPhen(Double oilPhen);
	public Double getOilEcp();
	public void setOilEcp(Double oilEcp);
	public Double getOil11dmcp();
	public void setOil11dmcp(Double oil11dmcp);
	public Double getOil123tmcp();
	public void setOil123tmcp(Double oil123tmcp);
	public String getOilDataType();
	public void setOilDataType(String oilDataType);
	public Double getOil1c3dmcp();
	public void setOil1c3dmcp(Double oil1c3dmcp);
	public Date getOilAcqDate();
	public void setOilAcqDate(Date oilAcqDate);
	public Double getOil2mc7();
	public void setOil2mc7(Double oil2mc7);
	public Double getOilC25hbi();
	public void setOilC25hbi(Double oilC25hbi);
	public Double getOilIc9();
	public void setOilIc9(Double oilIc9);
	public String getOilAuthor();
	public void setOilAuthor(String oilAuthor);
	public Double getOilMcp();
	public void setOilMcp(Double oilMcp);
	public Double getOilMch();
	public void setOilMch(Double oilMch);
	public Double getOil3mp();
	public void setOil3mp(Double oil3mp);
	public Double getOil3mh();
	public void setOil3mh(Double oil3mh);
	public Double getOil22dmpr();
	public void setOil22dmpr(Double oil22dmpr);
	public Double getOil24dmh();
	public void setOil24dmh(Double oil24dmh);
	public Double getOil24dmp();
	public void setOil24dmp(Double oil24dmp);
	public Double getOilDm1();
	public void setOilDm1(Double oilDm1);
	public Double getOilDm2();
	public void setOilDm2(Double oilDm2);
	public Double getOil223tmb();
	public void setOil223tmb(Double oil223tmb);
	public Double getOil3ep();
	public void setOil3ep(Double oil3ep);
	public Double getOil223tmp();
	public void setOil223tmp(Double oil223tmp);
	public Double getOil33dmh();
	public void setOil33dmh(Double oil33dmh);
	public Double getOil33dmp();
	public void setOil33dmp(Double oil33dmp);
	public Double getOilNpBenz();
	public void setOilNpBenz(Double oilNpBenz);
	public String getOilQcUser();
	public void setOilQcUser(String oilQcUser);
	public Double getOil1t2dmcp();
	public void setOil1t2dmcp(Double oil1t2dmcp);
	public Double getOilIstdConc();
	public void setOilIstdConc(Double oilIstdConc);
	public Double getOil3mc7();
	public void setOil3mc7(Double oil3mc7);
	public Double getOilEBenz();
	public void setOilEBenz(Double oilEBenz);
	public Double getOilNc30();
	public void setOilNc30(Double oilNc30);
	public Double getOilNc23();
	public void setOilNc23(Double oilNc23);
	public Double getOilNc22();
	public void setOilNc22(Double oilNc22);
	public Double getOilNc21();
	public void setOilNc21(Double oilNc21);
	public Double getOilNc20();
	public void setOilNc20(Double oilNc20);
	public Double getOilNc27();
	public void setOilNc27(Double oilNc27);
	public Double getOilNc26();
	public void setOilNc26(Double oilNc26);
	public Double getOilNc25();
	public void setOilNc25(Double oilNc25);
	public Double getOilNc24();
	public void setOilNc24(Double oilNc24);
	public Double getOilNc29();
	public void setOilNc29(Double oilNc29);
	public Double getOilNc28();
	public void setOilNc28(Double oilNc28);
	public Double getOilNc12();
	public void setOilNc12(Double oilNc12);
	public Double getOilNc11();
	public void setOilNc11(Double oilNc11);
	public Double getOilNc10();
	public void setOilNc10(Double oilNc10);
	public Double getOilNc16();
	public void setOilNc16(Double oilNc16);
	public Double getOilNc15();
	public void setOilNc15(Double oilNc15);
	public Double getOilNc14();
	public void setOilNc14(Double oilNc14);
	public Double getOilNc13();
	public void setOilNc13(Double oilNc13);
	public Double getOilNc19();
	public void setOilNc19(Double oilNc19);
	public Double getOilNc18();
	public void setOilNc18(Double oilNc18);
	public Double getOilNc17();
	public void setOilNc17(Double oilNc17);
	public Double getOilNc41();
	public void setOilNc41(Double oilNc41);
	public Double getOilNc40();
	public void setOilNc40(Double oilNc40);
	public Double getOilNc34();
	public void setOilNc34(Double oilNc34);
	public Double getOilNc33();
	public void setOilNc33(Double oilNc33);
	public Double getOilNc32();
	public void setOilNc32(Double oilNc32);
	public Double getOilNc31();
	public void setOilNc31(Double oilNc31);
	public Double getOilNc38();
	public void setOilNc38(Double oilNc38);
	public Double getOilNc37();
	public void setOilNc37(Double oilNc37);
	public Double getOilNc36();
	public void setOilNc36(Double oilNc36);
	public Double getOilNc35();
	public void setOilNc35(Double oilNc35);
	public Double getOilNc39();
	public void setOilNc39(Double oilNc39);
	public Double getOilMXyl();
	public void setOilMXyl(Double oilMXyl);
	public String getOilSampleIdVend();
	public void setOilSampleIdVend(String oilSampleIdVend);
	public Double getOil112tmcp();
	public void setOil112tmcp(Double oil112tmcp);
	public Double getOilNc3();
	public void setOilNc3(Double oilNc3);
	public Double getOilNc2();
	public void setOilNc2(Double oilNc2);
	public Double getOilNc5();
	public void setOilNc5(Double oilNc5);
	public Double getOilNc4();
	public void setOilNc4(Double oilNc4);
	public Double getOilNc7();
	public void setOilNc7(Double oilNc7);
	public Double getOilNc6();
	public void setOilNc6(Double oilNc6);
	public Double getOilNc9();
	public void setOilNc9(Double oilNc9);
	public Double getOilNc8();
	public void setOilNc8(Double oilNc8);
	public Double getOil224tmp();
	public void setOil224tmp(Double oil224tmp);
	public Double getOil2mpr();
	public void setOil2mpr(Double oil2mpr);
	public String getOilSvcCode();
	public void setOilSvcCode(String oilSvcCode);
	public Double getOil25dmh();
	public void setOil25dmh(Double oil25dmh);
	public Double getOil124TmBenz();
	public void setOil124TmBenz(Double oil124TmBenz);
	public Double getOilOXyl();
	public void setOilOXyl(Double oilOXyl);
	public Double getOil4mc7();
	public void setOil4mc7(Double oil4mc7);
	public Double getOil22dmb();
	public void setOil22dmb(Double oil22dmb);
	public Double getOil22dmh();
	public void setOil22dmh(Double oil22dmh);
	public Double getOil22dmp();
	public void setOil22dmp(Double oil22dmp);
	public Double getOil113tmcp();
	public void setOil113tmcp(Double oil113tmcp);
	public Double getOil1c2dmcp();
	public void setOil1c2dmcp(Double oil1c2dmcp);
	public Date getOilQcDate();
	public void setOilQcDate(Date oilQcDate);
	public String getOilTmpSam();
	public void setOilTmpSam(String oilTmpSam);
	public String getOilJobId();
	public void setOilJobId(String oilJobId);
	public Double getOil1e2mBenz();
	public void setOil1e2mBenz(Double oil1e2mBenz);
	public Double getOilMpXyl();
	public void setOilMpXyl(Double oilMpXyl);
	public Date getOilLastUpdate();
	public void setOilLastUpdate(Date oilLastUpdate);
	public Double getOilSplConc();
	public void setOilSplConc(Double oilSplConc);
	public Double getOilIc10();
	public void setOilIc10(Double oilIc10);
	public Double getOilIc11();
	public void setOilIc11(Double oilIc11);
	public Double getOilIc12();
	public void setOilIc12(Double oilIc12);
	public Double getOilIc13();
	public void setOilIc13(Double oilIc13);
	public Double getOilIc14();
	public void setOilIc14(Double oilIc14);
	public Double getOilIc15();
	public void setOilIc15(Double oilIc15);
	public Double getOilIc16();
	public void setOilIc16(Double oilIc16);
	public Double getOilIc18();
	public void setOilIc18(Double oilIc18);
	public Double getOil1e4mBenz();
	public void setOil1e4mBenz(Double oil1e4mBenz);
	public Double getOilIpBenz();
	public void setOilIpBenz(Double oilIpBenz);
	public Double getOil135TmBenz();
	public void setOil135TmBenz(Double oil135TmBenz);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getOilIstd();
	public void setOilIstd(Double oilIstd);
	public String getOilIqmCode();
	public void setOilIqmCode(String oilIqmCode);
	public Double getOilCh();
	public void setOilCh(Double oilCh);
	public String getOilRunNumber();
	public void setOilRunNumber(String oilRunNumber);
	public Double getOilCp();
	public void setOilCp(Double oilCp);
	public Double getOilEtch();
	public void setOilEtch(Double oilEtch);
	public Double getOilBz();
	public void setOilBz(Double oilBz);
	public String getOilQc();
	public void setOilQc(String oilQc);
	public Double getOilPh();
	public void setOilPh(Double oilPh);
	public Double getOilPr();
	public void setOilPr(Double oilPr);
	public Double getOil1e3mBenz();
	public void setOil1e3mBenz(Double oil1e3mBenz);
	public String getOilMethod();
	public void setOilMethod(String oilMethod);
	public Double getOil1t3dmcp();
	public void setOil1t3dmcp(Double oil1t3dmcp);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getOilLab();
	public void setOilLab(String oilLab);
	public Double getOil2mp();
	public void setOil2mp(Double oil2mp);
	public Double getOil2mh();
	public void setOil2mh(Double oil2mh);
	public Double getOil2mb();
	public void setOil2mb(Double oil2mb);
	public Double getOilTol();
	public void setOilTol(Double oilTol);
	public Double getOil124tmcp();
	public void setOil124tmcp(Double oil124tmcp);
	public String getOilComments();
	public void setOilComments(String oilComments);
	public Double getOil11dmch();
	public void setOil11dmch(Double oil11dmch);
	public Double getOilPXyl();
	public void setOilPXyl(Double oilPXyl);
	public Double getOil23dmbCp();
	public void setOil23dmbCp(Double oil23dmbCp);
	public Double getOil234tmp();
	public void setOil234tmp(Double oil234tmp);
	public Double getOil23dmb();
	public void setOil23dmb(Double oil23dmb);
	public Double getOil23dmh();
	public void setOil23dmh(Double oil23dmh);
	public Double getOil23dmp();
	public void setOil23dmp(Double oil23dmp);
	public Double getOilMch1c2dmcp();
	public void setOilMch1c2dmcp(Double oilMch1c2dmcp);
	public Double getOilItsd();
	public void setOilItsd(Double oilItsd);
	public Double getOilIc4();
	public void setOilIc4(Double oilIc4);
	public Double getOilIc5();
	public void setOilIc5(Double oilIc5);
	public Double getOilXylene();
	public void setOilXylene(Double oilXylene);
}
