package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcGcMs extends GTOAnalysisData {
	public Double getGcgcmsComp127Area();
	public void setGcgcmsComp127Area(Double gcgcmsComp127Area);
	public Double getGcgcmsComp102Area();
	public void setGcgcmsComp102Area(Double gcgcmsComp102Area);
	public Double getGcgcmsComp093Ppm();
	public void setGcgcmsComp093Ppm(Double gcgcmsComp093Ppm);
	public Double getGcgcms1EDiamPpm();
	public void setGcgcms1EDiamPpm(Double gcgcms1EDiamPpm);
	public Double getGcgcmsC3TetramPpm();
	public void setGcgcmsC3TetramPpm(Double gcgcmsC3TetramPpm);
	public Double getGcgcmsC624EdamPpm();
	public void setGcgcmsC624EdamPpm(Double gcgcmsC624EdamPpm);
	public String getGcgcmsLab();
	public void setGcgcmsLab(String gcgcmsLab);
	public Double getGcgcms1224DmDiamPpm();
	public void setGcgcms1224DmDiamPpm(Double gcgcms1224DmDiamPpm);
	public Double getGcgcmsComp133Ppm();
	public void setGcgcmsComp133Ppm(Double gcgcmsComp133Ppm);
	public Double getGcgcmsComp134Area();
	public void setGcgcmsComp134Area(Double gcgcmsComp134Area);
	public String getGcgcmsDataType();
	public void setGcgcmsDataType(String gcgcmsDataType);
	public Double getGcgcmsMiscC5AdamPpm();
	public void setGcgcmsMiscC5AdamPpm(Double gcgcmsMiscC5AdamPpm);
	public Double getGcgcmsComp106Ppm();
	public void setGcgcmsComp106Ppm(Double gcgcmsComp106Ppm);
	public Double getGcgcmsComp131Area();
	public void setGcgcmsComp131Area(Double gcgcmsComp131Area);
	public Double getGcgcmsC5AdamPpm();
	public void setGcgcmsC5AdamPpm(Double gcgcmsC5AdamPpm);
	public Double getGcgcms2426DmAdam2();
	public void setGcgcms2426DmAdam2(Double gcgcms2426DmAdam2);
	public Double getGcgcms2426DmAdam1();
	public void setGcgcms2426DmAdam1(Double gcgcms2426DmAdam1);
	public Double getGcgcms59DmTriam();
	public void setGcgcms59DmTriam(Double gcgcms59DmTriam);
	public Double getGcgcms1EAdam();
	public void setGcgcms1EAdam(Double gcgcms1EAdam);
	public Double getGcgcmsComp141Area();
	public void setGcgcmsComp141Area(Double gcgcmsComp141Area);
	public String getGcgcmsQcUser();
	public void setGcgcmsQcUser(String gcgcmsQcUser);
	public Double getGcgcms349TmDiamPpm();
	public void setGcgcms349TmDiamPpm(Double gcgcms349TmDiamPpm);
	public Double getGcgcms1e3mAdamPpm();
	public void setGcgcms1e3mAdamPpm(Double gcgcms1e3mAdamPpm);
	public Double getGcgcmsC7AdamPpm();
	public void setGcgcmsC7AdamPpm(Double gcgcmsC7AdamPpm);
	public Double getGcgcmsTetram2Ppm();
	public void setGcgcmsTetram2Ppm(Double gcgcmsTetram2Ppm);
	public Double getGcgcmsDiam();
	public void setGcgcmsDiam(Double gcgcmsDiam);
	public Double getGcgcmsC4AdamPpm();
	public void setGcgcmsC4AdamPpm(Double gcgcmsC4AdamPpm);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getGcgcmsComp145Ppm();
	public void setGcgcmsComp145Ppm(Double gcgcmsComp145Ppm);
	public Double getGcgcms1e3mAdam();
	public void setGcgcms1e3mAdam(Double gcgcms1e3mAdam);
	public Double getGcgcms1mDiam();
	public void setGcgcms1mDiam(Double gcgcms1mDiam);
	public Double getGcgcmsComp124Ppm();
	public void setGcgcmsComp124Ppm(Double gcgcmsComp124Ppm);
	public Double getGcgcms1357TmAdam();
	public void setGcgcms1357TmAdam(Double gcgcms1357TmAdam);
	public String getGcgcmsAuthor();
	public void setGcgcmsAuthor(String gcgcmsAuthor);
	public Double getGcgcmsComp098Area();
	public void setGcgcmsComp098Area(Double gcgcmsComp098Area);
	public Double getGcgcmsComp115Ppm();
	public void setGcgcmsComp115Ppm(Double gcgcmsComp115Ppm);
	public Double getGcgcmsC3TriamPpm();
	public void setGcgcmsC3TriamPpm(Double gcgcmsC3TriamPpm);
	public Double getGcgcmsComp149Area();
	public void setGcgcmsComp149Area(Double gcgcmsComp149Area);
	public Double getGcgcmsC1TriamPpm();
	public void setGcgcmsC1TriamPpm(Double gcgcmsC1TriamPpm);
	public Double getGcgcmsC4Adam();
	public void setGcgcmsC4Adam(Double gcgcmsC4Adam);
	public Double getGcgcms914DmTriam();
	public void setGcgcms914DmTriam(Double gcgcms914DmTriam);
	public Double getGcgcms13DmAdamPpm();
	public void setGcgcms13DmAdamPpm(Double gcgcms13DmAdamPpm);
	public Double getGcgcms24EdamPpm();
	public void setGcgcms24EdamPpm(Double gcgcms24EdamPpm);
	public Double getGcgcms914DmTriamPpm();
	public void setGcgcms914DmTriamPpm(Double gcgcms914DmTriamPpm);
	public Double getGcgcmsMiscTmAdam();
	public void setGcgcmsMiscTmAdam(Double gcgcmsMiscTmAdam);
	public Double getGcgcms123TmAdamPpm();
	public void setGcgcms123TmAdamPpm(Double gcgcms123TmAdamPpm);
	public Double getGcgcmsComp090Area();
	public void setGcgcmsComp090Area(Double gcgcmsComp090Area);
	public Double getGcgcms13DmAdam();
	public void setGcgcms13DmAdam(Double gcgcms13DmAdam);
	public Double getGcgcmsPtqAdamPpm();
	public void setGcgcmsPtqAdamPpm(Double gcgcmsPtqAdamPpm);
	public Double getGcgcms2mAdamPpm();
	public void setGcgcms2mAdamPpm(Double gcgcms2mAdamPpm);
	public Double getGcgcmsC2Diam();
	public void setGcgcmsC2Diam(Double gcgcmsC2Diam);
	public Double getGcgcmsC2DiamPpm();
	public void setGcgcmsC2DiamPpm(Double gcgcmsC2DiamPpm);
	public Double getGcgcmsC324EdamPpm();
	public void setGcgcmsC324EdamPpm(Double gcgcmsC324EdamPpm);
	public Double getGcgcmsComp089Ppm();
	public void setGcgcmsComp089Ppm(Double gcgcmsComp089Ppm);
	public Double getGcgcmsComp109Ppm();
	public void setGcgcmsComp109Ppm(Double gcgcmsComp109Ppm);
	public Double getGcgcmsComp092Area();
	public void setGcgcmsComp092Area(Double gcgcmsComp092Area);
	public Double getGcgcmsComp114Area();
	public void setGcgcmsComp114Area(Double gcgcmsComp114Area);
	public Double getGcgcmsComp121Area();
	public void setGcgcmsComp121Area(Double gcgcmsComp121Area);
	public Double getGcgcmsComp108Area();
	public void setGcgcmsComp108Area(Double gcgcmsComp108Area);
	public Double getGcgcmsComp090Ppm();
	public void setGcgcmsComp090Ppm(Double gcgcmsComp090Ppm);
	public Double getGcgcmsComp115Area();
	public void setGcgcmsComp115Area(Double gcgcmsComp115Area);
	public Double getGcgcmsComp136Ppm();
	public void setGcgcmsComp136Ppm(Double gcgcmsComp136Ppm);
	public Double getGcgcmsIstd3Ppm();
	public void setGcgcmsIstd3Ppm(Double gcgcmsIstd3Ppm);
	public Double getGcgcmsTr14DmAdam();
	public void setGcgcmsTr14DmAdam(Double gcgcmsTr14DmAdam);
	public Double getGcgcmsComp118Ppm();
	public void setGcgcmsComp118Ppm(Double gcgcmsComp118Ppm);
	public Double getGcgcms5mTriam();
	public void setGcgcms5mTriam(Double gcgcms5mTriam);
	public Double getGcgcmsComp147Area();
	public void setGcgcmsComp147Area(Double gcgcmsComp147Area);
	public Double getGcgcms1mDiamPpm();
	public void setGcgcms1mDiamPpm(Double gcgcms1mDiamPpm);
	public Double getGcgcms915DmTriam();
	public void setGcgcms915DmTriam(Double gcgcms915DmTriam);
	public Double getGcgcmsComp107Area();
	public void setGcgcmsComp107Area(Double gcgcmsComp107Area);
	public Double getGcgcms5915TmTriamPpm();
	public void setGcgcms5915TmTriamPpm(Double gcgcms5915TmTriamPpm);
	public Double getGcgcmsComp101Ppm();
	public void setGcgcmsComp101Ppm(Double gcgcmsComp101Ppm);
	public Double getGcgcmsComp098Ppm();
	public void setGcgcmsComp098Ppm(Double gcgcmsComp098Ppm);
	public Double getGcgcmsMiscC4AdamPpm();
	public void setGcgcmsMiscC4AdamPpm(Double gcgcmsMiscC4AdamPpm);
	public String getGcgcmsComment();
	public void setGcgcmsComment(String gcgcmsComment);
	public Double getGcgcms49DmDiamPpm();
	public void setGcgcms49DmDiamPpm(Double gcgcms49DmDiamPpm);
	public Double getGcgcms136TmAdam();
	public void setGcgcms136TmAdam(Double gcgcms136TmAdam);
	public Double getGcgcms2426DmAdam1Ppm();
	public void setGcgcms2426DmAdam1Ppm(Double gcgcms2426DmAdam1Ppm);
	public Double getGcgcmsComp122Area();
	public void setGcgcmsComp122Area(Double gcgcmsComp122Area);
	public Double getGcgcmsComp110Ppm();
	public void setGcgcmsComp110Ppm(Double gcgcmsComp110Ppm);
	public Double getGcgcmsC6AdamPpm();
	public void setGcgcmsC6AdamPpm(Double gcgcmsC6AdamPpm);
	public Double getGcgcms16mTriamPpm();
	public void setGcgcms16mTriamPpm(Double gcgcms16mTriamPpm);
	public Double getGcgcmsComp142Ppm();
	public void setGcgcmsComp142Ppm(Double gcgcmsComp142Ppm);
	public Double getGcgcmsComp127Ppm();
	public void setGcgcmsComp127Ppm(Double gcgcmsComp127Ppm);
	public Double getGcgcms2EDiam();
	public void setGcgcms2EDiam(Double gcgcms2EDiam);
	public Double getGcgcmsIstd3Area();
	public void setGcgcmsIstd3Area(Double gcgcmsIstd3Area);
	public Double getGcgcmsC3DiamPpm();
	public void setGcgcmsC3DiamPpm(Double gcgcmsC3DiamPpm);
	public Double getGcgcms49DmDiam();
	public void setGcgcms49DmDiam(Double gcgcms49DmDiam);
	public Double getGcgcmsCis134TmAdamPpm();
	public void setGcgcmsCis134TmAdamPpm(Double gcgcmsCis134TmAdamPpm);
	public Double getGcgcmsIstd1Area();
	public void setGcgcmsIstd1Area(Double gcgcmsIstd1Area);
	public Double getGcgcmsComp089Area();
	public void setGcgcmsComp089Area(Double gcgcmsComp089Area);
	public Double getGcgcmsCis14DmAdam();
	public void setGcgcmsCis14DmAdam(Double gcgcmsCis14DmAdam);
	public Double getGcgcms1EAdamPpm();
	public void setGcgcms1EAdamPpm(Double gcgcms1EAdamPpm);
	public Double getGcgcms12357PmAdam();
	public void setGcgcms12357PmAdam(Double gcgcms12357PmAdam);
	public Double getGcgcmsComp091Ppm();
	public void setGcgcmsComp091Ppm(Double gcgcmsComp091Ppm);
	public Double getGcgcmsComp108Ppm();
	public void setGcgcmsComp108Ppm(Double gcgcmsComp108Ppm);
	public Double getGcgcmsC6Adam();
	public void setGcgcmsC6Adam(Double gcgcmsC6Adam);
	public Double getGcgcms59DmTriamPpm();
	public void setGcgcms59DmTriamPpm(Double gcgcms59DmTriamPpm);
	public Double getGcgcmsComp104Area();
	public void setGcgcmsComp104Area(Double gcgcmsComp104Area);
	public Double getGcgcmsComp147Ppm();
	public void setGcgcmsComp147Ppm(Double gcgcmsComp147Ppm);
	public Double getGcgcms5915TmTriam();
	public void setGcgcms5915TmTriam(Double gcgcms5915TmTriam);
	public Double getGcgcmsComp135Ppm();
	public void setGcgcmsComp135Ppm(Double gcgcmsComp135Ppm);
	public Double getGcgcms34DmDiamPpm();
	public void setGcgcms34DmDiamPpm(Double gcgcms34DmDiamPpm);
	public Double getGcgcmsComp093Area();
	public void setGcgcmsComp093Area(Double gcgcmsComp093Area);
	public Double getGcgcms1e357TmAdam();
	public void setGcgcms1e357TmAdam(Double gcgcms1e357TmAdam);
	public Double getGcgcmsTriamPpm();
	public void setGcgcmsTriamPpm(Double gcgcmsTriamPpm);
	public Double getGcgcmsC4DiamPpm();
	public void setGcgcmsC4DiamPpm(Double gcgcmsC4DiamPpm);
	public Double getGcgcmsPtqAdam();
	public void setGcgcmsPtqAdam(Double gcgcmsPtqAdam);
	public Double getGcgcms1EDiam();
	public void setGcgcms1EDiam(Double gcgcms1EDiam);
	public Double getGcgcmsAdam();
	public void setGcgcmsAdam(Double gcgcmsAdam);
	public Double getGcgcmsComp133Area();
	public void setGcgcmsComp133Area(Double gcgcmsComp133Area);
	public Double getGcgcmsComp150Area();
	public void setGcgcmsComp150Area(Double gcgcmsComp150Area);
	public Double getGcgcmsComp117Ppm();
	public void setGcgcmsComp117Ppm(Double gcgcmsComp117Ppm);
	public Double getGcgcms2426DmAdam2Ppm();
	public void setGcgcms2426DmAdam2Ppm(Double gcgcms2426DmAdam2Ppm);
	public Double getGcgcmsComp146Area();
	public void setGcgcmsComp146Area(Double gcgcmsComp146Area);
	public Double getGcgcms1mAdam();
	public void setGcgcms1mAdam(Double gcgcms1mAdam);
	public Double getGcgcmsComp100Ppm();
	public void setGcgcmsComp100Ppm(Double gcgcmsComp100Ppm);
	public Double getGcgcmsCis14DmAdamPpm();
	public void setGcgcmsCis14DmAdamPpm(Double gcgcmsCis14DmAdamPpm);
	public Double getGcgcms1235TmAdamPpm();
	public void setGcgcms1235TmAdamPpm(Double gcgcms1235TmAdamPpm);
	public Double getGcgcmsComp126Ppm();
	public void setGcgcmsComp126Ppm(Double gcgcmsComp126Ppm);
	public Double getGcgcms4mDiam();
	public void setGcgcms4mDiam(Double gcgcms4mDiam);
	public Double getGcgcms2mAdam();
	public void setGcgcms2mAdam(Double gcgcms2mAdam);
	public Double getGcgcms149TmDiamPpm();
	public void setGcgcms149TmDiamPpm(Double gcgcms149TmDiamPpm);
	public Double getGcgcmsC4Diam();
	public void setGcgcmsC4Diam(Double gcgcmsC4Diam);
	public Double getGcgcmsComp136Area();
	public void setGcgcmsComp136Area(Double gcgcmsComp136Area);
	public Double getGcgcmsComp099Ppm();
	public void setGcgcmsComp099Ppm(Double gcgcmsComp099Ppm);
	public Double getGcgcms34DmDiam();
	public void setGcgcms34DmDiam(Double gcgcms34DmDiam);
	public Double getGcgcmsMiscC3DiamPpm();
	public void setGcgcmsMiscC3DiamPpm(Double gcgcmsMiscC3DiamPpm);
	public Double getGcgcmsMiscC3Diam();
	public void setGcgcmsMiscC3Diam(Double gcgcmsMiscC3Diam);
	public Double getGcgcmsComp144Area();
	public void setGcgcmsComp144Area(Double gcgcmsComp144Area);
	public Double getGcgcms1356TmAdam();
	public void setGcgcms1356TmAdam(Double gcgcms1356TmAdam);
	public Double getGcgcmsComp121Ppm();
	public void setGcgcmsComp121Ppm(Double gcgcmsComp121Ppm);
	public Double getGcgcmsComp096Ppm();
	public void setGcgcmsComp096Ppm(Double gcgcmsComp096Ppm);
	public Double getGcgcmsComp112Area();
	public void setGcgcmsComp112Area(Double gcgcmsComp112Area);
	public Double getGcgcmsComp103Ppm();
	public void setGcgcmsComp103Ppm(Double gcgcmsComp103Ppm);
	public Double getGcgcmsComp130Ppm();
	public void setGcgcmsComp130Ppm(Double gcgcmsComp130Ppm);
	public Double getGcgcmsComp095Area();
	public void setGcgcmsComp095Area(Double gcgcmsComp095Area);
	public Double getGcgcmsComp117Area();
	public void setGcgcmsComp117Area(Double gcgcmsComp117Area);
	public Double getGcgcmsC124EdamPpm();
	public void setGcgcmsC124EdamPpm(Double gcgcmsC124EdamPpm);
	public Double getGcgcmsTetram2();
	public void setGcgcmsTetram2(Double gcgcmsTetram2);
	public Double getGcgcmsTetram1();
	public void setGcgcmsTetram1(Double gcgcmsTetram1);
	public Double getGcgcmsTetram3();
	public void setGcgcmsTetram3(Double gcgcmsTetram3);
	public Double getGcgcmsC2AdamPpm();
	public void setGcgcmsC2AdamPpm(Double gcgcmsC2AdamPpm);
	public Double getGcgcms9mTriam();
	public void setGcgcms9mTriam(Double gcgcms9mTriam);
	public Double getGcgcms16mTriam();
	public void setGcgcms16mTriam(Double gcgcms16mTriam);
	public Double getGcgcmsAdamPpm();
	public void setGcgcmsAdamPpm(Double gcgcmsAdamPpm);
	public Double getGcgcms1e357TmAdamPpm();
	public void setGcgcms1e357TmAdamPpm(Double gcgcms1e357TmAdamPpm);
	public Double getGcgcms1235TmAdam();
	public void setGcgcms1235TmAdam(Double gcgcms1235TmAdam);
	public Double getGcgcmsC124Edam();
	public void setGcgcmsC124Edam(Double gcgcmsC124Edam);
	public Double getGcgcmsComp144Ppm();
	public void setGcgcmsComp144Ppm(Double gcgcmsComp144Ppm);
	public Double getGcgcmsComp138Ppm();
	public void setGcgcmsComp138Ppm(Double gcgcmsComp138Ppm);
	public Double getGcgcmsC3Adam();
	public void setGcgcmsC3Adam(Double gcgcmsC3Adam);
	public Double getGcgcmsComp125Area();
	public void setGcgcmsComp125Area(Double gcgcmsComp125Area);
	public Double getGcgcmsIstd1Ppm();
	public void setGcgcmsIstd1Ppm(Double gcgcmsIstd1Ppm);
	public Double getGcgcms1e35DmAdam();
	public void setGcgcms1e35DmAdam(Double gcgcms1e35DmAdam);
	public Double getGcgcmsTetram3Ppm();
	public void setGcgcmsTetram3Ppm(Double gcgcmsTetram3Ppm);
	public Double getGcgcmsMiscC5Adam();
	public void setGcgcmsMiscC5Adam(Double gcgcmsMiscC5Adam);
	public String getGcgcmsIstd2Name();
	public void setGcgcmsIstd2Name(String gcgcmsIstd2Name);
	public Double getGcgcmsC624Edam();
	public void setGcgcmsC624Edam(Double gcgcmsC624Edam);
	public Double getGcgcmsC1Tetram();
	public void setGcgcmsC1Tetram(Double gcgcmsC1Tetram);
	public Double getGcgcmsC4Tetram();
	public void setGcgcmsC4Tetram(Double gcgcmsC4Tetram);
	public Double getGcgcmsC424EdamPpm();
	public void setGcgcmsC424EdamPpm(Double gcgcmsC424EdamPpm);
	public String getGcgcmsIqmCode();
	public void setGcgcmsIqmCode(String gcgcmsIqmCode);
	public Double getGcgcmsC2Triam();
	public void setGcgcmsC2Triam(Double gcgcmsC2Triam);
	public Double getGcgcmsComp129Ppm();
	public void setGcgcmsComp129Ppm(Double gcgcmsComp129Ppm);
	public Double getGcgcmsC2TriamPpm();
	public void setGcgcmsC2TriamPpm(Double gcgcmsC2TriamPpm);
	public Double getGcgcms135TmAdamPpm();
	public void setGcgcms135TmAdamPpm(Double gcgcms135TmAdamPpm);
	public Double getGcgcmsComp112Ppm();
	public void setGcgcmsComp112Ppm(Double gcgcmsComp112Ppm);
	public Double getGcgcmsC6DiamPpm();
	public void setGcgcmsC6DiamPpm(Double gcgcmsC6DiamPpm);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getGcgcmsComp120Ppm();
	public void setGcgcmsComp120Ppm(Double gcgcmsComp120Ppm);
	public Double getGcgcms9mTriamPpm();
	public void setGcgcms9mTriamPpm(Double gcgcms9mTriamPpm);
	public Double getGcgcmsC8Adam();
	public void setGcgcmsC8Adam(Double gcgcmsC8Adam);
	public Double getGcgcmsC2TetramPpm();
	public void setGcgcmsC2TetramPpm(Double gcgcmsC2TetramPpm);
	public Date getGcgcmsDate();
	public void setGcgcmsDate(Date gcgcmsDate);
	public Double getGcgcmsMiscC4Adam();
	public void setGcgcmsMiscC4Adam(Double gcgcmsMiscC4Adam);
	public Double getGcgcms915DmTriamPpm();
	public void setGcgcms915DmTriamPpm(Double gcgcms915DmTriamPpm);
	public Double getGcgcmsComp120Area();
	public void setGcgcmsComp120Area(Double gcgcmsComp120Area);
	public Double getGcgcmsComp145Area();
	public void setGcgcmsComp145Area(Double gcgcmsComp145Area);
	public Double getGcgcmsComp102Ppm();
	public void setGcgcmsComp102Ppm(Double gcgcmsComp102Ppm);
	public String getGcgcmsIsExternalStd();
	public void setGcgcmsIsExternalStd(String gcgcmsIsExternalStd);
	public String getGcgcmsSampleIdVend();
	public void setGcgcmsSampleIdVend(String gcgcmsSampleIdVend);
	public String getGcgcmsRunNumber();
	public void setGcgcmsRunNumber(String gcgcmsRunNumber);
	public Double getGcgcms48DmDiamPpm();
	public void setGcgcms48DmDiamPpm(Double gcgcms48DmDiamPpm);
	public Double getGcgcmsComp138Area();
	public void setGcgcmsComp138Area(Double gcgcmsComp138Area);
	public Double getGcgcms136TmAdamPpm();
	public void setGcgcms136TmAdamPpm(Double gcgcms136TmAdamPpm);
	public Double getGcgcmsC424Edam();
	public void setGcgcmsC424Edam(Double gcgcmsC424Edam);
	public Double getGcgcms39496979DmTriam();
	public void setGcgcms39496979DmTriam(Double gcgcms39496979DmTriam);
	public Double getGcgcmsC6Diam();
	public void setGcgcmsC6Diam(Double gcgcmsC6Diam);
	public Double getGcgcmsIstdPpm();
	public void setGcgcmsIstdPpm(Double gcgcmsIstdPpm);
	public Double getGcgcmsComp149Ppm();
	public void setGcgcmsComp149Ppm(Double gcgcmsComp149Ppm);
	public Double getGcgcms135TmAdam();
	public void setGcgcms135TmAdam(Double gcgcms135TmAdam);
	public Double getGcgcmsC3Tetram();
	public void setGcgcmsC3Tetram(Double gcgcmsC3Tetram);
	public Double getGcgcmsComp119Ppm();
	public void setGcgcmsComp119Ppm(Double gcgcmsComp119Ppm);
	public Double getGcgcmsComp137Ppm();
	public void setGcgcmsComp137Ppm(Double gcgcmsComp137Ppm);
	public Double getGcgcmsC4TetramPpm();
	public void setGcgcmsC4TetramPpm(Double gcgcmsC4TetramPpm);
	public Double getGcgcmsComp123Area();
	public void setGcgcmsComp123Area(Double gcgcmsComp123Area);
	public Double getGcgcmsComp150Ppm();
	public void setGcgcmsComp150Ppm(Double gcgcmsComp150Ppm);
	public Double getGcgcms4mDiamPpm();
	public void setGcgcms4mDiamPpm(Double gcgcms4mDiamPpm);
	public Double getGcgcmsIstd2Ppm();
	public void setGcgcmsIstd2Ppm(Double gcgcmsIstd2Ppm);
	public Double getGcgcmsC524Edam();
	public void setGcgcmsC524Edam(Double gcgcmsC524Edam);
	public Double getGcgcmsC224EdamPpm();
	public void setGcgcmsC224EdamPpm(Double gcgcmsC224EdamPpm);
	public String getGcgcmsExtStdId3();
	public void setGcgcmsExtStdId3(String gcgcmsExtStdId3);
	public String getGcgcmsExtStdId2();
	public void setGcgcmsExtStdId2(String gcgcmsExtStdId2);
	public String getGcgcmsExtStdId1();
	public void setGcgcmsExtStdId1(String gcgcmsExtStdId1);
	public Integer getGcgcmsMethod();
	public void setGcgcmsMethod(Integer gcgcmsMethod);
	public Double getGcgcmsComp097Ppm();
	public void setGcgcmsComp097Ppm(Double gcgcmsComp097Ppm);
	public String getGcgcmsSvcCode();
	public void setGcgcmsSvcCode(String gcgcmsSvcCode);
	public Double getGcgcmsComp109Area();
	public void setGcgcmsComp109Area(Double gcgcmsComp109Area);
	public Double getGcgcmsComp113Area();
	public void setGcgcmsComp113Area(Double gcgcmsComp113Area);
	public Double getGcgcmsComp116Area();
	public void setGcgcmsComp116Area(Double gcgcmsComp116Area);
	public Double getGcgcmsComp111Ppm();
	public void setGcgcmsComp111Ppm(Double gcgcmsComp111Ppm);
	public Double getGcgcmsTr14DmAdamPpm();
	public void setGcgcmsTr14DmAdamPpm(Double gcgcmsTr14DmAdamPpm);
	public Double getGcgcmsComp141Ppm();
	public void setGcgcmsComp141Ppm(Double gcgcmsComp141Ppm);
	public Double getGcgcmsComp106Area();
	public void setGcgcmsComp106Area(Double gcgcmsComp106Area);
	public Double getGcgcmsComp128Ppm();
	public void setGcgcmsComp128Ppm(Double gcgcmsComp128Ppm);
	public Double getGcgcmsComp103Area();
	public void setGcgcmsComp103Area(Double gcgcmsComp103Area);
	public Double getGcgcmsComp105Ppm();
	public void setGcgcmsComp105Ppm(Double gcgcmsComp105Ppm);
	public Double getGcgcmsComp097Area();
	public void setGcgcmsComp097Area(Double gcgcmsComp097Area);
	public Double getGcgcmsIstd2Area();
	public void setGcgcmsIstd2Area(Double gcgcmsIstd2Area);
	public Double getGcgcmsDiamPpm();
	public void setGcgcmsDiamPpm(Double gcgcmsDiamPpm);
	public Double getGcgcmsComp119Area();
	public void setGcgcmsComp119Area(Double gcgcmsComp119Area);
	public String getGcgcmsQcFlag();
	public void setGcgcmsQcFlag(String gcgcmsQcFlag);
	public Double getGcgcmsMiscC2DmDiam();
	public void setGcgcmsMiscC2DmDiam(Double gcgcmsMiscC2DmDiam);
	public Double getGcgcmsC2Tetram();
	public void setGcgcmsC2Tetram(Double gcgcmsC2Tetram);
	public Double getGcgcmsC524EdamPpm();
	public void setGcgcmsC524EdamPpm(Double gcgcmsC524EdamPpm);
	public Double getGcgcmsC224Edam();
	public void setGcgcmsC224Edam(Double gcgcmsC224Edam);
	public Double getGcgcmsComp110Area();
	public void setGcgcmsComp110Area(Double gcgcmsComp110Area);
	public Double getGcgcmsComp123Ppm();
	public void setGcgcmsComp123Ppm(Double gcgcmsComp123Ppm);
	public Double getGcgcmsComp135Area();
	public void setGcgcmsComp135Area(Double gcgcmsComp135Area);
	public Double getGcgcmsComp094Ppm();
	public void setGcgcmsComp094Ppm(Double gcgcmsComp094Ppm);
	public Double getGcgcms34DmTriam();
	public void setGcgcms34DmTriam(Double gcgcms34DmTriam);
	public Double getGcgcmsComp101Area();
	public void setGcgcmsComp101Area(Double gcgcmsComp101Area);
	public Double getGcgcmsComp130Area();
	public void setGcgcmsComp130Area(Double gcgcmsComp130Area);
	public Double getGcgcms1257TmAdamPpm();
	public void setGcgcms1257TmAdamPpm(Double gcgcms1257TmAdamPpm);
	public Double getGcgcms48DmDiam();
	public void setGcgcms48DmDiam(Double gcgcms48DmDiam);
	public Double getGcgcmsCisTr134TmAdamPpm();
	public void setGcgcmsCisTr134TmAdamPpm(Double gcgcmsCisTr134TmAdamPpm);
	public Double getGcgcmsComp132Ppm();
	public void setGcgcmsComp132Ppm(Double gcgcmsComp132Ppm);
	public Double getGcgcmsComp128Area();
	public void setGcgcmsComp128Area(Double gcgcmsComp128Area);
	public Double getGcgcmsIstd();
	public void setGcgcmsIstd(Double gcgcmsIstd);
	public Double getGcgcms8mTriam();
	public void setGcgcms8mTriam(Double gcgcms8mTriam);
	public Double getGcgcmsTetram1Ppm();
	public void setGcgcmsTetram1Ppm(Double gcgcmsTetram1Ppm);
	public Double getGcgcmsC324Edam();
	public void setGcgcmsC324Edam(Double gcgcmsC324Edam);
	public Double getGcgcmsComp148Area();
	public void setGcgcmsComp148Area(Double gcgcmsComp148Area);
	public Double getGcgcms12DmAdam();
	public void setGcgcms12DmAdam(Double gcgcms12DmAdam);
	public Double getGcgcmsComp146Ppm();
	public void setGcgcmsComp146Ppm(Double gcgcmsComp146Ppm);
	public Double getGcgcms2EDiamPpm();
	public void setGcgcms2EDiamPpm(Double gcgcms2EDiamPpm);
	public Double getGcgcmsC3Diam();
	public void setGcgcmsC3Diam(Double gcgcmsC3Diam);
	public Double getGcgcms24Edam();
	public void setGcgcms24Edam(Double gcgcms24Edam);
	public Double getGcgcms1257TmAdam();
	public void setGcgcms1257TmAdam(Double gcgcms1257TmAdam);
	public Double getGcgcmsC5Adam();
	public void setGcgcmsC5Adam(Double gcgcmsC5Adam);
	public Double getGcgcmsComp091Area();
	public void setGcgcmsComp091Area(Double gcgcmsComp091Area);
	public Double getGcgcmsC3Triam();
	public void setGcgcmsC3Triam(Double gcgcmsC3Triam);
	public Double getGcgcmsMiscC2DmDiamPpm();
	public void setGcgcmsMiscC2DmDiamPpm(Double gcgcmsMiscC2DmDiamPpm);
	public Double getGcgcmsC4TriamPpm();
	public void setGcgcmsC4TriamPpm(Double gcgcmsC4TriamPpm);
	public Double getGcgcmsComp142Area();
	public void setGcgcmsComp142Area(Double gcgcmsComp142Area);
	public Double getGcgcmsC1Triam();
	public void setGcgcmsC1Triam(Double gcgcmsC1Triam);
	public Double getGcgcmsComp114Ppm();
	public void setGcgcmsComp114Ppm(Double gcgcmsComp114Ppm);
	public Double getGcgcms149TmDiam();
	public void setGcgcms149TmDiam(Double gcgcms149TmDiam);
	public Double getGcgcmsC5DiamPpm();
	public void setGcgcmsC5DiamPpm(Double gcgcmsC5DiamPpm);
	public Double getGcgcmsComp095Ppm();
	public void setGcgcmsComp095Ppm(Double gcgcmsComp095Ppm);
	public Double getGcgcmsComp104Ppm();
	public void setGcgcmsComp104Ppm(Double gcgcmsComp104Ppm);
	public Double getGcgcmsComp143Area();
	public void setGcgcmsComp143Area(Double gcgcmsComp143Area);
	public Double getGcgcmsComp131Ppm();
	public void setGcgcmsComp131Ppm(Double gcgcmsComp131Ppm);
	public Double getGcgcmsComp122Ppm();
	public void setGcgcmsComp122Ppm(Double gcgcmsComp122Ppm);
	public Double getGcgcms123TmAdam();
	public void setGcgcms123TmAdam(Double gcgcms123TmAdam);
	public Double getGcgcmsTr134TmAdamPpm();
	public void setGcgcmsTr134TmAdamPpm(Double gcgcmsTr134TmAdamPpm);
	public Double getGcgcms34DmTriamPpm();
	public void setGcgcms34DmTriamPpm(Double gcgcms34DmTriamPpm);
	public String getGcgcmsJobId();
	public void setGcgcmsJobId(String gcgcmsJobId);
	public Double getGcgcms12DmAdamPpm();
	public void setGcgcms12DmAdamPpm(Double gcgcms12DmAdamPpm);
	public Double getGcgcmsComp096Area();
	public void setGcgcmsComp096Area(Double gcgcmsComp096Area);
	public Double getGcgcmsComp118Area();
	public void setGcgcmsComp118Area(Double gcgcmsComp118Area);
	public Double getGcgcmsComp111Area();
	public void setGcgcmsComp111Area(Double gcgcmsComp111Area);
	public Double getGcgcmsTr134TmAdam();
	public void setGcgcmsTr134TmAdam(Double gcgcmsTr134TmAdam);
	public Double getGcgcmsComp143Ppm();
	public void setGcgcmsComp143Ppm(Double gcgcmsComp143Ppm);
	public Double getGcgcms39496979DmTriamPpm();
	public void setGcgcms39496979DmTriamPpm(Double gcgcms39496979DmTriamPpm);
	public Double getGcgcmsComp139Area();
	public void setGcgcmsComp139Area(Double gcgcmsComp139Area);
	public Double getGcgcms1357TmAdamPpm();
	public void setGcgcms1357TmAdamPpm(Double gcgcms1357TmAdamPpm);
	public Double getGcgcmsMiscEmAdamPpm();
	public void setGcgcmsMiscEmAdamPpm(Double gcgcmsMiscEmAdamPpm);
	public Double getGcgcmsComp100Area();
	public void setGcgcmsComp100Area(Double gcgcmsComp100Area);
	public Double getGcgcms349TmDiam();
	public void setGcgcms349TmDiam(Double gcgcms349TmDiam);
	public Double getGcgcmsCisTr134TmAdam();
	public void setGcgcmsCisTr134TmAdam(Double gcgcmsCisTr134TmAdam);
	public Double getGcgcmsTriam();
	public void setGcgcmsTriam(Double gcgcmsTriam);
	public Double getGcgcmsComp140Area();
	public void setGcgcmsComp140Area(Double gcgcmsComp140Area);
	public Double getGcgcmsSumPrAdamPpm();
	public void setGcgcmsSumPrAdamPpm(Double gcgcmsSumPrAdamPpm);
	public Double getGcgcmsComp139Ppm();
	public void setGcgcmsComp139Ppm(Double gcgcmsComp139Ppm);
	public Double getGcgcms39154915TmTriamPpm();
	public void setGcgcms39154915TmTriamPpm(Double gcgcms39154915TmTriamPpm);
	public Double getGcgcms5mTriamPpm();
	public void setGcgcms5mTriamPpm(Double gcgcms5mTriamPpm);
	public Double getGcgcmsComp129Area();
	public void setGcgcmsComp129Area(Double gcgcmsComp129Area);
	public Double getGcgcms39154915TmTriam();
	public void setGcgcms39154915TmTriam(Double gcgcms39154915TmTriam);
	public Double getGcgcmsMiscTmAdamPpm();
	public void setGcgcmsMiscTmAdamPpm(Double gcgcmsMiscTmAdamPpm);
	public Double getGcgcmsMiscEmAdam();
	public void setGcgcmsMiscEmAdam(Double gcgcmsMiscEmAdam);
	public Double getGcgcms3mDiam();
	public void setGcgcms3mDiam(Double gcgcms3mDiam);
	public Double getGcgcms12357PmAdamPpm();
	public void setGcgcms12357PmAdamPpm(Double gcgcms12357PmAdamPpm);
	public Double getGcgcmsComp113Ppm();
	public void setGcgcmsComp113Ppm(Double gcgcmsComp113Ppm);
	public Double getGcgcmsComp126Area();
	public void setGcgcmsComp126Area(Double gcgcmsComp126Area);
	public Double getGcgcmsC8AdamPpm();
	public void setGcgcmsC8AdamPpm(Double gcgcmsC8AdamPpm);
	public Double getGcgcmsC3AdamPpm();
	public void setGcgcmsC3AdamPpm(Double gcgcmsC3AdamPpm);
	public Double getGcgcmsC7Adam();
	public void setGcgcmsC7Adam(Double gcgcmsC7Adam);
	public Date getGcgcmsQcDate();
	public void setGcgcmsQcDate(Date gcgcmsQcDate);
	public Double getGcgcmsComp137Area();
	public void setGcgcmsComp137Area(Double gcgcmsComp137Area);
	public Double getGcgcms3mDiamPpm();
	public void setGcgcms3mDiamPpm(Double gcgcms3mDiamPpm);
	public String getGcgcmsIstd3Name();
	public void setGcgcmsIstd3Name(String gcgcmsIstd3Name);
	public Double getGcgcmsC2Adam();
	public void setGcgcmsC2Adam(Double gcgcmsC2Adam);
	public Double getGcgcmsComp148Ppm();
	public void setGcgcmsComp148Ppm(Double gcgcmsComp148Ppm);
	public Double getGcgcmsComp105Area();
	public void setGcgcmsComp105Area(Double gcgcmsComp105Area);
	public Date getGcgcmsAcqDate();
	public void setGcgcmsAcqDate(Date gcgcmsAcqDate);
	public Double getGcgcmsComp099Area();
	public void setGcgcmsComp099Area(Double gcgcmsComp099Area);
	public Double getGcgcmsComp092Ppm();
	public void setGcgcmsComp092Ppm(Double gcgcmsComp092Ppm);
	public String getGcgcmsIstd1Name();
	public void setGcgcmsIstd1Name(String gcgcmsIstd1Name);
	public Double getGcgcmsComp134Ppm();
	public void setGcgcmsComp134Ppm(Double gcgcmsComp134Ppm);
	public Double getGcgcmsComp107Ppm();
	public void setGcgcmsComp107Ppm(Double gcgcmsComp107Ppm);
	public Double getGcgcms1356TmAdamPpm();
	public void setGcgcms1356TmAdamPpm(Double gcgcms1356TmAdamPpm);
	public Double getGcgcms1e35DmAdamPpm();
	public void setGcgcms1e35DmAdamPpm(Double gcgcms1e35DmAdamPpm);
	public Double getGcgcmsComp132Area();
	public void setGcgcmsComp132Area(Double gcgcmsComp132Area);
	public Double getGcgcmsC4Triam();
	public void setGcgcmsC4Triam(Double gcgcmsC4Triam);
	public Double getGcgcms1mAdamPpm();
	public void setGcgcms1mAdamPpm(Double gcgcms1mAdamPpm);
	public Double getGcgcmsComp124Area();
	public void setGcgcmsComp124Area(Double gcgcmsComp124Area);
	public Double getGcgcms8mTriamPpm();
	public void setGcgcms8mTriamPpm(Double gcgcms8mTriamPpm);
	public Double getGcgcms1224DmDiam();
	public void setGcgcms1224DmDiam(Double gcgcms1224DmDiam);
	public Double getGcgcmsC5Diam();
	public void setGcgcmsC5Diam(Double gcgcmsC5Diam);
	public Double getGcgcmsSumPrAdam();
	public void setGcgcmsSumPrAdam(Double gcgcmsSumPrAdam);
	public Double getGcgcmsCis134TmAdam();
	public void setGcgcmsCis134TmAdam(Double gcgcmsCis134TmAdam);
	public Double getGcgcmsComp116Ppm();
	public void setGcgcmsComp116Ppm(Double gcgcmsComp116Ppm);
	public Double getGcgcms2EAdamPpm();
	public void setGcgcms2EAdamPpm(Double gcgcms2EAdamPpm);
	public Double getGcgcmsComp125Ppm();
	public void setGcgcmsComp125Ppm(Double gcgcmsComp125Ppm);
	public Double getGcgcmsComp094Area();
	public void setGcgcmsComp094Area(Double gcgcmsComp094Area);
	public Double getGcgcms2EAdam();
	public void setGcgcms2EAdam(Double gcgcms2EAdam);
	public Double getGcgcmsComp140Ppm();
	public void setGcgcmsComp140Ppm(Double gcgcmsComp140Ppm);
	public Double getGcgcmsC1TetramPpm();
	public void setGcgcmsC1TetramPpm(Double gcgcmsC1TetramPpm);
}
