package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcAromatic extends GTOAnalysisData {
	public Double getAgIstdPpm();
	public void setAgIstdPpm(Double agIstdPpm);
	public Double getAg236tmn();
	public void setAg236tmn(Double ag236tmn);
	public Double getAg18dmp();
	public void setAg18dmp(Double ag18dmp);
	public String getAgSvcCode();
	public void setAgSvcCode(String agSvcCode);
	public Double getAg1mp();
	public void setAg1mp(Double ag1mp);
	public Double getAg1mn();
	public void setAg1mn(Double ag1mn);
	public Double getAg1en();
	public void setAg1en(Double ag1en);
	public Double getAg12dmn();
	public void setAg12dmn(Double ag12dmn);
	public Double getAg2en();
	public void setAg2en(Double ag2en);
	public Double getAg36dmp();
	public void setAg36dmp(Double ag36dmp);
	public Double getAg2mp();
	public void setAg2mp(Double ag2mp);
	public Double getAg2mn();
	public void setAg2mn(Double ag2mn);
	public Double getAg29dmp();
	public void setAg29dmp(Double ag29dmp);
	public Double getAg17dmp();
	public void setAg17dmp(Double ag17dmp);
	public Double getAg3mp();
	public void setAg3mp(Double ag3mp);
	public String getAgQcUser();
	public void setAgQcUser(String agQcUser);
	public Double getAg26dmn();
	public void setAg26dmn(Double ag26dmn);
	public Double getAg26dmp();
	public void setAg26dmp(Double ag26dmp);
	public Double getAg14dmn();
	public void setAg14dmn(Double ag14dmn);
	public Double getAgSplPpm();
	public void setAgSplPpm(Double agSplPpm);
	public String getAgRunNumber();
	public void setAgRunNumber(String agRunNumber);
	public Double getAg19dmp();
	public void setAg19dmp(Double ag19dmp);
	public Date getAgQcDate();
	public void setAgQcDate(Date agQcDate);
	public Double getAg1317dmn();
	public void setAg1317dmn(Double ag1317dmn);
	public Double getAg127tmn();
	public void setAg127tmn(Double ag127tmn);
	public Date getAgAcqDate();
	public void setAgAcqDate(Date agAcqDate);
	public String getAgComments();
	public void setAgComments(String agComments);
	public Double getAgPhen();
	public void setAgPhen(Double agPhen);
	public Double getAg137tmn();
	public void setAg137tmn(Double ag137tmn);
	public Double getAg125tmn();
	public void setAg125tmn(Double ag125tmn);
	public String getAgDataType();
	public void setAgDataType(String agDataType);
	public Double getAgIstd();
	public void setAgIstd(Double agIstd);
	public Double getAg15dmn();
	public void setAg15dmn(Double ag15dmn);
	public Double getAg39dmp();
	public void setAg39dmp(Double ag39dmp);
	public Double getAg9mp();
	public void setAg9mp(Double ag9mp);
	public Double getAg27dmp();
	public void setAg27dmp(Double ag27dmp);
	public Double getAg27dmn();
	public void setAg27dmn(Double ag27dmn);
	public Double getAgBp();
	public void setAgBp(Double agBp);
	public String getAgLab();
	public void setAgLab(String agLab);
	public Double getAg146135t();
	public void setAg146135t(Double ag146135t);
	public Date getAgDate();
	public void setAgDate(Date agDate);
	public String getAgQc();
	public void setAgQc(String agQc);
	public String getAgJobId();
	public void setAgJobId(String agJobId);
	public Date getAgLastUpdate();
	public void setAgLastUpdate(Date agLastUpdate);
	public String getAgSampleIdVend();
	public void setAgSampleIdVend(String agSampleIdVend);
	public Double getAg23dmp();
	public void setAg23dmp(Double ag23dmp);
	public Double getAg23dmn();
	public void setAg23dmn(Double ag23dmn);
	public Double getAg167126t();
	public void setAg167126t(Double ag167126t);
	public Double getAg136tmn();
	public void setAg136tmn(Double ag136tmn);
	public Double getAg124tmn();
	public void setAg124tmn(Double ag124tmn);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getAgAuthor();
	public void setAgAuthor(String agAuthor);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getAg16dmn();
	public void setAg16dmn(Double ag16dmn);
	public String getAgIqmCode();
	public void setAgIqmCode(String agIqmCode);
	public String getAgMethod();
	public void setAgMethod(String agMethod);
}
