package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcSaturate extends GTOAnalysisData {
	public String getSatRunNumber();
	public void setSatRunNumber(String satRunNumber);
	public Double getSatPr();
	public void setSatPr(Double satPr);
	public Double getSatPh();
	public void setSatPh(Double satPh);
	public String getSatDataType();
	public void setSatDataType(String satDataType);
	public String getSatQc();
	public void setSatQc(String satQc);
	public String getSatMethod();
	public void setSatMethod(String satMethod);
	public Double getSatPrph();
	public void setSatPrph(Double satPrph);
	public String getSatSvcCode();
	public void setSatSvcCode(String satSvcCode);
	public String getSatSampleIdVend();
	public void setSatSampleIdVend(String satSampleIdVend);
	public Date getSatAcqDate();
	public void setSatAcqDate(Date satAcqDate);
	public Double getSatIc18();
	public void setSatIc18(Double satIc18);
	public Double getSatIc16();
	public void setSatIc16(Double satIc16);
	public Double getSatIc14();
	public void setSatIc14(Double satIc14);
	public Double getSatIc15();
	public void setSatIc15(Double satIc15);
	public Double getSatIc12();
	public void setSatIc12(Double satIc12);
	public Double getSatIc13();
	public void setSatIc13(Double satIc13);
	public String getRequestId();
	public void setRequestId(String satRequest);
	public String getSampleId();
	public void setSampleId(String satSampleId);
	public Date getSatQcDate();
	public void setSatQcDate(Date satQcDate);
	public Double getSatPh18();
	public void setSatPh18(Double satPh18);
	public String getSatQcUser();
	public void setSatQcUser(String satQcUser);
	public Double getSatNc10();
	public void setSatNc10(Double satNc10);
	public Double getSatNc11();
	public void setSatNc11(Double satNc11);
	public Double getSatNc12();
	public void setSatNc12(Double satNc12);
	public Double getSatNc17();
	public void setSatNc17(Double satNc17);
	public Double getSatNc18();
	public void setSatNc18(Double satNc18);
	public Double getSatNc19();
	public void setSatNc19(Double satNc19);
	public Double getSatNc13();
	public void setSatNc13(Double satNc13);
	public Double getSatNc14();
	public void setSatNc14(Double satNc14);
	public Double getSatNc15();
	public void setSatNc15(Double satNc15);
	public Double getSatNc16();
	public void setSatNc16(Double satNc16);
	public Double getSatNc31();
	public void setSatNc31(Double satNc31);
	public Double getSatNc32();
	public void setSatNc32(Double satNc32);
	public Double getSatNc33();
	public void setSatNc33(Double satNc33);
	public Double getSatNc34();
	public void setSatNc34(Double satNc34);
	public Double getSatNc30();
	public void setSatNc30(Double satNc30);
	public Double getSatNc39();
	public void setSatNc39(Double satNc39);
	public Double getSatNc35();
	public void setSatNc35(Double satNc35);
	public Double getSatNc36();
	public void setSatNc36(Double satNc36);
	public Double getSatNc37();
	public void setSatNc37(Double satNc37);
	public Double getSatNc38();
	public void setSatNc38(Double satNc38);
	public Double getSatNc20();
	public void setSatNc20(Double satNc20);
	public Double getSatNc21();
	public void setSatNc21(Double satNc21);
	public Double getSatNc22();
	public void setSatNc22(Double satNc22);
	public Double getSatNc23();
	public void setSatNc23(Double satNc23);
	public String getSatComments();
	public void setSatComments(String satComments);
	public Double getSatNc28();
	public void setSatNc28(Double satNc28);
	public Double getSatNc29();
	public void setSatNc29(Double satNc29);
	public Double getSatNc24();
	public void setSatNc24(Double satNc24);
	public Double getSatNc25();
	public void setSatNc25(Double satNc25);
	public Double getSatNc26();
	public void setSatNc26(Double satNc26);
	public Double getSatNc27();
	public void setSatNc27(Double satNc27);
	public Double getSatNc42();
	public void setSatNc42(Double satNc42);
	public Double getSatNc43();
	public void setSatNc43(Double satNc43);
	public Double getSatNc44();
	public void setSatNc44(Double satNc44);
	public Double getSatNc45();
	public void setSatNc45(Double satNc45);
	public Double getSatNc40();
	public void setSatNc40(Double satNc40);
	public Double getSatNc41();
	public void setSatNc41(Double satNc41);
	public String getSatLab();
	public void setSatLab(String satLab);
	public String getSatAuthor();
	public void setSatAuthor(String satAuthor);
	public String getSatIqmCode();
	public void setSatIqmCode(String satIqmCode);
	public String getSatJobId();
	public void setSatJobId(String satJobId);
	public Date getSatLastUpdate();
	public void setSatLastUpdate(Date satLastUpdate);
	public Double getSatPr17();
	public void setSatPr17(Double satPr17);
	public Date getSatDate();
	public void setSatDate(Date satDate);
	public Double getX5atCpi5();
	public void setX5atCpi5(Double x5atCpi5);
	public Double getX5atCpiOther();
	public void setX5atCpiOther(Double x5atCpiOther);
	public Double getSatIc11();
	public void setSatIc11(Double satIc11);
	public Double getSatCpi1();
	public void setSatCpi1(Double satCpi1);
	public Double getSatCpi2();
	public void setSatCpi2(Double satCpi2);
	public String getSatPrep();
	public void setSatPrep(String satPrep);
	public Double getSatCpi3();
	public void setSatCpi3(Double satCpi3);
	public Double getSatCpi4();
	public void setSatCpi4(Double satCpi4);
}
