package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcGc extends GTOAnalysisData {
	public Integer getGcgc1234tmBenz();
	public void setGcgc1234tmBenz(Integer gcgc1234tmBenz);
	public Integer getGcgcSecc4Benz();
	public void setGcgcSecc4Benz(Integer gcgcSecc4Benz);
	public String getGcgcSampleIdVend();
	public void setGcgcSampleIdVend(String gcgcSampleIdVend);
	public Integer getGcgcTol();
	public void setGcgcTol(Integer gcgcTol);
	public String getGcgcRunNumber();
	public void setGcgcRunNumber(String gcgcRunNumber);
	public Integer getGcgc1m2ipBenz();
	public void setGcgc1m2ipBenz(Integer gcgc1m2ipBenz);
	public Integer getGcgcMPXyl();
	public void setGcgcMPXyl(Integer gcgcMPXyl);
	public Integer getGcgcStdPpm();
	public void setGcgcStdPpm(Integer gcgcStdPpm);
	public String getGcgcIqmCode();
	public void setGcgcIqmCode(String gcgcIqmCode);
	public String getGcgcMethod();
	public void setGcgcMethod(String gcgcMethod);
	public Integer getGcgcStdCnts2();
	public void setGcgcStdCnts2(Integer gcgcStdCnts2);
	public Integer getGcgc2mNaph();
	public void setGcgc2mNaph(Integer gcgc2mNaph);
	public Integer getGcgcIpBenz();
	public void setGcgcIpBenz(Integer gcgcIpBenz);
	public Integer getGcgc56Ant();
	public void setGcgc56Ant(Integer gcgc56Ant);
	public Integer getGcgc1eNaph();
	public void setGcgc1eNaph(Integer gcgc1eNaph);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Integer getGcgc1m31m4IpBenz();
	public void setGcgc1m31m4IpBenz(Integer gcgc1m31m4IpBenz);
	public Integer getGcgc2mBp();
	public void setGcgc2mBp(Integer gcgc2mBp);
	public Integer getGcgcOXyl();
	public void setGcgcOXyl(Integer gcgcOXyl);
	public Integer getGcgcC3Naph6();
	public void setGcgcC3Naph6(Integer gcgcC3Naph6);
	public Integer getGcgcC3Naph7();
	public void setGcgcC3Naph7(Integer gcgcC3Naph7);
	public String getGcgcAuthor();
	public void setGcgcAuthor(String gcgcAuthor);
	public Integer getGcgcStdPpm2();
	public void setGcgcStdPpm2(Integer gcgcStdPpm2);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Integer getGcgc78Ant();
	public void setGcgc78Ant(Integer gcgc78Ant);
	public Integer getGcgc2eNaph();
	public void setGcgc2eNaph(Integer gcgc2eNaph);
	public Integer getGcgcNpBenz();
	public void setGcgcNpBenz(Integer gcgcNpBenz);
	public Date getGcgcQcDate();
	public void setGcgcQcDate(Date gcgcQcDate);
	public Integer getGcgcMch();
	public void setGcgcMch(Integer gcgcMch);
	public Integer getGcgcBp();
	public void setGcgcBp(Integer gcgcBp);
	public Double getGcgcNc36();
	public void setGcgcNc36(Double gcgcNc36);
	public Double getGcgcNc35();
	public void setGcgcNc35(Double gcgcNc35);
	public Double getGcgcNc34();
	public void setGcgcNc34(Double gcgcNc34);
	public Double getGcgcNc33();
	public void setGcgcNc33(Double gcgcNc33);
	public Double getGcgcNc32();
	public void setGcgcNc32(Double gcgcNc32);
	public Double getGcgcNc31();
	public void setGcgcNc31(Double gcgcNc31);
	public Double getGcgcNc30();
	public void setGcgcNc30(Double gcgcNc30);
	public Double getGcgcNc29();
	public void setGcgcNc29(Double gcgcNc29);
	public Double getGcgcNc28();
	public void setGcgcNc28(Double gcgcNc28);
	public Double getGcgcNc27();
	public void setGcgcNc27(Double gcgcNc27);
	public Double getGcgcNc26();
	public void setGcgcNc26(Double gcgcNc26);
	public Double getGcgcNc25();
	public void setGcgcNc25(Double gcgcNc25);
	public Double getGcgcNc24();
	public void setGcgcNc24(Double gcgcNc24);
	public Double getGcgcNc23();
	public void setGcgcNc23(Double gcgcNc23);
	public Double getGcgcNc22();
	public void setGcgcNc22(Double gcgcNc22);
	public Double getGcgcNc21();
	public void setGcgcNc21(Double gcgcNc21);
	public Double getGcgcNc20();
	public void setGcgcNc20(Double gcgcNc20);
	public Double getGcgcNc19();
	public void setGcgcNc19(Double gcgcNc19);
	public Double getGcgcNc18();
	public void setGcgcNc18(Double gcgcNc18);
	public Double getGcgcNc17();
	public void setGcgcNc17(Double gcgcNc17);
	public Double getGcgcNc16();
	public void setGcgcNc16(Double gcgcNc16);
	public Double getGcgcNc15();
	public void setGcgcNc15(Double gcgcNc15);
	public Double getGcgcNc14();
	public void setGcgcNc14(Double gcgcNc14);
	public Double getGcgcNc13();
	public void setGcgcNc13(Double gcgcNc13);
	public Double getGcgcNc12();
	public void setGcgcNc12(Double gcgcNc12);
	public Double getGcgcNc11();
	public void setGcgcNc11(Double gcgcNc11);
	public Double getGcgcNc10();
	public void setGcgcNc10(Double gcgcNc10);
	public Integer getGcgcNaph();
	public void setGcgcNaph(Integer gcgcNaph);
	public Date getGcgcLastUpdate();
	public void setGcgcLastUpdate(Date gcgcLastUpdate);
	public Integer getGcgcABenz();
	public void setGcgcABenz(Integer gcgcABenz);
	public Integer getGcgcPhen();
	public void setGcgcPhen(Integer gcgcPhen);
	public String getGcgcLab();
	public void setGcgcLab(String gcgcLab);
	public Double getGcgcNc40();
	public void setGcgcNc40(Double gcgcNc40);
	public Double getGcgcNc39();
	public void setGcgcNc39(Double gcgcNc39);
	public Double getGcgcNc38();
	public void setGcgcNc38(Double gcgcNc38);
	public Double getGcgcNc37();
	public void setGcgcNc37(Double gcgcNc37);
	public String getGcgcQc();
	public void setGcgcQc(String gcgcQc);
	public String getGcgcComment();
	public void setGcgcComment(String gcgcComment);
	public String getGcgcJobId();
	public void setGcgcJobId(String gcgcJobId);
	public String getGcgcQcUser();
	public void setGcgcQcUser(String gcgcQcUser);
	public String getGcgcSvcCode();
	public void setGcgcSvcCode(String gcgcSvcCode);
	public Double getGcgcNc5();
	public void setGcgcNc5(Double gcgcNc5);
	public Double getGcgcNc4();
	public void setGcgcNc4(Double gcgcNc4);
	public Double getGcgcNc7();
	public void setGcgcNc7(Double gcgcNc7);
	public Double getGcgcNc6();
	public void setGcgcNc6(Double gcgcNc6);
	public Double getGcgcNc9();
	public void setGcgcNc9(Double gcgcNc9);
	public Double getGcgcNc8();
	public void setGcgcNc8(Double gcgcNc8);
	public Double getGcgcNc1();
	public void setGcgcNc1(Double gcgcNc1);
	public Double getGcgcNc3();
	public void setGcgcNc3(Double gcgcNc3);
	public Double getGcgcNc2();
	public void setGcgcNc2(Double gcgcNc2);
	public Integer getGcgc135tmBenz();
	public void setGcgc135tmBenz(Integer gcgc135tmBenz);
	public Integer getGcgc13dm2eBenz();
	public void setGcgc13dm2eBenz(Integer gcgc13dm2eBenz);
	public Integer getGcgc124TmBenz();
	public void setGcgc124TmBenz(Integer gcgc124TmBenz);
	public Integer getGcgcBBenz();
	public void setGcgcBBenz(Integer gcgcBBenz);
	public Integer getGcgcG();
	public void setGcgcG(Integer gcgcG);
	public Integer getGcgcB();
	public void setGcgcB(Integer gcgcB);
	public Integer getGcgcA();
	public void setGcgcA(Integer gcgcA);
	public Integer getGcgcD();
	public void setGcgcD(Integer gcgcD);
	public Integer getGcgcF();
	public void setGcgcF(Integer gcgcF);
	public Double getGcgcSampAmt();
	public void setGcgcSampAmt(Double gcgcSampAmt);
	public Integer getGcgc123tmb();
	public void setGcgc123tmb(Integer gcgc123tmb);
	public Integer getGcgcStdCnts();
	public void setGcgcStdCnts(Integer gcgcStdCnts);
	public Integer getGcgcXBenz();
	public void setGcgcXBenz(Integer gcgcXBenz);
	public Date getGcgcAcqDate();
	public void setGcgcAcqDate(Date gcgcAcqDate);
	public Integer getGcgcIc4Benz();
	public void setGcgcIc4Benz(Integer gcgcIc4Benz);
	public Integer getGcgc1m2npBenz();
	public void setGcgc1m2npBenz(Integer gcgc1m2npBenz);
	public Integer getGcgc1mNaph();
	public void setGcgc1mNaph(Integer gcgc1mNaph);
	public Integer getGcgcEBenz();
	public void setGcgcEBenz(Integer gcgcEBenz);
	public Date getGcgcDate();
	public void setGcgcDate(Date gcgcDate);
	public Integer getGcgcDmNaph2();
	public void setGcgcDmNaph2(Integer gcgcDmNaph2);
	public Integer getGcgcDmNaph1();
	public void setGcgcDmNaph1(Integer gcgcDmNaph1);
	public Integer getGcgcDmNaph3();
	public void setGcgcDmNaph3(Integer gcgcDmNaph3);
	public Integer getGcgc1m2eBenz();
	public void setGcgc1m2eBenz(Integer gcgc1m2eBenz);
	public Integer getGcgcAnt();
	public void setGcgcAnt(Integer gcgcAnt);
	public Integer getGcgc1m3e4eBenz();
	public void setGcgc1m3e4eBenz(Integer gcgc1m3e4eBenz);
}
