package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcXmdgcBenz extends GTOAnalysisData {
	public String getXbQcUser();
	public void setXbQcUser(String xbQcUser);
	public String getXbRunNumber();
	public void setXbRunNumber(String xbRunNumber);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getXbLab();
	public void setXbLab(String xbLab);
	public Double getXbB();
	public void setXbB(Double xbB);
	public Double getXbD();
	public void setXbD(Double xbD);
	public Double getXbC();
	public void setXbC(Double xbC);
	public Double getXbN();
	public void setXbN(Double xbN);
	public Double getXbM();
	public void setXbM(Double xbM);
	public Double getXbP();
	public void setXbP(Double xbP);
	public Double getXbO();
	public void setXbO(Double xbO);
	public Double getXbR();
	public void setXbR(Double xbR);
	public Double getXbT();
	public void setXbT(Double xbT);
	public Double getXbS();
	public void setXbS(Double xbS);
	public Double getXbF();
	public void setXbF(Double xbF);
	public Double getXbE();
	public void setXbE(Double xbE);
	public Double getXbH();
	public void setXbH(Double xbH);
	public Double getXbG();
	public void setXbG(Double xbG);
	public Double getXbJ();
	public void setXbJ(Double xbJ);
	public Double getXbI();
	public void setXbI(Double xbI);
	public Double getXbL();
	public void setXbL(Double xbL);
	public Double getXbK();
	public void setXbK(Double xbK);
	public Double getXbU();
	public void setXbU(Double xbU);
	public Double getXbW();
	public void setXbW(Double xbW);
	public String getXbQc();
	public void setXbQc(String xbQc);
	public Date getXbQcDate();
	public void setXbQcDate(Date xbQcDate);
	public String getXbSvcCode();
	public void setXbSvcCode(String xbSvcCode);
	public String getXbIqmCode();
	public void setXbIqmCode(String xbIqmCode);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Date getXbLastUpdate();
	public void setXbLastUpdate(Date xbLastUpdate);
	public String getXbMethod();
	public void setXbMethod(String xbMethod);
	public String getXbAuthor();
	public void setXbAuthor(String xbAuthor);
	public String getXbJobId();
	public void setXbJobId(String xbJobId);
	public String getXbComments();
	public void setXbComments(String xbComments);
	public Date getXbAcqDate();
	public void setXbAcqDate(Date xbAcqDate);
	public String getXbSampleIdVend();
	public void setXbSampleIdVend(String xbSampleIdVend);
	public Date getXbDate();
	public void setXbDate(Date xbDate);
	public String getXbDataType();
	public void setXbDataType(String xbDataType);
}
