package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcHtgc extends GTOAnalysisData  {
	public Double getHtgcWax();
	public void setHtgcWax(Double htgcWax);
	public String getHtgcSampleIdVend();
	public void setHtgcSampleIdVend(String htgcSampleIdVend);
	public Double getHtgcPrph();
	public void setHtgcPrph(Double htgcPrph);
	public Double getHtgcPristane();
	public void setHtgcPristane(Double htgcPristane);
	public String getHtgcJobId();
	public void setHtgcJobId(String htgcJobId);
	public Double getHtgcPr17();
	public void setHtgcPr17(Double htgcPr17);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getHtgcLab();
	public void setHtgcLab(String htgcLab);
	public Double getHtgcPh18();
	public void setHtgcPh18(Double htgcPh18);
	public String getHtgcAuthor();
	public void setHtgcAuthor(String htgcAuthor);
	public String getHtgcQc();
	public void setHtgcQc(String htgcQc);
	public String getHtgcDataType();
	public void setHtgcDataType(String htgcDataType);
	public Double getHtgcIc18();
	public void setHtgcIc18(Double htgcIc18);
	public Double getHtgcIc15();
	public void setHtgcIc15(Double htgcIc15);
	public Double getHtgcIc14();
	public void setHtgcIc14(Double htgcIc14);
	public Double getHtgcIc16();
	public void setHtgcIc16(Double htgcIc16);
	public Double getHtgcIc13();
	public void setHtgcIc13(Double htgcIc13);
	public Double getHtgcIc12();
	public void setHtgcIc12(Double htgcIc12);
	public Double getHtgcNc100();
	public void setHtgcNc100(Double htgcNc100);
	public Double getHtgcIpi();
	public void setHtgcIpi(Double htgcIpi);
	public Date getHtgcLastUpdate();
	public void setHtgcLastUpdate(Date htgcLastUpdate);
	public Date getHtgcQcDate();
	public void setHtgcQcDate(Date htgcQcDate);
	public String getHtgcRunNumber();
	public void setHtgcRunNumber(String htgcRunNumber);
	public Date getHtgcDate();
	public void setHtgcDate(Date htgcDate);
	public String getHtgcQcUser();
	public void setHtgcQcUser(String htgcQcUser);
	public String getHtgcComments();
	public void setHtgcComments(String htgcComments);
	public Double getHtgcPhytane();
	public void setHtgcPhytane(Double htgcPhytane);
	public Double getHtgcAciCor();
	public void setHtgcAciCor(Double htgcAciCor);
	public Date getHtgcAcqDate();
	public void setHtgcAcqDate(Date htgcAcqDate);
	public Double getHtgcNc26();
	public void setHtgcNc26(Double htgcNc26);
	public Double getHtgcNc27();
	public void setHtgcNc27(Double htgcNc27);
	public Double getHtgcNc28();
	public void setHtgcNc28(Double htgcNc28);
	public Double getHtgcNc29();
	public void setHtgcNc29(Double htgcNc29);
	public Double getHtgcNc20();
	public void setHtgcNc20(Double htgcNc20);
	public Double getHtgcNc21();
	public void setHtgcNc21(Double htgcNc21);
	public Double getHtgcNc22();
	public void setHtgcNc22(Double htgcNc22);
	public Double getHtgcNc23();
	public void setHtgcNc23(Double htgcNc23);
	public Double getHtgcNc24();
	public void setHtgcNc24(Double htgcNc24);
	public Double getHtgcNc25();
	public void setHtgcNc25(Double htgcNc25);
	public Double getHtgcNc15();
	public void setHtgcNc15(Double htgcNc15);
	public Double getHtgcNc16();
	public void setHtgcNc16(Double htgcNc16);
	public Double getHtgcNc17();
	public void setHtgcNc17(Double htgcNc17);
	public Double getHtgcNc18();
	public void setHtgcNc18(Double htgcNc18);
	public Double getHtgcNc19();
	public void setHtgcNc19(Double htgcNc19);
	public Double getHtgcNc10();
	public void setHtgcNc10(Double htgcNc10);
	public Double getHtgcNc11();
	public void setHtgcNc11(Double htgcNc11);
	public Double getHtgcNc12();
	public void setHtgcNc12(Double htgcNc12);
	public Double getHtgcNc13();
	public void setHtgcNc13(Double htgcNc13);
	public Double getHtgcNc14();
	public void setHtgcNc14(Double htgcNc14);
	public Double getHtgcNc48();
	public void setHtgcNc48(Double htgcNc48);
	public Double getHtgcNc49();
	public void setHtgcNc49(Double htgcNc49);
	public Double getHtgcNc40();
	public void setHtgcNc40(Double htgcNc40);
	public Double getHtgcNc41();
	public void setHtgcNc41(Double htgcNc41);
	public Double getHtgcNc42();
	public void setHtgcNc42(Double htgcNc42);
	public Double getHtgcNc43();
	public void setHtgcNc43(Double htgcNc43);
	public Double getHtgcNc44();
	public void setHtgcNc44(Double htgcNc44);
	public Double getHtgcNc45();
	public void setHtgcNc45(Double htgcNc45);
	public Double getHtgcNc46();
	public void setHtgcNc46(Double htgcNc46);
	public Double getHtgcNc47();
	public void setHtgcNc47(Double htgcNc47);
	public Double getHtgcNc37();
	public void setHtgcNc37(Double htgcNc37);
	public Double getHtgcNc38();
	public void setHtgcNc38(Double htgcNc38);
	public Double getHtgcNc39();
	public void setHtgcNc39(Double htgcNc39);
	public Double getHtgcNc30();
	public void setHtgcNc30(Double htgcNc30);
	public Double getHtgcNc31();
	public void setHtgcNc31(Double htgcNc31);
	public Double getHtgcNc32();
	public void setHtgcNc32(Double htgcNc32);
	public Double getHtgcNc33();
	public void setHtgcNc33(Double htgcNc33);
	public Double getHtgcNc34();
	public void setHtgcNc34(Double htgcNc34);
	public Double getHtgcNc35();
	public void setHtgcNc35(Double htgcNc35);
	public Double getHtgcNc36();
	public void setHtgcNc36(Double htgcNc36);
	public String getHtgcMethod();
	public void setHtgcMethod(String htgcMethod);
	public Double getHtgcNc90();
	public void setHtgcNc90(Double htgcNc90);
	public Double getHtgcNc91();
	public void setHtgcNc91(Double htgcNc91);
	public Double getHtgcNc92();
	public void setHtgcNc92(Double htgcNc92);
	public Double getHtgcNc93();
	public void setHtgcNc93(Double htgcNc93);
	public Double getHtgcNc94();
	public void setHtgcNc94(Double htgcNc94);
	public Double getHtgcNc95();
	public void setHtgcNc95(Double htgcNc95);
	public Double getHtgcNc96();
	public void setHtgcNc96(Double htgcNc96);
	public Double getHtgcNc97();
	public void setHtgcNc97(Double htgcNc97);
	public Double getHtgcNc98();
	public void setHtgcNc98(Double htgcNc98);
	public Double getHtgcNc99();
	public void setHtgcNc99(Double htgcNc99);
	public Double getHtgcNc60();
	public void setHtgcNc60(Double htgcNc60);
	public Double getHtgcNc61();
	public void setHtgcNc61(Double htgcNc61);
	public Double getHtgcNc62();
	public void setHtgcNc62(Double htgcNc62);
	public Double getHtgcNc63();
	public void setHtgcNc63(Double htgcNc63);
	public Double getHtgcNc64();
	public void setHtgcNc64(Double htgcNc64);
	public Double getHtgcNc65();
	public void setHtgcNc65(Double htgcNc65);
	public Double getHtgcNc66();
	public void setHtgcNc66(Double htgcNc66);
	public Double getHtgcNc67();
	public void setHtgcNc67(Double htgcNc67);
	public Double getHtgcNc68();
	public void setHtgcNc68(Double htgcNc68);
	public Double getHtgcNc69();
	public void setHtgcNc69(Double htgcNc69);
	public Double getHtgcNc59();
	public void setHtgcNc59(Double htgcNc59);
	public Double getHtgcNc50();
	public void setHtgcNc50(Double htgcNc50);
	public Double getHtgcNc51();
	public void setHtgcNc51(Double htgcNc51);
	public Double getHtgcNc52();
	public void setHtgcNc52(Double htgcNc52);
	public Double getHtgcNc53();
	public void setHtgcNc53(Double htgcNc53);
	public Double getHtgcNc54();
	public void setHtgcNc54(Double htgcNc54);
	public Double getHtgcNc55();
	public void setHtgcNc55(Double htgcNc55);
	public Double getHtgcNc56();
	public void setHtgcNc56(Double htgcNc56);
	public Double getHtgcNc57();
	public void setHtgcNc57(Double htgcNc57);
	public Double getHtgcNc58();
	public void setHtgcNc58(Double htgcNc58);
	public Double getHtgcNc80();
	public void setHtgcNc80(Double htgcNc80);
	public Double getHtgcNc81();
	public void setHtgcNc81(Double htgcNc81);
	public Double getHtgcNc82();
	public void setHtgcNc82(Double htgcNc82);
	public Double getHtgcNc83();
	public void setHtgcNc83(Double htgcNc83);
	public Double getHtgcNc84();
	public void setHtgcNc84(Double htgcNc84);
	public Double getHtgcNc85();
	public void setHtgcNc85(Double htgcNc85);
	public Double getHtgcNc86();
	public void setHtgcNc86(Double htgcNc86);
	public Double getHtgcNc87();
	public void setHtgcNc87(Double htgcNc87);
	public Double getHtgcNc88();
	public void setHtgcNc88(Double htgcNc88);
	public Double getHtgcNc89();
	public void setHtgcNc89(Double htgcNc89);
	public Double getHtgcNc70();
	public void setHtgcNc70(Double htgcNc70);
	public Double getHtgcNc71();
	public void setHtgcNc71(Double htgcNc71);
	public Double getHtgcNc72();
	public void setHtgcNc72(Double htgcNc72);
	public Double getHtgcNc73();
	public void setHtgcNc73(Double htgcNc73);
	public Double getHtgcNc74();
	public void setHtgcNc74(Double htgcNc74);
	public Double getHtgcNc75();
	public void setHtgcNc75(Double htgcNc75);
	public Double getHtgcNc76();
	public void setHtgcNc76(Double htgcNc76);
	public Double getHtgcNc77();
	public void setHtgcNc77(Double htgcNc77);
	public Double getHtgcNc78();
	public void setHtgcNc78(Double htgcNc78);
	public Double getHtgcNc79();
	public void setHtgcNc79(Double htgcNc79);
	public Double getHtgcCpi();
	public void setHtgcCpi(Double htgcCpi);
	public String getHtgcIqmCode();
	public void setHtgcIqmCode(String htgcIqmCode);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getHtgcAci();
	public void setHtgcAci(Double htgcAci);
	public String getHtgcSvcCode();
	public void setHtgcSvcCode(String htgcSvcCode);
	public String getHtgcIqmFlag();
	public void setHtgcIqmFlag(String htgcIqmFlag);
	public Integer getHtgcMethodId();
	public void setHtgcMethodId(Integer htgcMethodId);
	public String getHtgcRequestIdVend();
	public void setHtgcRequestIdVend(String htgcRequestIdVend);
	public Integer getHtgcDataTypeId();
	public void setHtgcDataTypeId(Integer htgcDataTypeId);
	public Integer getHtgcUnitsId();
	public void setHtgcUnitsId(Integer htgcUnitsId);
	public String getHtgcDataUnits();
	public void setHtgcDataUnits(String htgcDataUnits);
}
