package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcGasoline extends GTOAnalysisData {
	public String getG7AcqDate();
	public void setG7AcqDate(String g7AcqDate);
	public String getG7SvcCode();
	public void setG7SvcCode(String g7SvcCode);
	public Double getG7Ethylcyclohexane();
	public void setG7Ethylcyclohexane(Double g7Ethylcyclohexane);
	public String getG7RunNumber();
	public void setG7RunNumber(String g7RunNumber);
	public Double getG7WeightPercIs();
	public void setG7WeightPercIs(Double g7WeightPercIs);
	public String getG7QcUser();
	public void setG7QcUser(String g7QcUser);
	public Double getX24dmh();
	public void setX24dmh(Double x24dmh);
	public Double getG74mc7();
	public void setG74mc7(Double g74mc7);
	public Double getX24dmp();
	public void setX24dmp(Double x24dmp);
	public Double getG71tr2cis4Tmh();
	public void setG71tr2cis4Tmh(Double g71tr2cis4Tmh);
	public Double getX223tmp();
	public void setX223tmp(Double x223tmp);
	public Double getX223tmb();
	public void setX223tmb(Double x223tmb);
	public Double getG7123tmcp();
	public void setG7123tmcp(Double g7123tmcp);
	public Double getX22dmpr();
	public void setX22dmpr(Double x22dmpr);
	public Double getRatio3334();
	public void setRatio3334(Double ratio3334);
	public Double getPeak3334();
	public void setPeak3334(Double peak3334);
	public Double getG7112tmcp();
	public void setG7112tmcp(Double g7112tmcp);
	public Double getX113tmcp();
	public void setX113tmcp(Double x113tmcp);
	public String getG7JobId();
	public void setG7JobId(String g7JobId);
	public Double getG7Perc();
	public void setG7Perc(Double g7Perc);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getX33dmp();
	public void setX33dmp(Double x33dmp);
	public Double getG7113tmcp22dmh();
	public void setG7113tmcp22dmh(Double g7113tmcp22dmh);
	public Double getTol();
	public void setTol(Double tol);
	public String getG7IqmCode();
	public void setG7IqmCode(String g7IqmCode);
	public Double getX2mh();
	public void setX2mh(Double x2mh);
	public Double getX2mp();
	public void setX2mp(Double x2mp);
	public Double getG73mc7();
	public void setG73mc7(Double g73mc7);
	public Double getX25dmh();
	public void setX25dmh(Double x25dmh);
	public String getG7Method();
	public void setG7Method(String g7Method);
	public Double getG7C8();
	public void setG7C8(Double g7C8);
	public Double getG71c2dmcpMch();
	public void setG71c2dmcpMch(Double g71c2dmcpMch);
	public Double getX224tmp();
	public void setX224tmp(Double x224tmp);
	public Date getG7Date();
	public void setG7Date(Date g7Date);
	public Double getMcp22dmp();
	public void setMcp22dmp(Double mcp22dmp);
	public Double getX1t2dmcp3ep();
	public void setX1t2dmcp3ep(Double x1t2dmcp3ep);
	public Double getX1c2dmcp();
	public void setX1c2dmcp(Double x1c2dmcp);
	public Double getG733dmh();
	public void setG733dmh(Double g733dmh);
	public Double getX1t2dmcp();
	public void setX1t2dmcp(Double x1t2dmcp);
	public String getG7Comments();
	public void setG7Comments(String g7Comments);
	public String getG7Qc();
	public void setG7Qc(String g7Qc);
	public Double getX3ep();
	public void setX3ep(Double x3ep);
	public Double getX22dmb();
	public void setX22dmb(Double x22dmb);
	public Double getX22dmh();
	public void setX22dmh(Double x22dmh);
	public Double getC1();
	public void setC1(Double c1);
	public Double getC2();
	public void setC2(Double c2);
	public Double getC3();
	public void setC3(Double c3);
	public Double getC4();
	public void setC4(Double c4);
	public Double getC5();
	public void setC5(Double c5);
	public Double getC6();
	public void setC6(Double c6);
	public Double getC7();
	public void setC7(Double c7);
	public Double getCh();
	public void setCh(Double ch);
	public Double getCp();
	public void setCp(Double cp);
	public Double getX22dmp();
	public void setX22dmp(Double x22dmp);
	public String getG7SampleIdVend();
	public void setG7SampleIdVend(String g7SampleIdVend);
	public Double getX3mh();
	public void setX3mh(Double x3mh);
	public Double getX3mp();
	public void setX3mp(Double x3mp);
	public String getG7Lab();
	public void setG7Lab(String g7Lab);
	public Double getMch();
	public void setMch(Double mch);
	public Double getMcp();
	public void setMcp(Double mcp);
	public Double getG7T14dmch();
	public void setG7T14dmch(Double g7T14dmch);
	public String getG7Author();
	public void setG7Author(String g7Author);
	public Double getG7234tmp();
	public void setG7234tmp(Double g7234tmp);
	public Double getIc5();
	public void setIc5(Double ic5);
	public Double getIc4();
	public void setIc4(Double ic4);
	public Double getPeak3132();
	public void setPeak3132(Double peak3132);
	public Double getX1t2c4tmcp();
	public void setX1t2c4tmcp(Double x1t2c4tmcp);
	public String getG7DataType();
	public void setG7DataType(String g7DataType);
	public Double getG72mc7();
	public void setG72mc7(Double g72mc7);
	public Double getRatio3132();
	public void setRatio3132(Double ratio3132);
	public Double getEcp();
	public void setEcp(Double ecp);
	public Double getG7SplConc();
	public void setG7SplConc(Double g7SplConc);
	public Double getX23dmb();
	public void setX23dmb(Double x23dmb);
	public Double getG7Istd();
	public void setG7Istd(Double g7Istd);
	public Double getMch1c2dmcp();
	public void setMch1c2dmcp(Double mch1c2dmcp);
	public Double getBenz();
	public void setBenz(Double benz);
	public Date getG7QcDate();
	public void setG7QcDate(Date g7QcDate);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getX23dmp();
	public void setX23dmp(Double x23dmp);
	public Date getG7LastUpdate();
	public void setG7LastUpdate(Date g7LastUpdate);
	public Double getX11dmcp();
	public void setX11dmcp(Double x11dmcp);
	public Double getG723dmh();
	public void setG723dmh(Double g723dmh);
	public Double getX1c3dmcp();
	public void setX1c3dmcp(Double x1c3dmcp);
	public Double getX1t3dmcp();
	public void setX1t3dmcp(Double x1t3dmcp);
	public Double getG7IstdConc();
	public void setG7IstdConc(Double g7IstdConc);
	public Double getPxyl();
	public void setPxyl(Double pxyl);
	public Double getMxylPxyl();
	public void setMxylPxyl(Double mxylPxyl);
	public Double getMxyl();
	public void setMxyl(Double mxyl);
	public String getG7ProcDate();
	public void setG7ProcDate(String g7ProcDate);
}
