package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcHeadspace extends GTOAnalysisData {
	public Integer getHsC3();
	public void setHsC3(Integer hsC3);
	public Integer getHsC2();
	public void setHsC2(Integer hsC2);
	public Integer getHsC1();
	public void setHsC1(Integer hsC1);
	public Integer getHsCo();
	public void setHsCo(Integer hsCo);
	public Integer getHsH2();
	public void setHsH2(Integer hsH2);
	public Integer getHsN2();
	public void setHsN2(Integer hsN2);
	public Date getHsQcDate();
	public void setHsQcDate(Date hsQcDate);
	public Integer getHsO2();
	public void setHsO2(Integer hsO2);
	public Integer getHsAirSpMl();
	public void setHsAirSpMl(Integer hsAirSpMl);
	public String getHsQc();
	public void setHsQc(String hsQc);
	public String getHsSampleIdVend();
	public void setHsSampleIdVend(String hsSampleIdVend);
	public String getHsQcUser();
	public void setHsQcUser(String hsQcUser);
	public Integer getHsAr();
	public void setHsAr(Integer hsAr);
	public String getHsIqmCode();
	public void setHsIqmCode(String hsIqmCode);
	public String getHsJobId();
	public void setHsJobId(String hsJobId);
	public String getHsMethod();
	public void setHsMethod(String hsMethod);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Date getHsAcqDate();
	public void setHsAcqDate(Date hsAcqDate);
	public Integer getHsAirH2oMl();
	public void setHsAirH2oMl(Integer hsAirH2oMl);
	public Integer getHsNc4();
	public void setHsNc4(Integer hsNc4);
	public Integer getHsNc5();
	public void setHsNc5(Integer hsNc5);
	public String getHsComment();
	public void setHsComment(String hsComment);
	public Integer getHsVolCtgsMl();
	public void setHsVolCtgsMl(Integer hsVolCtgsMl);
	public String getHsLab();
	public void setHsLab(String hsLab);
	public Integer getHsC5C7();
	public void setHsC5C7(Integer hsC5C7);
	public String getHsAuthor();
	public void setHsAuthor(String hsAuthor);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Integer getHsC6pls();
	public void setHsC6pls(Integer hsC6pls);
	public Integer getHsArOs();
	public void setHsArOs(Integer hsArOs);
	public Integer getHsIc4();
	public void setHsIc4(Integer hsIc4);
	public Integer getHsIc5();
	public void setHsIc5(Integer hsIc5);
	public String getHsSvcCode();
	public void setHsSvcCode(String hsSvcCode);
	public String getHsDataType();
	public void setHsDataType(String hsDataType);
	public Integer getHsC5pls();
	public void setHsC5pls(Integer hsC5pls);
	public Date getHsDate();
	public void setHsDate(Date hsDate);
	public String getHsRunNumber();
	public void setHsRunNumber(String hsRunNumber);
	public Integer getHsUc3();
	public void setHsUc3(Integer hsUc3);
	public Integer getHsUc2();
	public void setHsUc2(Integer hsUc2);
	public Integer getHsCo2();
	public void setHsCo2(Integer hsCo2);
}
