package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcTegc extends GTOAnalysisData {
	public String getTegcMethod();
	public void setTegcMethod(String tegcMethod);
	public Double getTegcC44();
	public void setTegcC44(Double tegcC44);
	public Double getTegcC43();
	public void setTegcC43(Double tegcC43);
	public Double getTegcC40();
	public void setTegcC40(Double tegcC40);
	public Double getTegcC42();
	public void setTegcC42(Double tegcC42);
	public Double getTegcC41();
	public void setTegcC41(Double tegcC41);
	public Double getTegcC37();
	public void setTegcC37(Double tegcC37);
	public Double getTegcC36();
	public void setTegcC36(Double tegcC36);
	public Double getTegcC39();
	public void setTegcC39(Double tegcC39);
	public Double getTegcC38();
	public void setTegcC38(Double tegcC38);
	public Double getTegcC33();
	public void setTegcC33(Double tegcC33);
	public Double getTegcC32();
	public void setTegcC32(Double tegcC32);
	public Double getTegcC35();
	public void setTegcC35(Double tegcC35);
	public Double getTegcC34();
	public void setTegcC34(Double tegcC34);
	public Double getTegcC31();
	public void setTegcC31(Double tegcC31);
	public Double getTegcC30();
	public void setTegcC30(Double tegcC30);
	public Double getTegcC26();
	public void setTegcC26(Double tegcC26);
	public Double getTegcC25();
	public void setTegcC25(Double tegcC25);
	public Double getTegcC28();
	public void setTegcC28(Double tegcC28);
	public Double getTegcC27();
	public void setTegcC27(Double tegcC27);
	public Double getTegcC22();
	public void setTegcC22(Double tegcC22);
	public Double getTegcC21();
	public void setTegcC21(Double tegcC21);
	public Double getTegcC24();
	public void setTegcC24(Double tegcC24);
	public Double getTegcC23();
	public void setTegcC23(Double tegcC23);
	public Double getTegcC29();
	public void setTegcC29(Double tegcC29);
	public Double getTegcC20();
	public void setTegcC20(Double tegcC20);
	public Double getTegcC15();
	public void setTegcC15(Double tegcC15);
	public Double getTegcC14();
	public void setTegcC14(Double tegcC14);
	public Double getTegcC17();
	public void setTegcC17(Double tegcC17);
	public Double getTegcC16();
	public void setTegcC16(Double tegcC16);
	public Double getTegcC11();
	public void setTegcC11(Double tegcC11);
	public Double getTegcC10();
	public void setTegcC10(Double tegcC10);
	public Double getTegcC13();
	public void setTegcC13(Double tegcC13);
	public Double getTegcC12();
	public void setTegcC12(Double tegcC12);
	public Double getTegcC19();
	public void setTegcC19(Double tegcC19);
	public Double getTegcC18();
	public void setTegcC18(Double tegcC18);
	public Date getTegcDate();
	public void setTegcDate(Date tegcDate);
	public String getTegcJobId();
	public void setTegcJobId(String tegcJobId);
	public String getTegcLab();
	public void setTegcLab(String tegcLab);
	public String getTegcComment();
	public void setTegcComment(String tegcComment);
	public String getTegcSvcCode();
	public void setTegcSvcCode(String tegcSvcCode);
	public String getTegcSampleIdVend();
	public void setTegcSampleIdVend(String tegcSampleIdVend);
	public String getTegcIqmCode();
	public void setTegcIqmCode(String tegcIqmCode);
	public Date getTegcQcDate();
	public void setTegcQcDate(Date tegcQcDate);
	public Double getTegcC44pls();
	public void setTegcC44pls(Double tegcC44pls);
	public String getTegcRunNumber();
	public void setTegcRunNumber(String tegcRunNumber);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getTegcQcUser();
	public void setTegcQcUser(String tegcQcUser);
	public String getTegcAuthor();
	public void setTegcAuthor(String tegcAuthor);
	public String getTegcQc();
	public void setTegcQc(String tegcQc);
	public Double getTegcC4();
	public void setTegcC4(Double tegcC4);
	public Double getTegcC7();
	public void setTegcC7(Double tegcC7);
	public Double getTegcC8();
	public void setTegcC8(Double tegcC8);
	public Double getTegcC5();
	public void setTegcC5(Double tegcC5);
	public Double getTegcC6();
	public void setTegcC6(Double tegcC6);
	public Double getTegcC9();
	public void setTegcC9(Double tegcC9);
	public Date getLastUpdate();
	public void setLastUpdate(Date lastUpdate);
	public Double getTegcC34pls();
	public void setTegcC34pls(Double tegcC34pls);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Date getTegcAcqDate();
	public void setTegcAcqDate(Date tegcAcqDate);
}
