package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOGcXmdgcNaph extends GTOAnalysisData {
	public String getXnComments();
	public void setXnComments(String xnComments);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Date getXnAcqDate();
	public void setXnAcqDate(Date xnAcqDate);
	public Date getXnDate();
	public void setXnDate(Date xnDate);
	public Double getXnTmn1();
	public void setXnTmn1(Double xnTmn1);
	public Double getXnTmn2();
	public void setXnTmn2(Double xnTmn2);
	public Double getXnTmn3();
	public void setXnTmn3(Double xnTmn3);
	public Date getXnQcDate();
	public void setXnQcDate(Date xnQcDate);
	public String getXnQcUser();
	public void setXnQcUser(String xnQcUser);
	public String getXnMethod();
	public void setXnMethod(String xnMethod);
	public Double getXnDmn5();
	public void setXnDmn5(Double xnDmn5);
	public Double getXnDmn4();
	public void setXnDmn4(Double xnDmn4);
	public Double getXnDmn7();
	public void setXnDmn7(Double xnDmn7);
	public Double getXnDmn6();
	public void setXnDmn6(Double xnDmn6);
	public Double getXnDmn9();
	public void setXnDmn9(Double xnDmn9);
	public Double getXnDmn8();
	public void setXnDmn8(Double xnDmn8);
	public Double getXnDmn1();
	public void setXnDmn1(Double xnDmn1);
	public Double getXnDmn3();
	public void setXnDmn3(Double xnDmn3);
	public Double getXnDmn2();
	public void setXnDmn2(Double xnDmn2);
	public String getXnSvcCode();
	public void setXnSvcCode(String xnSvcCode);
	public String getXnAuthor();
	public void setXnAuthor(String xnAuthor);
	public Date getXnLastUpdate();
	public void setXnLastUpdate(Date xnLastUpdate);
	public String getXnJobId();
	public void setXnJobId(String xnJobId);
	public String getXnDataType();
	public void setXnDataType(String xnDataType);
	public Double getXnMn1();
	public void setXnMn1(Double xnMn1);
	public Double getXnMn2();
	public void setXnMn2(Double xnMn2);
	public String getXnRunNumber();
	public void setXnRunNumber(String xnRunNumber);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getXnSampleIdVend();
	public void setXnSampleIdVend(String xnSampleIdVend);
	public String getXnIqmCode();
	public void setXnIqmCode(String xnIqmCode);
	public String getXnLab();
	public void setXnLab(String xnLab);
	public String getXnQc();
	public void setXnQc(String xnQc);
}
