package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOIsotopesOil extends GTOAnalysisData {
	public Double getDdOWho();
	public void setDdOWho(Double ddOWho);
	public Double getDdOSat();
	public void setDdOSat(Double ddOSat);
	public Double getDdONso();
	public void setDdONso(Double ddONso);
	public Double getDsOSat();
	public void setDsOSat(Double dsOSat);
	public String getRequestId();
	public void setRequestId(String dORequest);
	public Double getDdOAro();
	public void setDdOAro(Double ddOAro);
	public Date getDOAcqDate();
	public void setDOAcqDate(Date dOAcqDate);
	public String getDOQc();
	public void setDOQc(String dOQc);
	public Double getDnOAsph();
	public void setDnOAsph(Double dnOAsph);
	public Double getDdOAsph();
	public void setDdOAsph(Double ddOAsph);
	public Date getDoQcDate();
	public void setDoQcDate(Date doQcDate);
	public String getDOComments();
	public void setDOComments(String dOComments);
	public Double getDcOOil();
	public void setDcOOil(Double dcOOil);
	public Double getIsoOil();
	public void setIsoOil(Double isoOil);
	public String getDOAuthor();
	public void setDOAuthor(String dOAuthor);
	public String getDOLab();
	public void setDOLab(String dOLab);
	public Double getDsONso();
	public void setDsONso(Double dsONso);
	public Double getDcOSat();
	public void setDcOSat(Double dcOSat);
	public Double getDsOWho();
	public void setDsOWho(Double dsOWho);
	public Double getDnOWho();
	public void setDnOWho(Double dnOWho);
	public Double getIsoSat();
	public void setIsoSat(Double isoSat);
	public Double getDoOWho();
	public void setDoOWho(Double doOWho);
	public Double getDsOAro();
	public void setDsOAro(Double dsOAro);
	public Double getDdONpar();
	public void setDdONpar(Double ddONpar);
	public Double getDnONso();
	public void setDnONso(Double dnONso);
	public String getDoQcUser();
	public void setDoQcUser(String doQcUser);
	public Double getDoONso();
	public void setDoONso(Double doONso);
	public String getDOSampleIdVend();
	public void setDOSampleIdVend(String dOSampleIdVend);
	public Double getDcOAro();
	public void setDcOAro(Double dcOAro);
	public String getDOMethod();
	public void setDOMethod(String dOMethod);
	public Double getDsOAsph();
	public void setDsOAsph(Double dsOAsph);
	public Double getIsoAro();
	public void setIsoAro(Double isoAro);
	public Double getDcOAsph();
	public void setDcOAsph(Double dcOAsph);
	public Double getDcOWho();
	public void setDcOWho(Double dcOWho);
	public Double getDcONso();
	public void setDcONso(Double dcONso);
	public Double getDcOIso();
	public void setDcOIso(Double dcOIso);
	public String getDOJobId();
	public void setDOJobId(String dOJobId);
	public Double getDdOTop();
	public void setDdOTop(Double ddOTop);
	public Date getDOLastUpdate();
	public void setDOLastUpdate(Date dOLastUpdate);
	public String getDORunNumber();
	public void setDORunNumber(String dORunNumber);
	public Double getDdOIso();
	public void setDdOIso(Double ddOIso);
	public Double getDsOTop();
	public void setDsOTop(Double dsOTop);
	public Double getDcONpar();
	public void setDcONpar(Double dcONpar);
	public Double getDnOTop();
	public void setDnOTop(Double dnOTop);
	public Double getDoOTop();
	public void setDoOTop(Double doOTop);
	public String getDOSvcCode();
	public void setDOSvcCode(String dOSvcCode);
	public String getDODataType();
	public void setDODataType(String dODataType);
	public String getDoIqmCode();
	public void setDoIqmCode(String doIqmCode);
	public Double getDoOAsph();
	public void setDoOAsph(Double doOAsph);
	public String getSampleId();
	public void setSampleId(String dOSampleId);
}
