package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOIsotopesGas extends GTOAnalysisData  {
	public String getDGMethod();
	public void setDGMethod(String dGMethod);
	public String getCsiaNc19Q();
	public void setCsiaNc19Q(String csiaNc19Q);
	public Double getCsiaEthene();
	public void setCsiaEthene(Double csiaEthene);
	public String getCsiaPrQ();
	public void setCsiaPrQ(String csiaPrQ);
	public Date getDGHtQcDate();
	public void setDGHtQcDate(Date dGHtQcDate);
	public String getDdGNc17Q();
	public void setDdGNc17Q(String ddGNc17Q);
	public String getDGQc();
	public void setDGQc(String dGQc);
	public Double getDcGGas();
	public void setDcGGas(Double dcGGas);
	public String getDdGNc6Q();
	public void setDdGNc6Q(String ddGNc6Q);
	public String getCsiaNeoc5Q();
	public void setCsiaNeoc5Q(String csiaNeoc5Q);
	public String getCsiaNc32Q();
	public void setCsiaNc32Q(String csiaNc32Q);
	public Double getDoGCo2();
	public void setDoGCo2(Double doGCo2);
	public Double getDdGNc33();
	public void setDdGNc33(Double ddGNc33);
	public Double getDdGNc34();
	public void setDdGNc34(Double ddGNc34);
	public Double getDdGNc35();
	public void setDdGNc35(Double ddGNc35);
	public Double getDdGNc30();
	public void setDdGNc30(Double ddGNc30);
	public Double getDdGNc31();
	public void setDdGNc31(Double ddGNc31);
	public Double getDdGNc32();
	public void setDdGNc32(Double ddGNc32);
	public Double getDdGNc26();
	public void setDdGNc26(Double ddGNc26);
	public Double getDdGNc27();
	public void setDdGNc27(Double ddGNc27);
	public Double getDdGNc28();
	public void setDdGNc28(Double ddGNc28);
	public Double getDdGNc29();
	public void setDdGNc29(Double ddGNc29);
	public String getDdGGasQ();
	public void setDdGGasQ(String ddGGasQ);
	public Double getDdGNc22();
	public void setDdGNc22(Double ddGNc22);
	public Double getDdGNc23();
	public void setDdGNc23(Double ddGNc23);
	public Double getDdGNc24();
	public void setDdGNc24(Double ddGNc24);
	public Double getDdGNc25();
	public void setDdGNc25(Double ddGNc25);
	public Double getDdGNc20();
	public void setDdGNc20(Double ddGNc20);
	public Double getDdGNc21();
	public void setDdGNc21(Double ddGNc21);
	public Double getDdGNc19();
	public void setDdGNc19(Double ddGNc19);
	public Double getDdGNc15();
	public void setDdGNc15(Double ddGNc15);
	public Double getDdGNc16();
	public void setDdGNc16(Double ddGNc16);
	public Double getDdGNc17();
	public void setDdGNc17(Double ddGNc17);
	public Double getDdGNc18();
	public void setDdGNc18(Double ddGNc18);
	public Double getDdGNc11();
	public void setDdGNc11(Double ddGNc11);
	public Double getDdGNc12();
	public void setDdGNc12(Double ddGNc12);
	public Double getDdGNc13();
	public void setDdGNc13(Double ddGNc13);
	public Double getDdGNc14();
	public void setDdGNc14(Double ddGNc14);
	public Double getDdGNc10();
	public void setDdGNc10(Double ddGNc10);
	public String getCsiaNc1Q();
	public void setCsiaNc1Q(String csiaNc1Q);
	public String getCsiaNc11Q();
	public void setCsiaNc11Q(String csiaNc11Q);
	public String getDdGNc21Q();
	public void setDdGNc21Q(String ddGNc21Q);
	public String getCsiaIc16Q();
	public void setCsiaIc16Q(String csiaIc16Q);
	public String getCsiaNc33Q();
	public void setCsiaNc33Q(String csiaNc33Q);
	public String getDdGNc2Q();
	public void setDdGNc2Q(String ddGNc2Q);
	public Double getCsiaConcC1();
	public void setCsiaConcC1(Double csiaConcC1);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getDdGNc30Q();
	public void setDdGNc30Q(String ddGNc30Q);
	public String getCsiaEtheneQ();
	public void setCsiaEtheneQ(String csiaEtheneQ);
	public String getCsiaNc6Q();
	public void setCsiaNc6Q(String csiaNc6Q);
	public Double getDdGIc4();
	public void setDdGIc4(Double ddGIc4);
	public String getCsiaNc24Q();
	public void setCsiaNc24Q(String csiaNc24Q);
	public Double getDdGIc5();
	public void setDdGIc5(Double ddGIc5);
	public Double getDdGH2();
	public void setDdGH2(Double ddGH2);
	public String getDdGNc25Q();
	public void setDdGNc25Q(String ddGNc25Q);
	public String getCsiaNc15Q();
	public void setCsiaNc15Q(String csiaNc15Q);
	public String getDdGNc34Q();
	public void setDdGNc34Q(String ddGNc34Q);
	public String getDGDataType();
	public void setDGDataType(String dGDataType);
	public String getCsiaNc28Q();
	public void setCsiaNc28Q(String csiaNc28Q);
	public String getDdGNc12Q();
	public void setDdGNc12Q(String ddGNc12Q);
	public String getDdGNc29Q();
	public void setDdGNc29Q(String ddGNc29Q);
	public String getDGSvcCode();
	public void setDGSvcCode(String dGSvcCode);
	public String getDdGNc16Q();
	public void setDdGNc16Q(String ddGNc16Q);
	public String getDGJobId();
	public void setDGJobId(String dGJobId);
	public String getDdGNc9Q();
	public void setDdGNc9Q(String ddGNc9Q);
	public String getCsiaNc31Q();
	public void setCsiaNc31Q(String csiaNc31Q);
	public String getCsiaPhQ();
	public void setCsiaPhQ(String csiaPhQ);
	public String getDnGN2Q();
	public void setDnGN2Q(String dnGN2Q);
	public Double getCsiaPh();
	public void setCsiaPh(Double csiaPh);
	public Double getCsiaPr();
	public void setCsiaPr(Double csiaPr);
	public String getDcGCo2Q();
	public void setDcGCo2Q(String dcGCo2Q);
	public String getCsiaNc23Q();
	public void setCsiaNc23Q(String csiaNc23Q);
	public String getDdGNc33Q();
	public void setDdGNc33Q(String ddGNc33Q);
	public String getCsiaNc10Q();
	public void setCsiaNc10Q(String csiaNc10Q);
	public String getCsiaIc15Q();
	public void setCsiaIc15Q(String csiaIc15Q);
	public String getDdGNc5Q();
	public void setDdGNc5Q(String ddGNc5Q);
	public String getCsiaNc14Q();
	public void setCsiaNc14Q(String csiaNc14Q);
	public String getCsiaNc5Q();
	public void setCsiaNc5Q(String csiaNc5Q);
	public String getDdGNc20Q();
	public void setDdGNc20Q(String ddGNc20Q);
	public String getCsiaNc27Q();
	public void setCsiaNc27Q(String csiaNc27Q);
	public String getDdGNc15Q();
	public void setDdGNc15Q(String ddGNc15Q);
	public Double getDdGNc4();
	public void setDdGNc4(Double ddGNc4);
	public Double getDdGNc5();
	public void setDdGNc5(Double ddGNc5);
	public Double getDdGNc6();
	public void setDdGNc6(Double ddGNc6);
	public Double getDdGNc8();
	public void setDdGNc8(Double ddGNc8);
	public Double getDdGNc9();
	public void setDdGNc9(Double ddGNc9);
	public Double getDdGNc1();
	public void setDdGNc1(Double ddGNc1);
	public Double getDdGNc2();
	public void setDdGNc2(Double ddGNc2);
	public Double getDdGNc3();
	public void setDdGNc3(Double ddGNc3);
	public String getDdGNc11Q();
	public void setDdGNc11Q(String ddGNc11Q);
	public String getDdGNc1Q();
	public void setDdGNc1Q(String ddGNc1Q);
	public String getCsiaNc18Q();
	public void setCsiaNc18Q(String csiaNc18Q);
	public String getCsiaConcC1Q();
	public void setCsiaConcC1Q(String csiaConcC1Q);
	public String getDdGNc24Q();
	public void setDdGNc24Q(String ddGNc24Q);
	public String getCsiaNc9Q();
	public void setCsiaNc9Q(String csiaNc9Q);
	public String getDdGNc19Q();
	public void setDdGNc19Q(String ddGNc19Q);
	public String getCsiaIc5Q();
	public void setCsiaIc5Q(String csiaIc5Q);
	public String getDdGNc28Q();
	public void setDdGNc28Q(String ddGNc28Q);
	public String getDsGH2sQ();
	public void setDsGH2sQ(String dsGH2sQ);
	public String getDdGIc5Q();
	public void setDdGIc5Q(String ddGIc5Q);
	public String getDoGCoQ();
	public void setDoGCoQ(String doGCoQ);
	public String getCsiaIc13Q();
	public void setCsiaIc13Q(String csiaIc13Q);
	public String getCsiaNc30Q();
	public void setCsiaNc30Q(String csiaNc30Q);
	public Double getDdGGas();
	public void setDdGGas(Double ddGGas);
	public String getCsiaPropeneQ();
	public void setCsiaPropeneQ(String csiaPropeneQ);
	public Double getDsGH2s();
	public void setDsGH2s(Double dsGH2s);
	public String getCsiaNc21Q();
	public void setCsiaNc21Q(String csiaNc21Q);
	public String getDdGNc8Q();
	public void setDdGNc8Q(String ddGNc8Q);
	public String getDdGNc32Q();
	public void setDdGNc32Q(String ddGNc32Q);
	public String getCsiaNc4Q();
	public void setCsiaNc4Q(String csiaNc4Q);
	public Double getCsiaPropene();
	public void setCsiaPropene(Double csiaPropene);
	public String getDdGH2Q();
	public void setDdGH2Q(String ddGH2Q);
	public String getCsiaNc35Q();
	public void setCsiaNc35Q(String csiaNc35Q);
	public String getDGRunNumber();
	public void setDGRunNumber(String dGRunNumber);
	public String getDdGNc10Q();
	public void setDdGNc10Q(String ddGNc10Q);
	public String getCsiaNc22Q();
	public void setCsiaNc22Q(String csiaNc22Q);
	public String getCsiaIc14Q();
	public void setCsiaIc14Q(String csiaIc14Q);
	public Double getCsiaNc29();
	public void setCsiaNc29(Double csiaNc29);
	public Double getCsiaNc28();
	public void setCsiaNc28(Double csiaNc28);
	public Double getCsiaNc27();
	public void setCsiaNc27(Double csiaNc27);
	public Double getCsiaNc26();
	public void setCsiaNc26(Double csiaNc26);
	public Double getCsiaNc21();
	public void setCsiaNc21(Double csiaNc21);
	public Double getCsiaNc20();
	public void setCsiaNc20(Double csiaNc20);
	public Double getCsiaNc25();
	public void setCsiaNc25(Double csiaNc25);
	public Double getCsiaNc24();
	public void setCsiaNc24(Double csiaNc24);
	public Double getCsiaNc23();
	public void setCsiaNc23(Double csiaNc23);
	public Double getCsiaNc22();
	public void setCsiaNc22(Double csiaNc22);
	public String getDdGNc4Q();
	public void setDdGNc4Q(String ddGNc4Q);
	public String getDGLab();
	public void setDGLab(String dGLab);
	public String getDGSampleIdVend();
	public void setDGSampleIdVend(String dGSampleIdVend);
	public String getCsiaNc13Q();
	public void setCsiaNc13Q(String csiaNc13Q);
	public Double getCsiaNc32();
	public void setCsiaNc32(Double csiaNc32);
	public Double getCsiaNc31();
	public void setCsiaNc31(Double csiaNc31);
	public Double getCsiaNc30();
	public void setCsiaNc30(Double csiaNc30);
	public Double getCsiaNc35();
	public void setCsiaNc35(Double csiaNc35);
	public Double getCsiaNc34();
	public void setCsiaNc34(Double csiaNc34);
	public Double getCsiaNc33();
	public void setCsiaNc33(Double csiaNc33);
	public Double getCsiaNc2();
	public void setCsiaNc2(Double csiaNc2);
	public Double getCsiaNc3();
	public void setCsiaNc3(Double csiaNc3);
	public Double getCsiaNc1();
	public void setCsiaNc1(Double csiaNc1);
	public Double getCsiaNc8();
	public void setCsiaNc8(Double csiaNc8);
	public Double getCsiaNc9();
	public void setCsiaNc9(Double csiaNc9);
	public Double getCsiaNc6();
	public void setCsiaNc6(Double csiaNc6);
	public Double getCsiaNc7();
	public void setCsiaNc7(Double csiaNc7);
	public Double getCsiaNc4();
	public void setCsiaNc4(Double csiaNc4);
	public Double getCsiaNc5();
	public void setCsiaNc5(Double csiaNc5);
	public String getCsiaNc8Q();
	public void setCsiaNc8Q(String csiaNc8Q);
	public Double getCsiaNc18();
	public void setCsiaNc18(Double csiaNc18);
	public Double getCsiaNc17();
	public void setCsiaNc17(Double csiaNc17);
	public Double getCsiaNc16();
	public void setCsiaNc16(Double csiaNc16);
	public String getDdGNc14Q();
	public void setDdGNc14Q(String ddGNc14Q);
	public Double getCsiaNc15();
	public void setCsiaNc15(Double csiaNc15);
	public Double getCsiaNc19();
	public void setCsiaNc19(Double csiaNc19);
	public Double getCsiaNc10();
	public void setCsiaNc10(Double csiaNc10);
	public Double getCsiaNc14();
	public void setCsiaNc14(Double csiaNc14);
	public Double getCsiaNc13();
	public void setCsiaNc13(Double csiaNc13);
	public Double getCsiaNc12();
	public void setCsiaNc12(Double csiaNc12);
	public Double getCsiaNc11();
	public void setCsiaNc11(Double csiaNc11);
	public String getCsiaNc26Q();
	public void setCsiaNc26Q(String csiaNc26Q);
	public Date getDGLastUpdate();
	public void setDGLastUpdate(Date dGLastUpdate);
	public String getDdGNc23Q();
	public void setDdGNc23Q(String ddGNc23Q);
	public String getCsiaIc18Q();
	public void setCsiaIc18Q(String csiaIc18Q);
	public String getCsiaNc17Q();
	public void setCsiaNc17Q(String csiaNc17Q);
	public String getDdGNc18Q();
	public void setDdGNc18Q(String ddGNc18Q);
	public String getDGHtQcUser();
	public void setDGHtQcUser(String dGHtQcUser);
	public Date getDGAcqDate();
	public void setDGAcqDate(Date dGAcqDate);
	public String getDdGNc27Q();
	public void setDdGNc27Q(String ddGNc27Q);
	public String getDdGIc4Q();
	public void setDdGIc4Q(String ddGIc4Q);
	public Double getDnGN2();
	public void setDnGN2(Double dnGN2);
	public Double getCsiaIc18();
	public void setCsiaIc18(Double csiaIc18);
	public Double getCsiaIc13();
	public void setCsiaIc13(Double csiaIc13);
	public Double getCsiaIc15();
	public void setCsiaIc15(Double csiaIc15);
	public Double getCsiaIc14();
	public void setCsiaIc14(Double csiaIc14);
	public Double getCsiaIc16();
	public void setCsiaIc16(Double csiaIc16);
	public String getDGComments();
	public void setDGComments(String dGComments);
	public String getDGHtIqmCode();
	public void setDGHtIqmCode(String dGHtIqmCode);
	public String getCsiaNc2Q();
	public void setCsiaNc2Q(String csiaNc2Q);
	public Double getCsiaIc5();
	public void setCsiaIc5(Double csiaIc5);
	public Double getCsiaIc4();
	public void setCsiaIc4(Double csiaIc4);
	public String getCsiaNc20Q();
	public void setCsiaNc20Q(String csiaNc20Q);
	public String getCsiaNc34Q();
	public void setCsiaNc34Q(String csiaNc34Q);
	public String getDdGNc3Q();
	public void setDdGNc3Q(String ddGNc3Q);
	public String getCsiaNc3Q();
	public void setCsiaNc3Q(String csiaNc3Q);
	public String getDdGNc22Q();
	public void setDdGNc22Q(String ddGNc22Q);
	public String getCsiaNc25Q();
	public void setCsiaNc25Q(String csiaNc25Q);
	public String getDdGNc31Q();
	public void setDdGNc31Q(String ddGNc31Q);
	public String getCsiaNc12Q();
	public void setCsiaNc12Q(String csiaNc12Q);
	public String getDoGCo2Q();
	public void setDoGCo2Q(String doGCo2Q);
	public Double getDdGH2s();
	public void setDdGH2s(Double ddGH2s);
	public String getCsiaNc16Q();
	public void setCsiaNc16Q(String csiaNc16Q);
	public String getDdGNc26Q();
	public void setDdGNc26Q(String ddGNc26Q);
	public String getCsiaIc4Q();
	public void setCsiaIc4Q(String csiaIc4Q);
	public String getCsiaNc7Q();
	public void setCsiaNc7Q(String csiaNc7Q);
	public String getCsiaNc29Q();
	public void setCsiaNc29Q(String csiaNc29Q);
	public String getDGAuthor();
	public void setDGAuthor(String dGAuthor);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getDdGNc35Q();
	public void setDdGNc35Q(String ddGNc35Q);
	public String getDdGH2sQ();
	public void setDdGH2sQ(String ddGH2sQ);
	public Double getCsiaNeoc5();
	public void setCsiaNeoc5(Double csiaNeoc5);
	public Double getDcGCo2();
	public void setDcGCo2(Double dcGCo2);
	public String getDdGNc13Q();
	public void setDdGNc13Q(String ddGNc13Q);
	public String getDcGCoQ();
	public void setDcGCoQ(String dcGCoQ);
	public Double getDcGCo();
	public void setDcGCo(Double dcGCo);
	public Double getDdGCh4();
	public void setDdGCh4(Double ddGCh4);
	public Double getCsiaNc36();
	public void setCsiaNc36(Double csiaNc36);
	public String getDoComments();
	public void setDoComments(String doComments);
	public String getDGOwner();
	public void setDGOwner(String dGOwner);
	public String getDdComments();
	public void setDdComments(String ddComments);
	public Integer getDGRecordType();
	public void setDGRecordType(Integer dGRecordType);
	public Integer getDGCalibration();
	public void setDGCalibration(Integer dGCalibration);
	public Integer getDGMethodNew();
	public void setDGMethodNew(Integer dGMethodNew);
	public Integer getDGUom();
	public void setDGUom(Integer dGUom);
	public Integer getDGCalibConf();
	public void setDGCalibConf(Integer dGCalibConf);
}
