package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOLiqPah extends GTOAnalysisData {
	public String getPahAnthraceneQ();
	public void setPahAnthraceneQ(String pahAnthraceneQ);
	public String getPahQcUser();
	public void setPahQcUser(String pahQcUser);
	public Integer getPahMethodId();
	public void setPahMethodId(Integer pahMethodId);
	public Double getPahChrysene();
	public void setPahChrysene(Double pahChrysene);
	public String getPahUpdatedUser();
	public void setPahUpdatedUser(String pahUpdatedUser);
	public Double getPahAnthracene();
	public void setPahAnthracene(Double pahAnthracene);
	public String getPahIndeoQ();
	public void setPahIndeoQ(String pahIndeoQ);
	public Date getPahQcDate();
	public void setPahQcDate(Date pahQcDate);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Integer getPahRunNumber();
	public void setPahRunNumber(Integer pahRunNumber);
	public String getPahBenzAQ();
	public void setPahBenzAQ(String pahBenzAQ);
	public Date getPahUpdatedDate();
	public void setPahUpdatedDate(Date pahUpdatedDate);
	public String getPahSvcCode();
	public void setPahSvcCode(String pahSvcCode);
	public Integer getPahLab();
	public void setPahLab(Integer pahLab);
	public Double getPahFluorene();
	public void setPahFluorene(Double pahFluorene);
	public String getPahFluoreneQ();
	public void setPahFluoreneQ(String pahFluoreneQ);
	public Double getPahBenzoK();
	public void setPahBenzoK(Double pahBenzoK);
	public Double getPahBenzoB();
	public void setPahBenzoB(Double pahBenzoB);
	public Double getPahBenzoA();
	public void setPahBenzoA(Double pahBenzoA);
	public String getPahChryseneQ();
	public void setPahChryseneQ(String pahChryseneQ);
	public Double getPahBenzoGhl();
	public void setPahBenzoGhl(Double pahBenzoGhl);
	public Date getPahAcqDate();
	public void setPahAcqDate(Date pahAcqDate);
	public String getPahRequestIdVend();
	public void setPahRequestIdVend(String pahRequestIdVend);
	public Integer getPahRecordTypeId();
	public void setPahRecordTypeId(Integer pahRecordTypeId);
	public String getPahBenzoAQ();
	public void setPahBenzoAQ(String pahBenzoAQ);
	public Date getPahCreatedDate();
	public void setPahCreatedDate(Date pahCreatedDate);
	public String getPahBenzoGhlQ();
	public void setPahBenzoGhlQ(String pahBenzoGhlQ);
	public String getPahAcenaphthyleneQ();
	public void setPahAcenaphthyleneQ(String pahAcenaphthyleneQ);
	public String getPahSampleIdVend();
	public void setPahSampleIdVend(String pahSampleIdVend);
	public String getPahAcenaphtheneQ();
	public void setPahAcenaphtheneQ(String pahAcenaphtheneQ);
	public Integer getPahPk();
	public void setPahPk(Integer pahPk);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getPahComment();
	public void setPahComment(String pahComment);
	public String getPahBenzoBQ();
	public void setPahBenzoBQ(String pahBenzoBQ);
	public Double getPahFloranthene();
	public void setPahFloranthene(Double pahFloranthene);
	public Double getPahAcenaphthylene();
	public void setPahAcenaphthylene(Double pahAcenaphthylene);
	public Integer getPahUnitsId();
	public void setPahUnitsId(Integer pahUnitsId);
	public String getPahCreatedUser();
	public void setPahCreatedUser(String pahCreatedUser);
	public String getPahFlorantheneQ();
	public void setPahFlorantheneQ(String pahFlorantheneQ);
	public Double getPahIndeo();
	public void setPahIndeo(Double pahIndeo);
	public Double getPahBenzA();
	public void setPahBenzA(Double pahBenzA);
	public String getPahIqmCode();
	public void setPahIqmCode(String pahIqmCode);
	public String getPahDibenzQ();
	public void setPahDibenzQ(String pahDibenzQ);
	public Integer getPahConfTypeId();
	public void setPahConfTypeId(Integer pahConfTypeId);
	public String getPahPyreneQ();
	public void setPahPyreneQ(String pahPyreneQ);
	public Double getPahPyrene();
	public void setPahPyrene(Double pahPyrene);
	public Double getPahAcenaphthene();
	public void setPahAcenaphthene(Double pahAcenaphthene);
	public Double getPahDibenz();
	public void setPahDibenz(Double pahDibenz);
	public String getPahBenzoKQ();
	public void setPahBenzoKQ(String pahBenzoKQ);
}
