package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOLiqConRes extends GTOAnalysisData {
	public Integer getCrConTempUnitsId();
	public void setCrConTempUnitsId(Integer crConTempUnitsId);
	public String getCrSampleIdVend();
	public void setCrSampleIdVend(String crSampleIdVend);
	public Date getCrAcqDate();
	public void setCrAcqDate(Date crAcqDate);
	public Date getCrCreatedDate();
	public void setCrCreatedDate(Date crCreatedDate);
	public Integer getCrConfTypeId();
	public void setCrConfTypeId(Integer crConfTypeId);
	public Integer getCrResMethodId();
	public void setCrResMethodId(Integer crResMethodId);
	public String getCrResQ();
	public void setCrResQ(String crResQ);
	public Date getCrQcDate();
	public void setCrQcDate(Date crQcDate);
	public Integer getCrRecordTypeId();
	public void setCrRecordTypeId(Integer crRecordTypeId);
	public Double getCrRes();
	public void setCrRes(Double crRes);
	public String getCrAuthor();
	public void setCrAuthor(String crAuthor);
	public String getCrComment();
	public void setCrComment(String crComment);
	public Integer getCrPk();
	public void setCrPk(Integer crPk);
	public Double getCrCon();
	public void setCrCon(Double crCon);
	public String getCrConQ();
	public void setCrConQ(String crConQ);
	public String getCrSvcCode();
	public void setCrSvcCode(String crSvcCode);
	public String getCrRunNumber();
	public void setCrRunNumber(String crRunNumber);
	public Date getCrUpdatedDate();
	public void setCrUpdatedDate(Date crUpdatedDate);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Integer getCrResUnitsId();
	public void setCrResUnitsId(Integer crResUnitsId);
	public Integer getCrConUnitsId();
	public void setCrConUnitsId(Integer crConUnitsId);
	public String getCrUpdatedUser();
	public void setCrUpdatedUser(String crUpdatedUser);
	public Double getCrResTemp();
	public void setCrResTemp(Double crResTemp);
	public Integer getCrConMethodId();
	public void setCrConMethodId(Integer crConMethodId);
	public String getCrQcUser();
	public void setCrQcUser(String crQcUser);
	public String getCrRequestIdVend();
	public void setCrRequestIdVend(String crRequestIdVend);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getCrConTemp();
	public void setCrConTemp(Double crConTemp);
	public Integer getCrLab();
	public void setCrLab(Integer crLab);
	public Integer getCrResTempUnitsId();
	public void setCrResTempUnitsId(Integer crResTempUnitsId);
	public String getCrCreatedUser();
	public void setCrCreatedUser(String crCreatedUser);
}
