package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOLiqOrganicacids extends GTOAnalysisData {
	public Double getOaForm();
	public void setOaForm(Double oaForm);
	public String getOaComment();
	public void setOaComment(String oaComment);
	public Double getOaVal();
	public void setOaVal(Double oaVal);
	public String getOaValQ();
	public void setOaValQ(String oaValQ);
	public Date getOaUpdatedDate();
	public void setOaUpdatedDate(Date oaUpdatedDate);
	public String getOaQcUser();
	public void setOaQcUser(String oaQcUser);
	public String getOaIqmCode();
	public void setOaIqmCode(String oaIqmCode);
	public Double getOaSuc();
	public void setOaSuc(Double oaSuc);
	public Double getOaNVal();
	public void setOaNVal(Double oaNVal);
	public String getOaOxalQ();
	public void setOaOxalQ(String oaOxalQ);
	public Double getOaButy();
	public void setOaButy(Double oaButy);
	public Double getOaGlyoxylicAcid();
	public void setOaGlyoxylicAcid(Double oaGlyoxylicAcid);
	public Double getOaCitric();
	public void setOaCitric(Double oaCitric);
	public String getOaNValQ();
	public void setOaNValQ(String oaNValQ);
	public String getOaRequestIdVend();
	public void setOaRequestIdVend(String oaRequestIdVend);
	public String getOaNButyQ();
	public void setOaNButyQ(String oaNButyQ);
	public String getOaCitricQ();
	public void setOaCitricQ(String oaCitricQ);
	public Integer getOaRecordTypeId();
	public void setOaRecordTypeId(Integer oaRecordTypeId);
	public String getOaMalonQ();
	public void setOaMalonQ(String oaMalonQ);
	public Double getOaNHex();
	public void setOaNHex(Double oaNHex);
	public String getOaIsoHexQ();
	public void setOaIsoHexQ(String oaIsoHexQ);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Date getOaQcDate();
	public void setOaQcDate(Date oaQcDate);
	public String getOaHepQ();
	public void setOaHepQ(String oaHepQ);
	public Double getOaIsoHex();
	public void setOaIsoHex(Double oaIsoHex);
	public Double getOaHex();
	public void setOaHex(Double oaHex);
	public Double getOaHep();
	public void setOaHep(Double oaHep);
	public Integer getOaMethodId();
	public void setOaMethodId(Integer oaMethodId);
	public String getOaAceQ();
	public void setOaAceQ(String oaAceQ);
	public String getOaGlyoxylicQ();
	public void setOaGlyoxylicQ(String oaGlyoxylicQ);
	public Double getOaIsoButy();
	public void setOaIsoButy(Double oaIsoButy);
	public Date getOaCreatedDate();
	public void setOaCreatedDate(Date oaCreatedDate);
	public Date getOaAcqDate();
	public void setOaAcqDate(Date oaAcqDate);
	public String getOaIsoValQ();
	public void setOaIsoValQ(String oaIsoValQ);
	public String getOaSampleIdVend();
	public void setOaSampleIdVend(String oaSampleIdVend);
	public Double getOaIsoVal();
	public void setOaIsoVal(Double oaIsoVal);
	public String getOaNHexQ();
	public void setOaNHexQ(String oaNHexQ);
	public String getOaButyQ();
	public void setOaButyQ(String oaButyQ);
	public Double getOaNButy();
	public void setOaNButy(Double oaNButy);
	public String getOaFormQ();
	public void setOaFormQ(String oaFormQ);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getOaCreatedUser();
	public void setOaCreatedUser(String oaCreatedUser);
	public String getOaGlycQ();
	public void setOaGlycQ(String oaGlycQ);
	public Double getOaMalon();
	public void setOaMalon(Double oaMalon);
	public Integer getOaLab();
	public void setOaLab(Integer oaLab);
	public Integer getOaUnitsId();
	public void setOaUnitsId(Integer oaUnitsId);
	public String getOaSvcCode();
	public void setOaSvcCode(String oaSvcCode);
	public String getOaSucQ();
	public void setOaSucQ(String oaSucQ);
	public String getOaHexQ();
	public void setOaHexQ(String oaHexQ);
	public String getOaIsoButyQ();
	public void setOaIsoButyQ(String oaIsoButyQ);
	public Double getOaAce();
	public void setOaAce(Double oaAce);
	public Double getOaGlyc();
	public void setOaGlyc(Double oaGlyc);
	public String getOaUpdatedUser();
	public void setOaUpdatedUser(String oaUpdatedUser);
	public Integer getOaConfTypeId();
	public void setOaConfTypeId(Integer oaConfTypeId);
	public Double getOaOxal();
	public void setOaOxal(Double oaOxal);
	public String getOaProQ();
	public void setOaProQ(String oaProQ);
	public Double getOaPro();
	public void setOaPro(Double oaPro);
	public Integer getOaRunNumber();
	public void setOaRunNumber(Integer oaRunNumber);
	public Integer getOaPk();
	public void setOaPk(Integer oaPk);
}
