package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOLiqElemental extends GTOAnalysisData {
	public Double getElNo3();
	public void setElNo3(Double elNo3);
	public String getElThQ();
	public void setElThQ(String elThQ);
	public String getElSeQ();
	public void setElSeQ(String elSeQ);
	public Double getElNh34();
	public void setElNh34(Double elNh34);
	public String getElRbQ();
	public void setElRbQ(String elRbQ);
	public String getElTiQ();
	public void setElTiQ(String elTiQ);
	public String getElHfQ();
	public void setElHfQ(String elHfQ);
	public String getElLaQ();
	public void setElLaQ(String elLaQ);
	public Double getElB();
	public void setElB(Double elB);
	public Double getElC();
	public void setElC(Double elC);
	public Double getElF();
	public void setElF(Double elF);
	public Double getElI();
	public void setElI(Double elI);
	public Double getElK();
	public void setElK(Double elK);
	public Double getElP();
	public void setElP(Double elP);
	public Double getElS();
	public void setElS(Double elS);
	public Double getElU();
	public void setElU(Double elU);
	public Double getElV();
	public void setElV(Double elV);
	public Double getElW();
	public void setElW(Double elW);
	public Double getElY();
	public void setElY(Double elY);
	public String getElBeQ();
	public void setElBeQ(String elBeQ);
	public String getElCuQ();
	public void setElCuQ(String elCuQ);
	public String getElCdQ();
	public void setElCdQ(String elCdQ);
	public String getElBrQ();
	public void setElBrQ(String elBrQ);
	public String getElBaQ();
	public void setElBaQ(String elBaQ);
	public Integer getElConfTypeId();
	public void setElConfTypeId(Integer elConfTypeId);
	public Integer getElLab();
	public void setElLab(Integer elLab);
	public String getElKQ();
	public void setElKQ(String elKQ);
	public Double getElIr();
	public void setElIr(Double elIr);
	public Double getElIn();
	public void setElIn(Double elIn);
	public Double getElHf();
	public void setElHf(Double elHf);
	public Double getElHg();
	public void setElHg(Double elHg);
	public Double getElGa();
	public void setElGa(Double elGa);
	public Double getElGe();
	public void setElGe(Double elGe);
	public Integer getElAnionMethodSpecification();
	public void setElAnionMethodSpecification(Integer elAnionMethodSpecification);
	public Double getElFe();
	public void setElFe(Double elFe);
	public Double getElNitrite();
	public void setElNitrite(Double elNitrite);
	public Double getElCl();
	public void setElCl(Double elCl);
	public Double getElCo();
	public void setElCo(Double elCo);
	public Double getElCr();
	public void setElCr(Double elCr);
	public Double getElCu();
	public void setElCu(Double elCu);
	public Double getElCa();
	public void setElCa(Double elCa);
	public Double getElCd();
	public void setElCd(Double elCd);
	public Double getElBr();
	public void setElBr(Double elBr);
	public Double getElBa();
	public void setElBa(Double elBa);
	public Double getElBe();
	public void setElBe(Double elBe);
	public Double getElBi();
	public void setElBi(Double elBi);
	public Double getElAl();
	public void setElAl(Double elAl);
	public Double getElAs();
	public void setElAs(Double elAs);
	public Double getElAu();
	public void setElAu(Double elAu);
	public Double getElAg();
	public void setElAg(Double elAg);
	public Integer getElCationsMethodId();
	public void setElCationsMethodId(Integer elCationsMethodId);
	public Integer getElAnionsMethodId();
	public void setElAnionsMethodId(Integer elAnionsMethodId);
	public String getElGaQ();
	public void setElGaQ(String elGaQ);
	public String getElIQ();
	public void setElIQ(String elIQ);
	public String getElSiQ();
	public void setElSiQ(String elSiQ);
	public String getElAnionsComment();
	public void setElAnionsComment(String elAnionsComment);
	public String getElTlQ();
	public void setElTlQ(String elTlQ);
	public Double getElZr();
	public void setElZr(Double elZr);
	public Double getElZn();
	public void setElZn(Double elZn);
	public Double getElTl();
	public void setElTl(Double elTl);
	public Double getElTa();
	public void setElTa(Double elTa);
	public Double getElTe();
	public void setElTe(Double elTe);
	public Double getElTh();
	public void setElTh(Double elTh);
	public Double getElTi();
	public void setElTi(Double elTi);
	public Double getElSn();
	public void setElSn(Double elSn);
	public Double getElSr();
	public void setElSr(Double elSr);
	public Double getElSb();
	public void setElSb(Double elSb);
	public Double getElSe();
	public void setElSe(Double elSe);
	public Double getElSi();
	public void setElSi(Double elSi);
	public Double getElRu();
	public void setElRu(Double elRu);
	public Double getElRb();
	public void setElRb(Double elRb);
	public Double getElRe();
	public void setElRe(Double elRe);
	public Double getElRh();
	public void setElRh(Double elRh);
	public Integer getElPk();
	public void setElPk(Integer elPk);
	public Double getElPt();
	public void setElPt(Double elPt);
	public Double getElPb();
	public void setElPb(Double elPb);
	public Double getElPd();
	public void setElPd(Double elPd);
	public Double getElNi();
	public void setElNi(Double elNi);
	public Double getElNa();
	public void setElNa(Double elNa);
	public Double getElNb();
	public void setElNb(Double elNb);
	public String getElZnQ();
	public void setElZnQ(String elZnQ);
	public Double getElMg();
	public void setElMg(Double elMg);
	public Double getElMn();
	public void setElMn(Double elMn);
	public Double getElMo();
	public void setElMo(Double elMo);
	public Double getElLi();
	public void setElLi(Double elLi);
	public Double getElLa();
	public void setElLa(Double elLa);
	public String getElClQ();
	public void setElClQ(String elClQ);
	public String getElBiQ();
	public void setElBiQ(String elBiQ);
	public String getElIqmCode();
	public void setElIqmCode(String elIqmCode);
	public String getElHgQ();
	public void setElHgQ(String elHgQ);
	public String getElCationMethodSpecification();
	public void setElCationMethodSpecification(String elCationMethodSpecification);
	public String getElRuQ();
	public void setElRuQ(String elRuQ);
	public String getElAsQ();
	public void setElAsQ(String elAsQ);
	public String getElNiQ();
	public void setElNiQ(String elNiQ);
	public String getElYQ();
	public void setElYQ(String elYQ);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getElReQ();
	public void setElReQ(String elReQ);
	public String getElGeQ();
	public void setElGeQ(String elGeQ);
	public String getElAuQ();
	public void setElAuQ(String elAuQ);
	public String getElMgQ();
	public void setElMgQ(String elMgQ);
	public String getElPdQ();
	public void setElPdQ(String elPdQ);
	public String getElZrQ();
	public void setElZrQ(String elZrQ);
	public Integer getElRecordTypeId();
	public void setElRecordTypeId(Integer elRecordTypeId);
	public String getElCoQ();
	public void setElCoQ(String elCoQ);
	public String getElVQ();
	public void setElVQ(String elVQ);
	public String getElRunNumber();
	public void setElRunNumber(String elRunNumber);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getElNh34Q();
	public void setElNh34Q(String elNh34Q);
	public String getElCationsComment();
	public void setElCationsComment(String elCationsComment);
	public String getElLiQ();
	public void setElLiQ(String elLiQ);
	public String getElWQ();
	public void setElWQ(String elWQ);
	public String getElTSulfideQ();
	public void setElTSulfideQ(String elTSulfideQ);
	public String getElFQ();
	public void setElFQ(String elFQ);
	public String getElSnQ();
	public void setElSnQ(String elSnQ);
	public Double getElTSulfide();
	public void setElTSulfide(Double elTSulfide);
	public Integer getElCationsUnitsId();
	public void setElCationsUnitsId(Integer elCationsUnitsId);
	public String getElIrQ();
	public void setElIrQ(String elIrQ);
	public String getElTaQ();
	public void setElTaQ(String elTaQ);
	public String getElNitriteQ();
	public void setElNitriteQ(String elNitriteQ);
	public String getElRhQ();
	public void setElRhQ(String elRhQ);
	public String getElFeQ();
	public void setElFeQ(String elFeQ);
	public String getElPbQ();
	public void setElPbQ(String elPbQ);
	public String getElInQ();
	public void setElInQ(String elInQ);
	public String getElCQ();
	public void setElCQ(String elCQ);
	public String getElAgQ();
	public void setElAgQ(String elAgQ);
	public String getElNo3Q();
	public void setElNo3Q(String elNo3Q);
	public String getElRequestIdVend();
	public void setElRequestIdVend(String elRequestIdVend);
	public String getElPtQ();
	public void setElPtQ(String elPtQ);
	public String getElUQ();
	public void setElUQ(String elUQ);
	public String getElSvcCode();
	public void setElSvcCode(String elSvcCode);
	public String getElNbQ();
	public void setElNbQ(String elNbQ);
	public Date getElCreatedDate();
	public void setElCreatedDate(Date elCreatedDate);
	public String getElSampleIdVend();
	public void setElSampleIdVend(String elSampleIdVend);
	public String getElSrQ();
	public void setElSrQ(String elSrQ);
	public String getElAuthor();
	public void setElAuthor(String elAuthor);
	public Date getElAcqDate();
	public void setElAcqDate(Date elAcqDate);
	public String getElSo4Q();
	public void setElSo4Q(String elSo4Q);
	public Integer getElAnionsUnitsId();
	public void setElAnionsUnitsId(Integer elAnionsUnitsId);
	public String getElSQ();
	public void setElSQ(String elSQ);
	public String getElBQ();
	public void setElBQ(String elBQ);
	public Date getElQcDate();
	public void setElQcDate(Date elQcDate);
	public String getElTeQ();
	public void setElTeQ(String elTeQ);
	public Double getElSo4();
	public void setElSo4(Double elSo4);
	public String getElSbQ();
	public void setElSbQ(String elSbQ);
	public Double getElPo4();
	public void setElPo4(Double elPo4);
	public String getElMnQ();
	public void setElMnQ(String elMnQ);
	public String getElPo4Q();
	public void setElPo4Q(String elPo4Q);
	public String getElUpdatedUser();
	public void setElUpdatedUser(String elUpdatedUser);
	public String getElQcUser();
	public void setElQcUser(String elQcUser);
	public String getElCrQ();
	public void setElCrQ(String elCrQ);
	public String getElNaQ();
	public void setElNaQ(String elNaQ);
	public String getElCaQ();
	public void setElCaQ(String elCaQ);
	public String getElMoQ();
	public void setElMoQ(String elMoQ);
	public String getElCreatedUser();
	public void setElCreatedUser(String elCreatedUser);
	public String getElAlQ();
	public void setElAlQ(String elAlQ);
	public Date getElUpdatedDate();
	public void setElUpdatedDate(Date elUpdatedDate);
	public String getElPQ();
	public void setElPQ(String elPQ);
}
