package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOLiqPh extends GTOAnalysisData {
	public String getPhAuthor();
	public void setPhAuthor(String phAuthor);
	public String getPhCreatedUser();
	public void setPhCreatedUser(String phCreatedUser);
	public Date getPhQcDate();
	public void setPhQcDate(Date phQcDate);
	public Integer getPhRecordTypeId();
	public void setPhRecordTypeId(Integer phRecordTypeId);
	public Integer getPhPk();
	public void setPhPk(Integer phPk);
	public Date getPhCreatedDate();
	public void setPhCreatedDate(Date phCreatedDate);
	public String getPhComment();
	public void setPhComment(String phComment);
	public String getPhQcUser();
	public void setPhQcUser(String phQcUser);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getPhSvcCode();
	public void setPhSvcCode(String phSvcCode);
	public String getPhRunNumber();
	public void setPhRunNumber(String phRunNumber);
	public Double getPhFieldTemp();
	public void setPhFieldTemp(Double phFieldTemp);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Date getPhFieldAcqDate();
	public void setPhFieldAcqDate(Date phFieldAcqDate);
	public Double getPhConf();
	public void setPhConf(Double phConf);
	public String getPhRequestIdVend();
	public void setPhRequestIdVend(String phRequestIdVend);
	public Double getPhTempDegassed();
	public void setPhTempDegassed(Double phTempDegassed);
	public Date getPhUpdatedDate();
	public void setPhUpdatedDate(Date phUpdatedDate);
	public String getPhDegassedValueQ();
	public void setPhDegassedValueQ(String phDegassedValueQ);
	public Date getPhAcqDate();
	public void setPhAcqDate(Date phAcqDate);
	public String getPhUpdatedUser();
	public void setPhUpdatedUser(String phUpdatedUser);
	public Double getPhFieldValue();
	public void setPhFieldValue(Double phFieldValue);
	public Integer getPhFieldTempUnitsId();
	public void setPhFieldTempUnitsId(Integer phFieldTempUnitsId);
	public String getPhLab();
	public void setPhLab(String phLab);
	public Integer getPhConfTypeId();
	public void setPhConfTypeId(Integer phConfTypeId);
	public Double getPhDegassedValue();
	public void setPhDegassedValue(Double phDegassedValue);
	public String getPhSampleIdVend();
	public void setPhSampleIdVend(String phSampleIdVend);
	public String getPhFieldValueQ();
	public void setPhFieldValueQ(String phFieldValueQ);
	public Integer getPhMethodId();
	public void setPhMethodId(Integer phMethodId);
	public Integer getPhFieldMethodId();
	public void setPhFieldMethodId(Integer phFieldMethodId);
	public Integer getPhTempDegassedUnitsId();
	public void setPhTempDegassedUnitsId(Integer phTempDegassedUnitsId);
	public Double getPhFieldT();
	public void setPhFieldT(Double phFieldT);
	public String getWaterPhLab();
	public void setWaterPhLab(String waterPhLab);
	public Double getPhValue();
	public void setPhValue(Double phValue);
	public Double getWaterPhFieldT();
	public void setWaterPhFieldT(Double waterPhFieldT);
	public String getWaterPhQc();
	public void setWaterPhQc(String waterPhQc);
	public String getWaterPhAuthor();
	public void setWaterPhAuthor(String waterPhAuthor);
	public Integer getWaterPhFieldMethod();
	public void setWaterPhFieldMethod(Integer waterPhFieldMethod);
	public Integer getPhMethod();
	public void setPhMethod(Integer phMethod);
	public String getPhQc();
	public void setPhQc(String phQc);
	public Double getWaterPhT();
	public void setWaterPhT(Double waterPhT);
	public Double getWaterPhConf();
	public void setWaterPhConf(Double waterPhConf);
	public Date getWaterPhDate();
	public void setWaterPhDate(Date waterPhDate);
	public Double getPhT();
	public void setPhT(Double phT);
	public Integer getPhFieldMethod();
	public void setPhFieldMethod(Integer phFieldMethod);
	public Integer getWaterPhMethod();
	public void setWaterPhMethod(Integer waterPhMethod);
	public Date getPhDate();
	public void setPhDate(Date phDate);
	public Double getWaterPhValue();
	public void setWaterPhValue(Double waterPhValue);
	public String getWaterPhComment();
	public void setWaterPhComment(String waterPhComment);
	public Double getWaterPhFieldValue();
	public void setWaterPhFieldValue(Double waterPhFieldValue);
}
