package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOLiqBtex extends GTOAnalysisData {
	public String getBtexQcUser();
	public void setBtexQcUser(String btexQcUser);
	public String getBtexMpxyleneQ();
	public void setBtexMpxyleneQ(String btexMpxyleneQ);
	public String getBtexCreatedUser();
	public void setBtexCreatedUser(String btexCreatedUser);
	public String getBtexComment();
	public void setBtexComment(String btexComment);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getBtexRunNumber();
	public void setBtexRunNumber(String btexRunNumber);
	public Date getBtexCreatedDate();
	public void setBtexCreatedDate(Date btexCreatedDate);
	public String getBtexOxyleneQ();
	public void setBtexOxyleneQ(String btexOxyleneQ);
	public Integer getBtexUnitsId();
	public void setBtexUnitsId(Integer btexUnitsId);
	public Double getBtexBenzene();
	public void setBtexBenzene(Double btexBenzene);
	public Date getBtexQcDate();
	public void setBtexQcDate(Date btexQcDate);
	public String getBtexLab();
	public void setBtexLab(String btexLab);
	public Integer getBtexConfTypeId();
	public void setBtexConfTypeId(Integer btexConfTypeId);
	public Double getBtexToluene();
	public void setBtexToluene(Double btexToluene);
	public String getBtexAuthor();
	public void setBtexAuthor(String btexAuthor);
	public Integer getBtexMethodId();
	public void setBtexMethodId(Integer btexMethodId);
	public String getBtexEthylbenzeneQ();
	public void setBtexEthylbenzeneQ(String btexEthylbenzeneQ);
	public String getBtexTolueneQ();
	public void setBtexTolueneQ(String btexTolueneQ);
	public Date getBtexUpdatedDate();
	public void setBtexUpdatedDate(Date btexUpdatedDate);
	public Integer getBtexRecordTypeId();
	public void setBtexRecordTypeId(Integer btexRecordTypeId);
	public String getBtexUpdatedUser();
	public void setBtexUpdatedUser(String btexUpdatedUser);
	public String getBtexSampleIdVend();
	public void setBtexSampleIdVend(String btexSampleIdVend);
	public Double getBtexTotal();
	public void setBtexTotal(Double btexTotal);
	public String getBtexRequestIdVend();
	public void setBtexRequestIdVend(String btexRequestIdVend);
	public Integer getBtexPk();
	public void setBtexPk(Integer btexPk);
	public Date getBtexAcqDate();
	public void setBtexAcqDate(Date btexAcqDate);
	public Double getBtexEthylbenzene();
	public void setBtexEthylbenzene(Double btexEthylbenzene);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getBtexMpxylene();
	public void setBtexMpxylene(Double btexMpxylene);
	public String getBtexSvcCode();
	public void setBtexSvcCode(String btexSvcCode);
	public String getBtexBenzeneQ();
	public void setBtexBenzeneQ(String btexBenzeneQ);
	public Double getBtexOxylene();
	public void setBtexOxylene(Double btexOxylene);
	public String getWaterBtexComment();
	public void setWaterBtexComment(String waterBtexComment);
	public Integer getBtexXyleneQ();
	public void setBtexXyleneQ(Integer btexXyleneQ);
	public Integer getBtexMethod();
	public void setBtexMethod(Integer btexMethod);
	public Integer getWaterBtexMethod();
	public void setWaterBtexMethod(Integer waterBtexMethod);
	public String getWaterBtexLab();
	public void setWaterBtexLab(String waterBtexLab);
	public Integer getWaterBtexBenzeneQ();
	public void setWaterBtexBenzeneQ(Integer waterBtexBenzeneQ);
	public Double getWaterBtexTotal();
	public void setWaterBtexTotal(Double waterBtexTotal);
	public Double getWaterBtexBenzene();
	public void setWaterBtexBenzene(Double waterBtexBenzene);
	public Double getWaterBtexXylene();
	public void setWaterBtexXylene(Double waterBtexXylene);
	public String getBtexQc();
	public void setBtexQc(String btexQc);
	public String getWaterBtexAuthor();
	public void setWaterBtexAuthor(String waterBtexAuthor);
	public Double getBtexXylene();
	public void setBtexXylene(Double btexXylene);
	public Integer getBtexUnits();
	public void setBtexUnits(Integer btexUnits);
	public Double getWaterBtexToluene();
	public void setWaterBtexToluene(Double waterBtexToluene);
	public Integer getWaterBtexUnits();
	public void setWaterBtexUnits(Integer waterBtexUnits);
	public Double getWaterBtexEthene();
	public void setWaterBtexEthene(Double waterBtexEthene);
	public Date getBtexDate();
	public void setBtexDate(Date btexDate);
	public String getWaterBtexQc();
	public void setWaterBtexQc(String waterBtexQc);
	public Integer getWaterBtexXyleneQ();
	public void setWaterBtexXyleneQ(Integer waterBtexXyleneQ);
	public Double getBtexEthene();
	public void setBtexEthene(Double btexEthene);
	public Date getWaterBtexDate();
	public void setWaterBtexDate(Date waterBtexDate);
	public Integer getBtexEtheneQ();
	public void setBtexEtheneQ(Integer btexEtheneQ);
	public Integer getWaterBtexEtheneQ();
	public void setWaterBtexEtheneQ(Integer waterBtexEtheneQ);
	public Integer getWaterBtexTolueneQ();
	public void setWaterBtexTolueneQ(Integer waterBtexTolueneQ);
}
