package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOLiqTds extends GTOAnalysisData {
	public Integer getTdsMethodId();
	public void setTdsMethodId(Integer tdsMethodId);
	public Double getTdsValue();
	public void setTdsValue(Double tdsValue);
	public Integer getTssMethodId();
	public void setTssMethodId(Integer tssMethodId);
	public Date getTdsCreatedDate();
	public void setTdsCreatedDate(Date tdsCreatedDate);
	public Double getVssValue();
	public void setVssValue(Double vssValue);
	public Double getTssConf();
	public void setTssConf(Double tssConf);
	public Integer getTdsTempUnitsId();
	public void setTdsTempUnitsId(Integer tdsTempUnitsId);
	public Double getTssValue();
	public void setTssValue(Double tssValue);
	public Integer getVssUnitsId();
	public void setVssUnitsId(Integer vssUnitsId);
	public Integer getTssUnitsId();
	public void setTssUnitsId(Integer tssUnitsId);
	public Integer getTssTempUnitsId();
	public void setTssTempUnitsId(Integer tssTempUnitsId);
	public Integer getTdsConfTypeId();
	public void setTdsConfTypeId(Integer tdsConfTypeId);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Integer getTdsCalcUnitsId();
	public void setTdsCalcUnitsId(Integer tdsCalcUnitsId);
	public Double getTdsTemp();
	public void setTdsTemp(Double tdsTemp);
	public Double getTssTemp();
	public void setTssTemp(Double tssTemp);
	public String getTdsComment();
	public void setTdsComment(String tdsComment);
	public Integer getVssMethodId();
	public void setVssMethodId(Integer vssMethodId);
	public String getTdsRequestIdVend();
	public void setTdsRequestIdVend(String tdsRequestIdVend);
	public String getTdsSvcCode();
	public void setTdsSvcCode(String tdsSvcCode);
	public Integer getTdsUnitsId();
	public void setTdsUnitsId(Integer tdsUnitsId);
	public Integer getVssTempUnitsId();
	public void setVssTempUnitsId(Integer vssTempUnitsId);
	public Double getTdsConf();
	public void setTdsConf(Double tdsConf);
	public Date getTdsUpdatedDate();
	public void setTdsUpdatedDate(Date tdsUpdatedDate);
	public String getTdsRunNumber();
	public void setTdsRunNumber(String tdsRunNumber);
	public String getTdsQ();
	public void setTdsQ(String tdsQ);
	public Double getVssTemp();
	public void setVssTemp(Double vssTemp);
	public String getVssQ();
	public void setVssQ(String vssQ);
	public String getTdsUpdatedUser();
	public void setTdsUpdatedUser(String tdsUpdatedUser);
	public Integer getTdsPk();
	public void setTdsPk(Integer tdsPk);
	public Double getTdsCalc();
	public void setTdsCalc(Double tdsCalc);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getTssQ();
	public void setTssQ(String tssQ);
	public String getTdsAuthor();
	public void setTdsAuthor(String tdsAuthor);
	public Integer getTdsRecordTypeId();
	public void setTdsRecordTypeId(Integer tdsRecordTypeId);
	public String getTdsQcUser();
	public void setTdsQcUser(String tdsQcUser);
	public Date getTdsQcDate();
	public void setTdsQcDate(Date tdsQcDate);
	public String getTdsSampleIdVend();
	public void setTdsSampleIdVend(String tdsSampleIdVend);
	public Date getTdsAcqDate();
	public void setTdsAcqDate(Date tdsAcqDate);
	public String getTdsLab();
	public void setTdsLab(String tdsLab);
	public Double getVssConf();
	public void setVssConf(Double vssConf);
	public String getTdsCreatedUser();
	public void setTdsCreatedUser(String tdsCreatedUser);
	public String getWaterVssQc();
	public void setWaterVssQc(String waterVssQc);
	public Double getWaterVssConf();
	public void setWaterVssConf(Double waterVssConf);
	public Integer getWaterTdsUnits();
	public void setWaterTdsUnits(Integer waterTdsUnits);
	public Integer getTdsUnits();
	public void setTdsUnits(Integer tdsUnits);
	public Date getTdsDate();
	public void setTdsDate(Date tdsDate);
	public String getWaterTdsAuthor();
	public void setWaterTdsAuthor(String waterTdsAuthor);
	public Double getWaterTdsValue();
	public void setWaterTdsValue(Double waterTdsValue);
	public Date getWaterTdsDate();
	public void setWaterTdsDate(Date waterTdsDate);
	public String getTssQc();
	public void setTssQc(String tssQc);
	public Double getWaterTdsConf();
	public void setWaterTdsConf(Double waterTdsConf);
	public String getTdsQc();
	public void setTdsQc(String tdsQc);
	public Integer getWaterTdsMethod();
	public void setWaterTdsMethod(Integer waterTdsMethod);
	public Integer getTdsMethod();
	public void setTdsMethod(Integer tdsMethod);
	public String getVssQc();
	public void setVssQc(String vssQc);
	public Double getWaterTssValue();
	public void setWaterTssValue(Double waterTssValue);
	public Double getWaterTssConf();
	public void setWaterTssConf(Double waterTssConf);
	public Double getWaterVssValue();
	public void setWaterVssValue(Double waterVssValue);
	public String getWaterTdsComment();
	public void setWaterTdsComment(String waterTdsComment);
	public String getWaterTdsQc();
	public void setWaterTdsQc(String waterTdsQc);
	public String getWaterTssQc();
	public void setWaterTssQc(String waterTssQc);
	public String getWaterTdsLab();
	public void setWaterTdsLab(String waterTdsLab);
}
