package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOLiqNpd extends GTOAnalysisData {
	public String getNpd9ePhenanthQ();
	public void setNpd9ePhenanthQ(String npd9ePhenanthQ);
	public Double getNpd126tmPhenanth();
	public void setNpd126tmPhenanth(Double npd126tmPhenanth);
	public Double getNpd26dmNapth();
	public void setNpd26dmNapth(Double npd26dmNapth);
	public String getNpdCreatedUser();
	public void setNpdCreatedUser(String npdCreatedUser);
	public String getNpdC3DbthiophQ();
	public void setNpdC3DbthiophQ(String npdC3DbthiophQ);
	public Date getNpdCreatedDate();
	public void setNpdCreatedDate(Date npdCreatedDate);
	public Double getNpd9mnapth();
	public void setNpd9mnapth(Double npd9mnapth);
	public String getNpdC2PhenanthQ();
	public void setNpdC2PhenanthQ(String npdC2PhenanthQ);
	public Double getNpdC1Nath();
	public void setNpdC1Nath(Double npdC1Nath);
	public Double getNpd4pDbthioph();
	public void setNpd4pDbthioph(Double npd4pDbthioph);
	public Integer getNpdConfTypeId();
	public void setNpdConfTypeId(Integer npdConfTypeId);
	public Double getNpdC3Nath();
	public void setNpdC3Nath(Double npdC3Nath);
	public Double getNpdC3Phenanth();
	public void setNpdC3Phenanth(Double npdC3Phenanth);
	public Date getNpdQcDate();
	public void setNpdQcDate(Date npdQcDate);
	public String getNpdAuthor();
	public void setNpdAuthor(String npdAuthor);
	public Double getNpd1mnapth();
	public void setNpd1mnapth(Double npd1mnapth);
	public String getNpd4pDbthiophQ();
	public void setNpd4pDbthiophQ(String npd4pDbthiophQ);
	public String getNpdQcUser();
	public void setNpdQcUser(String npdQcUser);
	public String getNpd4eDbthiophQ();
	public void setNpd4eDbthiophQ(String npd4eDbthiophQ);
	public String getNpdNapthQ();
	public void setNpdNapthQ(String npdNapthQ);
	public Double getNpdDbthioph();
	public void setNpdDbthioph(Double npdDbthioph);
	public Double getNpd2mnapth();
	public void setNpd2mnapth(Double npd2mnapth);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getNpd26dmNapthQ();
	public void setNpd26dmNapthQ(String npd26dmNapthQ);
	public Date getNpdAcqDate();
	public void setNpdAcqDate(Date npdAcqDate);
	public String getNpdUpdatedUser();
	public void setNpdUpdatedUser(String npdUpdatedUser);
	public String getNpd9mnapthQ();
	public void setNpd9mnapthQ(String npd9mnapthQ);
	public String getNpdSampleIdVend();
	public void setNpdSampleIdVend(String npdSampleIdVend);
	public String getNpdC1NathQ();
	public void setNpdC1NathQ(String npdC1NathQ);
	public String getNpdC1PhenanthQ();
	public void setNpdC1PhenanthQ(String npdC1PhenanthQ);
	public Date getNpdUpdatedDate();
	public void setNpdUpdatedDate(Date npdUpdatedDate);
	public Double getNpdC3Dbthioph();
	public void setNpdC3Dbthioph(Double npdC3Dbthioph);
	public String getNpdC2DbthiophQ();
	public void setNpdC2DbthiophQ(String npdC2DbthiophQ);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getNpdPhenanthQ();
	public void setNpdPhenanthQ(String npdPhenanthQ);
	public Double getNpd2ipNapth();
	public void setNpd2ipNapth(Double npd2ipNapth);
	public Double getNpdC2Nath();
	public void setNpdC2Nath(Double npdC2Nath);
	public Double getNpdC1Dbthioph();
	public void setNpdC1Dbthioph(Double npdC1Dbthioph);
	public String getNpdC2NathQ();
	public void setNpdC2NathQ(String npdC2NathQ);
	public Double getNpd4eDbthioph();
	public void setNpd4eDbthioph(Double npd4eDbthioph);
	public String getNpdC3NathQ();
	public void setNpdC3NathQ(String npdC3NathQ);
	public String getNpdComment();
	public void setNpdComment(String npdComment);
	public String getNpdRequestIdVend();
	public void setNpdRequestIdVend(String npdRequestIdVend);
	public Double getNpd9ePhenanth();
	public void setNpd9ePhenanth(Double npd9ePhenanth);
	public Double getNpdPhenanth();
	public void setNpdPhenanth(Double npdPhenanth);
	public Double getNpdC1Phenanth();
	public void setNpdC1Phenanth(Double npdC1Phenanth);
	public String getNpd4mDbthiophQ();
	public void setNpd4mDbthiophQ(String npd4mDbthiophQ);
	public Integer getNpdUnitsId();
	public void setNpdUnitsId(Integer npdUnitsId);
	public String getNpd2ipNapthQ();
	public void setNpd2ipNapthQ(String npd2ipNapthQ);
	public Double getNpdNapth();
	public void setNpdNapth(Double npdNapth);
	public String getNpdSvcCode();
	public void setNpdSvcCode(String npdSvcCode);
	public Double getNpdC2Phenanth();
	public void setNpdC2Phenanth(Double npdC2Phenanth);
	public String getNpd1mnapthQ();
	public void setNpd1mnapthQ(String npd1mnapthQ);
	public Integer getNpdMethodId();
	public void setNpdMethodId(Integer npdMethodId);
	public Integer getNpdRecordTypeId();
	public void setNpdRecordTypeId(Integer npdRecordTypeId);
	public String getNpd2mnapthQ();
	public void setNpd2mnapthQ(String npd2mnapthQ);
	public Integer getNpdLab();
	public void setNpdLab(Integer npdLab);
	public Integer getNpdPk();
	public void setNpdPk(Integer npdPk);
	public String getNpdC1DbthiophQ();
	public void setNpdC1DbthiophQ(String npdC1DbthiophQ);
	public String getNpdC3PhenanthQ();
	public void setNpdC3PhenanthQ(String npdC3PhenanthQ);
	public String getNpdRunNumber();
	public void setNpdRunNumber(String npdRunNumber);
	public Double getNpd4mDbthioph();
	public void setNpd4mDbthioph(Double npd4mDbthioph);
	public String getNpd126tmPhenanthQ();
	public void setNpd126tmPhenanthQ(String npd126tmPhenanthQ);
	public String getNpdDbthiophQ();
	public void setNpdDbthiophQ(String npdDbthiophQ);
	public Double getNpdC2Dbthioph();
	public void setNpdC2Dbthioph(Double npdC2Dbthioph);
}
