package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOLiqAlkalinity extends GTOAnalysisData {
	public String getAlkSvcCode();
	public void setAlkSvcCode(String alkSvcCode);
	public String getAlkRunNumber();
	public void setAlkRunNumber(String alkRunNumber);
	public Double getAlkPheno();
	public void setAlkPheno(Double alkPheno);
	public Integer getAlkRecordTypeId();
	public void setAlkRecordTypeId(Integer alkRecordTypeId);
	public Double getAlkAlkalinity();
	public void setAlkAlkalinity(Double alkAlkalinity);
	public String getAlkPhenoQ();
	public void setAlkPhenoQ(String alkPhenoQ);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getAlkOrganicAcidQ();
	public void setAlkOrganicAcidQ(String alkOrganicAcidQ);
	public Integer getAlkCo3UnitsId();
	public void setAlkCo3UnitsId(Integer alkCo3UnitsId);
	public String getAlkAlkalinityQ();
	public void setAlkAlkalinityQ(String alkAlkalinityQ);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getAlkCo3();
	public void setAlkCo3(Double alkCo3);
	public Integer getAlkAcidUnitsId();
	public void setAlkAcidUnitsId(Integer alkAcidUnitsId);
	public Date getAlkCreatedDate();
	public void setAlkCreatedDate(Date alkCreatedDate);
	public String getAlkHco3Q();
	public void setAlkHco3Q(String alkHco3Q);
	public String getAlkCreatedUser();
	public void setAlkCreatedUser(String alkCreatedUser);
	public Double getAlkOrganicAcid();
	public void setAlkOrganicAcid(Double alkOrganicAcid);
	public Integer getAlkCarbMethodId();
	public void setAlkCarbMethodId(Integer alkCarbMethodId);
	public String getAlkCarbQ();
	public void setAlkCarbQ(String alkCarbQ);
	public Integer getAlkCarbUnitsId();
	public void setAlkCarbUnitsId(Integer alkCarbUnitsId);
	public Integer getAlkTotUnitsId();
	public void setAlkTotUnitsId(Integer alkTotUnitsId);
	public String getAlkRequestIdVend();
	public void setAlkRequestIdVend(String alkRequestIdVend);
	public String getAlkSampleIdVend();
	public void setAlkSampleIdVend(String alkSampleIdVend);
	public Integer getAlkMethodId();
	public void setAlkMethodId(Integer alkMethodId);
	public Double getAlkCarbonic();
	public void setAlkCarbonic(Double alkCarbonic);
	public String getAlkCarbonicQ();
	public void setAlkCarbonicQ(String alkCarbonicQ);
	public Double getAlkCarbonate();
	public void setAlkCarbonate(Double alkCarbonate);
	public String getAlkUpdatedUser();
	public void setAlkUpdatedUser(String alkUpdatedUser);
	public Integer getAlkLab();
	public void setAlkLab(Integer alkLab);
	public Date getAlkUpdatedDate();
	public void setAlkUpdatedDate(Date alkUpdatedDate);
	public Integer getAlkHco3UnitsId();
	public void setAlkHco3UnitsId(Integer alkHco3UnitsId);
	public String getAlkAuthor();
	public void setAlkAuthor(String alkAuthor);
	public String getAlkComment();
	public void setAlkComment(String alkComment);
	public Date getAlkQcDate();
	public void setAlkQcDate(Date alkQcDate);
	public Integer getAlkPk();
	public void setAlkPk(Integer alkPk);
	public Double getAlkHco3();
	public void setAlkHco3(Double alkHco3);
	public Date getAlkAcqDate();
	public void setAlkAcqDate(Date alkAcqDate);
	public Double getAlkOh();
	public void setAlkOh(Double alkOh);
	public Integer getAlkCarbonicUnitsId();
	public void setAlkCarbonicUnitsId(Integer alkCarbonicUnitsId);
	public String getAlkQcUser();
	public void setAlkQcUser(String alkQcUser);
	public String getAlkOhQ();
	public void setAlkOhQ(String alkOhQ);
	public Integer getAlkPhenoUnitsId();
	public void setAlkPhenoUnitsId(Integer alkPhenoUnitsId);
	public String getAlkCo3Q();
	public void setAlkCo3Q(String alkCo3Q);
	public Integer getAlkOhUnitsId();
	public void setAlkOhUnitsId(Integer alkOhUnitsId);
	public Integer getAlkConfTypeId();
	public void setAlkConfTypeId(Integer alkConfTypeId);
}
