package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOMsAlkylbenzenes extends GTOAnalysisData {
	public Integer getAbOxyl105();
	public void setAbOxyl105(Integer abOxyl105);
	public Integer getAbOxyl106();
	public void setAbOxyl106(Integer abOxyl106);
	public Integer getAb1m2ebz120();
	public void setAb1m2ebz120(Integer ab1m2ebz120);
	public Integer getAb1m2ebz105();
	public void setAb1m2ebz105(Integer ab1m2ebz105);
	public String getAbComment();
	public void setAbComment(String abComment);
	public Integer getAbPxyl105();
	public void setAbPxyl105(Integer abPxyl105);
	public Integer getAbPxyl106();
	public void setAbPxyl106(Integer abPxyl106);
	public Integer getAbNpbz105();
	public void setAbNpbz105(Integer abNpbz105);
	public String getAbQcUser();
	public void setAbQcUser(String abQcUser);
	public Integer getAbNpbz120();
	public void setAbNpbz120(Integer abNpbz120);
	public Integer getAbMxyl106();
	public void setAbMxyl106(Integer abMxyl106);
	public Integer getAbMxyl105();
	public void setAbMxyl105(Integer abMxyl105);
	public Integer getAb1m3ebz105();
	public void setAb1m3ebz105(Integer ab1m3ebz105);
	public Integer getAb1m3ebz120();
	public void setAb1m3ebz120(Integer ab1m3ebz120);
	public Integer getAbEbz91();
	public void setAbEbz91(Integer abEbz91);
	public Integer getAb135tmbz105();
	public void setAb135tmbz105(Integer ab135tmbz105);
	public Integer getAb135tmbz120();
	public void setAb135tmbz120(Integer ab135tmbz120);
	public Date getAbQcDate();
	public void setAbQcDate(Date abQcDate);
	public String getAbAuthor();
	public void setAbAuthor(String abAuthor);
	public String getAbMethod();
	public void setAbMethod(String abMethod);
	public Integer getAbNpbz91();
	public void setAbNpbz91(Integer abNpbz91);
	public String getAbLab();
	public void setAbLab(String abLab);
	public Integer getAb124tmbz120();
	public void setAb124tmbz120(Integer ab124tmbz120);
	public Integer getAb124tmbz105();
	public void setAb124tmbz105(Integer ab124tmbz105);
	public Integer getAb123tmbz120();
	public void setAb123tmbz120(Integer ab123tmbz120);
	public Integer getAb123tmbz105();
	public void setAb123tmbz105(Integer ab123tmbz105);
	public Date getAbAcqDate();
	public void setAbAcqDate(Date abAcqDate);
	public Integer getAbOxyl91();
	public void setAbOxyl91(Integer abOxyl91);
	public String getAbJobId();
	public void setAbJobId(String abJobId);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Date getAbDate();
	public void setAbDate(Date abDate);
	public String getAbIqmCode();
	public void setAbIqmCode(String abIqmCode);
	public String getAbQc();
	public void setAbQc(String abQc);
	public String getAbSampleIdVend();
	public void setAbSampleIdVend(String abSampleIdVend);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Integer getAbPxyl91();
	public void setAbPxyl91(Integer abPxyl91);
	public Date getAbLastUpdate();
	public void setAbLastUpdate(Date abLastUpdate);
	public Integer getAbStdPpm();
	public void setAbStdPpm(Integer abStdPpm);
	public Integer getAb1m4ebz105();
	public void setAb1m4ebz105(Integer ab1m4ebz105);
	public String getAbDataType();
	public void setAbDataType(String abDataType);
	public Integer getAb1m4ebz120();
	public void setAb1m4ebz120(Integer ab1m4ebz120);
	public Double getAbSampAmt();
	public void setAbSampAmt(Double abSampAmt);
	public Integer getAbStdCnts();
	public void setAbStdCnts(Integer abStdCnts);
	public Integer getAbIpbz120();
	public void setAbIpbz120(Integer abIpbz120);
	public String getAbRunNumber();
	public void setAbRunNumber(String abRunNumber);
	public Integer getAbEbz106();
	public void setAbEbz106(Integer abEbz106);
	public Integer getAbEbz105();
	public void setAbEbz105(Integer abEbz105);
	public String getAbSvcCode();
	public void setAbSvcCode(String abSvcCode);
	public Integer getAbMxyl91();
	public void setAbMxyl91(Integer abMxyl91);
	public Integer getAbIpbz105();
	public void setAbIpbz105(Integer abIpbz105);
	public Integer getAbIpbz106();
	public void setAbIpbz106(Integer abIpbz106);
}
