package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOMsMs extends GTOAnalysisData {
	public Date getMsmsAcqDate();
	public void setMsmsAcqDate(Date msmsAcqDate);
	public Integer getMsmsBicadinene();
	public void setMsmsBicadinene(Integer msmsBicadinene);
	public String getMsmsRunNumber();
	public void setMsmsRunNumber(String msmsRunNumber);
	public Integer getMsmsC28unk9();
	public void setMsmsC28unk9(Integer msmsC28unk9);
	public String getMsmsComment();
	public void setMsmsComment(String msmsComment);
	public Integer getMsmsH29ts();
	public void setMsmsH29ts(Integer msmsH29ts);
	public Integer getMsmsD293mbasa();
	public void setMsmsD293mbasa(Integer msmsD293mbasa);
	public Integer getMsmsD293mbarb();
	public void setMsmsD293mbarb(Integer msmsD293mbarb);
	public Integer getMsmsD293mbara();
	public void setMsmsD293mbara(Integer msmsD293mbara);
	public Integer getMsmsH33abr();
	public void setMsmsH33abr(Integer msmsH33abr);
	public Integer getMsmsH33abs();
	public void setMsmsH33abs(Integer msmsH33abs);
	public Integer getMsmsD293mbasb();
	public void setMsmsD293mbasb(Integer msmsD293mbasb);
	public Integer getMsmsS294maaasb();
	public void setMsmsS294maaasb(Integer msmsS294maaasb);
	public Integer getMsmsS294maaasa();
	public void setMsmsS294maaasa(Integer msmsS294maaasa);
	public Integer getMsmsNorpreg12();
	public void setMsmsNorpreg12(Integer msmsNorpreg12);
	public Integer getMsmsNorpreg11();
	public void setMsmsNorpreg11(Integer msmsNorpreg11);
	public Integer getMsmsNorpreg10();
	public void setMsmsNorpreg10(Integer msmsNorpreg10);
	public Integer getMsmsH29ba();
	public void setMsmsH29ba(Integer msmsH29ba);
	public Integer getMsmsS29abbr();
	public void setMsmsS29abbr(Integer msmsS29abbr);
	public Integer getMsmsS29abbs();
	public void setMsmsS29abbs(Integer msmsS29abbs);
	public Integer getMsmsD30npbasb();
	public void setMsmsD30npbasb(Integer msmsD30npbasb);
	public Integer getMsmsD30npbasa();
	public void setMsmsD30npbasa(Integer msmsD30npbasa);
	public Integer getMsmsH29ab();
	public void setMsmsH29ab(Integer msmsH29ab);
	public Integer getMsmsDs4ars20r();
	public void setMsmsDs4ars20r(Integer msmsDs4ars20r);
	public Integer getMsmsOl3b543abeo();
	public void setMsmsOl3b543abeo(Integer msmsOl3b543abeo);
	public Integer getMsmsD283mbas();
	public void setMsmsD283mbas(Integer msmsD283mbas);
	public Integer getMsmsD283mbar();
	public void setMsmsD283mbar(Integer msmsD283mbar);
	public Integer getMsmsS26n27aaar();
	public void setMsmsS26n27aaar(Integer msmsS26n27aaar);
	public Integer getMsmsS26n27aaas();
	public void setMsmsS26n27aaas(Integer msmsS26n27aaas);
	public Integer getMsmsDesatarax();
	public void setMsmsDesatarax(Integer msmsDesatarax);
	public String getMsmsMethod();
	public void setMsmsMethod(String msmsMethod);
	public String getMsmsQcUser();
	public void setMsmsQcUser(String msmsQcUser);
	public Integer getMsmsOl3a5b543abeo();
	public void setMsmsOl3a5b543abeo(Integer msmsOl3a5b543abeo);
	public Integer getMsmsS29aaar();
	public void setMsmsS29aaar(Integer msmsS29aaar);
	public Integer getMsmsS29aaas();
	public void setMsmsS29aaas(Integer msmsS29aaas);
	public Date getMsmsLastUpdate();
	public void setMsmsLastUpdate(Date msmsLastUpdate);
	public Integer getMsmsC30unkt2();
	public void setMsmsC30unkt2(Integer msmsC30unkt2);
	public Integer getMsmsDs4arr20r();
	public void setMsmsDs4arr20r(Integer msmsDs4arr20r);
	public Integer getMsmsS26n27abbr();
	public void setMsmsS26n27abbr(Integer msmsS26n27abbr);
	public Integer getMsmsS26n27abbs();
	public void setMsmsS26n27abbs(Integer msmsS26n27abbs);
	public Integer getMsmsPp1();
	public void setMsmsPp1(Integer msmsPp1);
	public Integer getMsmsDh33a();
	public void setMsmsDh33a(Integer msmsDh33a);
	public Integer getMsmsDh33b();
	public void setMsmsDh33b(Integer msmsDh33b);
	public Integer getMsmsOleanoid15a();
	public void setMsmsOleanoid15a(Integer msmsOleanoid15a);
	public Integer getMsmsDh32a();
	public void setMsmsDh32a(Integer msmsDh32a);
	public Integer getMsmsDh32b();
	public void setMsmsDh32b(Integer msmsDh32b);
	public Integer getMsmsDh34b();
	public void setMsmsDh34b(Integer msmsDh34b);
	public Integer getMsmsDh34a();
	public void setMsmsDh34a(Integer msmsDh34a);
	public String getMsmsJobId();
	public void setMsmsJobId(String msmsJobId);
	public Date getMsmsQcDate();
	public void setMsmsQcDate(Date msmsQcDate);
	public Integer getMsmsDh31a();
	public void setMsmsDh31a(Integer msmsDh31a);
	public Integer getMsmsDh31b();
	public void setMsmsDh31b(Integer msmsDh31b);
	public Integer getMsmsD28abrb();
	public void setMsmsD28abrb(Integer msmsD28abrb);
	public Integer getMsmsD28abra();
	public void setMsmsD28abra(Integer msmsD28abra);
	public Integer getMsmsS284mabbs();
	public void setMsmsS284mabbs(Integer msmsS284mabbs);
	public Integer getMsmsS284mabbr();
	public void setMsmsS284mabbr(Integer msmsS284mabbr);
	public Integer getMsmsC30unk12();
	public void setMsmsC30unk12(Integer msmsC30unk12);
	public Integer getMsmsS303pabbs();
	public void setMsmsS303pabbs(Integer msmsS303pabbs);
	public Integer getMsmsB30t1();
	public void setMsmsB30t1(Integer msmsB30t1);
	public String getMsmsSvcCode();
	public void setMsmsSvcCode(String msmsSvcCode);
	public Integer getMsmsD284mbas();
	public void setMsmsD284mbas(Integer msmsD284mbas);
	public Integer getMsmsD284mbar();
	public void setMsmsD284mbar(Integer msmsD284mbar);
	public Integer getMsmsH32abs();
	public void setMsmsH32abs(Integer msmsH32abs);
	public Integer getMsmsH32abr();
	public void setMsmsH32abr(Integer msmsH32abr);
	public Integer getMsmsS26n21();
	public void setMsmsS26n21(Integer msmsS26n21);
	public Integer getMsmsOl1318ene();
	public void setMsmsOl1318ene(Integer msmsOl1318ene);
	public Integer getMsmsS30ipabbr();
	public void setMsmsS30ipabbr(Integer msmsS30ipabbr);
	public Integer getMsmsS27abbr();
	public void setMsmsS27abbr(Integer msmsS27abbr);
	public Integer getMsmsS27abbs();
	public void setMsmsS27abbs(Integer msmsS27abbs);
	public Integer getMsmsH30n30();
	public void setMsmsH30n30(Integer msmsH30n30);
	public Integer getMsmsTriterp18();
	public void setMsmsTriterp18(Integer msmsTriterp18);
	public Integer getMsmsTriterp14();
	public void setMsmsTriterp14(Integer msmsTriterp14);
	public Integer getMsmsS293maaasb();
	public void setMsmsS293maaasb(Integer msmsS293maaasb);
	public Integer getMsmsDc29unk27();
	public void setMsmsDc29unk27(Integer msmsDc29unk27);
	public Integer getMsmsDc29unk28();
	public void setMsmsDc29unk28(Integer msmsDc29unk28);
	public Integer getMsmsD30npabsa();
	public void setMsmsD30npabsa(Integer msmsD30npabsa);
	public Integer getMsmsD30npabsb();
	public void setMsmsD30npabsb(Integer msmsD30npabsb);
	public Integer getMsmsS27aaar();
	public void setMsmsS27aaar(Integer msmsS27aaar);
	public Integer getMsmsS27aaas();
	public void setMsmsS27aaas(Integer msmsS27aaas);
	public Integer getMsmsXs29aaar();
	public void setMsmsXs29aaar(Integer msmsXs29aaar);
	public Integer getMsmsS294mabbs3maaar();
	public void setMsmsS294mabbs3maaar(Integer msmsS294mabbs3maaar);
	public Integer getMsmsH31abs();
	public void setMsmsH31abs(Integer msmsH31abs);
	public Integer getMsmsH31abr();
	public void setMsmsH31abr(Integer msmsH31abr);
	public Integer getMsmsS293maaasa4abrb();
	public void setMsmsS293maaasa4abrb(Integer msmsS293maaasa4abrb);
	public Integer getMsmsD26n27bas();
	public void setMsmsD26n27bas(Integer msmsD26n27bas);
	public Integer getMsmsD26n27bar();
	public void setMsmsD26n27bar(Integer msmsD26n27bar);
	public Integer getMsmsUnkH();
	public void setMsmsUnkH(Integer msmsUnkH);
	public Integer getMsmsS304mabbr();
	public void setMsmsS304mabbr(Integer msmsS304mabbr);
	public Date getMsmsDate();
	public void setMsmsDate(Date msmsDate);
	public Integer getMsmsS28aaasb();
	public void setMsmsS28aaasb(Integer msmsS28aaasb);
	public Integer getMsmsS28aaasa();
	public void setMsmsS28aaasa(Integer msmsS28aaasa);
	public Integer getMsmsDs4ass20r();
	public void setMsmsDs4ass20r(Integer msmsDs4ass20r);
	public Integer getMsmsH27bb();
	public void setMsmsH27bb(Integer msmsH27bb);
	public Integer getMsmsD28bara();
	public void setMsmsD28bara(Integer msmsD28bara);
	public Integer getMsmsD28barb();
	public void setMsmsD28barb(Integer msmsD28barb);
	public Integer getMsmsD28basb();
	public void setMsmsD28basb(Integer msmsD28basb);
	public Integer getMsmsD28basa();
	public void setMsmsD28basa(Integer msmsD28basa);
	public Integer getMsmsD26n27abr();
	public void setMsmsD26n27abr(Integer msmsD26n27abr);
	public Integer getMsmsD26n27abs();
	public void setMsmsD26n27abs(Integer msmsD26n27abs);
	public Integer getMsmsS304maaar();
	public void setMsmsS304maaar(Integer msmsS304maaar);
	public Integer getMsmsS304maaas();
	public void setMsmsS304maaas(Integer msmsS304maaas);
	public Integer getMsmsD27abs();
	public void setMsmsD27abs(Integer msmsD27abs);
	public Integer getMsmsD27abr();
	public void setMsmsD27abr(Integer msmsD27abr);
	public Integer getMsmsS28aaar();
	public void setMsmsS28aaar(Integer msmsS28aaar);
	public Integer getMsmsDc28unk3();
	public void setMsmsDc28unk3(Integer msmsDc28unk3);
	public String getMsmsSampleIdVend();
	public void setMsmsSampleIdVend(String msmsSampleIdVend);
	public Integer getMsmsS283mabbr();
	public void setMsmsS283mabbr(Integer msmsS283mabbr);
	public Integer getMsmsS283mabbs();
	public void setMsmsS283mabbs(Integer msmsS283mabbs);
	public Integer getMsmsXs28aaar();
	public void setMsmsXs28aaar(Integer msmsXs28aaar);
	public Integer getMsmsDs4asr20r();
	public void setMsmsDs4asr20r(Integer msmsDs4asr20r);
	public Integer getMsmsS30npaaas();
	public void setMsmsS30npaaas(Integer msmsS30npaaas);
	public Integer getMsmsS30npaaar();
	public void setMsmsS30npaaar(Integer msmsS30npaaar);
	public Integer getMsmsBotyrococcane();
	public void setMsmsBotyrococcane(Integer msmsBotyrococcane);
	public String getMsmsIqmCode();
	public void setMsmsIqmCode(String msmsIqmCode);
	public Integer getMsmsD27bar();
	public void setMsmsD27bar(Integer msmsD27bar);
	public Integer getMsmsD27bas();
	public void setMsmsD27bas(Integer msmsD27bas);
	public Integer getMsmsD30npbar();
	public void setMsmsD30npbar(Integer msmsD30npbar);
	public Integer getMsmsPp2S303pabbr();
	public void setMsmsPp2S303pabbr(Integer msmsPp2S303pabbr);
	public Integer getMsmsS28n21();
	public void setMsmsS28n21(Integer msmsS28n21);
	public Integer getMsmsIstd();
	public void setMsmsIstd(Integer msmsIstd);
	public Integer getMsmsS293mabbs();
	public void setMsmsS293mabbs(Integer msmsS293mabbs);
	public Integer getMsmsS293mabbr();
	public void setMsmsS293mabbr(Integer msmsS293mabbr);
	public Integer getMsmsDesehop();
	public void setMsmsDesehop(Integer msmsDesehop);
	public Integer getMsmsS30npabbs();
	public void setMsmsS30npabbs(Integer msmsS30npabbs);
	public Integer getMsmsS30npabbr();
	public void setMsmsS30npabbr(Integer msmsS30npabbr);
	public Integer getMsmsH28n2930();
	public void setMsmsH28n2930(Integer msmsH28n2930);
	public Integer getMsmsS302maaas();
	public void setMsmsS302maaas(Integer msmsS302maaas);
	public Integer getMsmsDesaol();
	public void setMsmsDesaol(Integer msmsDesaol);
	public String getMsmsAuthor();
	public void setMsmsAuthor(String msmsAuthor);
	public Integer getMsmsH28n2830();
	public void setMsmsH28n2830(Integer msmsH28n2830);
	public Integer getMsmsD28abs();
	public void setMsmsD28abs(Integer msmsD28abs);
	public Integer getMsmsS28baar();
	public void setMsmsS28baar(Integer msmsS28baar);
	public Integer getMsmsD294mabra();
	public void setMsmsD294mabra(Integer msmsD294mabra);
	public Integer getMsmsS283maaar();
	public void setMsmsS283maaar(Integer msmsS283maaar);
	public Integer getMsmsS283maaas();
	public void setMsmsS283maaas(Integer msmsS283maaas);
	public Integer getMsmsS302mabbs();
	public void setMsmsS302mabbs(Integer msmsS302mabbs);
	public Integer getMsmsS302mabbr();
	public void setMsmsS302mabbr(Integer msmsS302mabbr);
	public Integer getMsmsNorpreg34();
	public void setMsmsNorpreg34(Integer msmsNorpreg34);
	public Integer getMsmsH35abs();
	public void setMsmsH35abs(Integer msmsH35abs);
	public Integer getMsmsH35abr();
	public void setMsmsH35abr(Integer msmsH35abr);
	public Integer getMsmsS30ipaaar();
	public void setMsmsS30ipaaar(Integer msmsS30ipaaar);
	public Integer getMsmsS30ipaaas();
	public void setMsmsS30ipaaas(Integer msmsS30ipaaas);
	public Integer getMsmsH313mab();
	public void setMsmsH313mab(Integer msmsH313mab);
	public Integer getMsmsOleanoid16();
	public void setMsmsOleanoid16(Integer msmsOleanoid16);
	public Integer getMsmsOleanoid15();
	public void setMsmsOleanoid15(Integer msmsOleanoid15);
	public Integer getMsmsOleanoid17();
	public void setMsmsOleanoid17(Integer msmsOleanoid17);
	public Integer getMsmsOleanoid13();
	public void setMsmsOleanoid13(Integer msmsOleanoid13);
	public Integer getMsmsIstdConc();
	public void setMsmsIstdConc(Integer msmsIstdConc);
	public Integer getMsmsS303mabbr();
	public void setMsmsS303mabbr(Integer msmsS303mabbr);
	public Integer getMsmsS303mabbs();
	public void setMsmsS303mabbs(Integer msmsS303mabbs);
	public Integer getMsmsH31ba();
	public void setMsmsH31ba(Integer msmsH31ba);
	public Integer getMsmsOl18ene();
	public void setMsmsOl18ene(Integer msmsOl18ene);
	public String getMsmsQc();
	public void setMsmsQc(String msmsQc);
	public Integer getMsmsH30ts();
	public void setMsmsH30ts(Integer msmsH30ts);
	public Integer getMsmsTm();
	public void setMsmsTm(Integer msmsTm);
	public Integer getMsmsTs();
	public void setMsmsTs(Integer msmsTs);
	public Integer getMsmsDc28unk17();
	public void setMsmsDc28unk17(Integer msmsDc28unk17);
	public Integer getMsmsDc28unk16();
	public void setMsmsDc28unk16(Integer msmsDc28unk16);
	public Integer getMsmsS303paaar();
	public void setMsmsS303paaar(Integer msmsS303paaar);
	public Integer getMsmsS303paaas();
	public void setMsmsS303paaas(Integer msmsS303paaas);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Integer getMsmsS284maaas();
	public void setMsmsS284maaas(Integer msmsS284maaas);
	public Integer getMsmsS284maaar();
	public void setMsmsS284maaar(Integer msmsS284maaar);
	public Integer getMsmsD29bas();
	public void setMsmsD29bas(Integer msmsD29bas);
	public Integer getMsmsD29bar();
	public void setMsmsD29bar(Integer msmsD29bar);
	public Integer getMsmsH30ab();
	public void setMsmsH30ab(Integer msmsH30ab);
	public Integer getMsmsH30aa();
	public void setMsmsH30aa(Integer msmsH30aa);
	public Integer getMsmsH30ba();
	public void setMsmsH30ba(Integer msmsH30ba);
	public Integer getMsmsS29baar();
	public void setMsmsS29baar(Integer msmsS29baar);
	public Integer getMsmsTriterp17a();
	public void setMsmsTriterp17a(Integer msmsTriterp17a);
	public Integer getMsmsS303maaar();
	public void setMsmsS303maaar(Integer msmsS303maaar);
	public Integer getMsmsS303maaas();
	public void setMsmsS303maaas(Integer msmsS303maaas);
	public Integer getMsmsS30npbaar();
	public void setMsmsS30npbaar(Integer msmsS30npbaar);
	public Integer getMsmsDh29();
	public void setMsmsDh29(Integer msmsDh29);
	public Integer getMsmsDh30();
	public void setMsmsDh30(Integer msmsDh30);
	public Integer getMsmsRearnghop();
	public void setMsmsRearnghop(Integer msmsRearnghop);
	public Integer getMsmsH312mab();
	public void setMsmsH312mab(Integer msmsH312mab);
	public Integer getMsmsGama();
	public void setMsmsGama(Integer msmsGama);
	public Integer getMsmsGamb();
	public void setMsmsGamb(Integer msmsGamb);
	public Integer getMsmsDesalup();
	public void setMsmsDesalup(Integer msmsDesalup);
	public Integer getMsmsS294maaar();
	public void setMsmsS294maaar(Integer msmsS294maaar);
	public Integer getMsmsD26n24bar();
	public void setMsmsD26n24bar(Integer msmsD26n24bar);
	public Integer getMsmsD26n24bas();
	public void setMsmsD26n24bas(Integer msmsD26n24bas);
	public Integer getMsmsD30npabr();
	public void setMsmsD30npabr(Integer msmsD30npabr);
	public Integer getMsmsNorpreg89();
	public void setMsmsNorpreg89(Integer msmsNorpreg89);
	public Integer getMsmsS26n24abbs();
	public void setMsmsS26n24abbs(Integer msmsS26n24abbs);
	public Integer getMsmsS26n24abbr();
	public void setMsmsS26n24abbr(Integer msmsS26n24abbr);
	public Integer getMsmsD26n24abr();
	public void setMsmsD26n24abr(Integer msmsD26n24abr);
	public Integer getMsmsD26n24abs();
	public void setMsmsD26n24abs(Integer msmsD26n24abs);
	public Integer getMsmsH34abs();
	public void setMsmsH34abs(Integer msmsH34abs);
	public Integer getMsmsH34abr();
	public void setMsmsH34abr(Integer msmsH34abr);
	public Integer getMsmsH29n25ab();
	public void setMsmsH29n25ab(Integer msmsH29n25ab);
	public Integer getMsmsRh34b();
	public void setMsmsRh34b(Integer msmsRh34b);
	public Integer getMsmsRh34a();
	public void setMsmsRh34a(Integer msmsRh34a);
	public Integer getMsmsRh33a();
	public void setMsmsRh33a(Integer msmsRh33a);
	public Integer getMsmsRh33b();
	public void setMsmsRh33b(Integer msmsRh33b);
	public Integer getMsmsS28abbr();
	public void setMsmsS28abbr(Integer msmsS28abbr);
	public Integer getMsmsS28abbs();
	public void setMsmsS28abbs(Integer msmsS28abbs);
	public Integer getMsmsS304mabbs2maaar();
	public void setMsmsS304mabbs2maaar(Integer msmsS304mabbs2maaar);
	public Integer getMsmsS26n27baar();
	public void setMsmsS26n27baar(Integer msmsS26n27baar);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Integer getMsmsH32ba();
	public void setMsmsH32ba(Integer msmsH32ba);
	public Integer getMsmsOl12ene();
	public void setMsmsOl12ene(Integer msmsOl12ene);
	public Integer getMsmsOl12ene18a();
	public void setMsmsOl12ene18a(Integer msmsOl12ene18a);
	public Integer getMsmsD294mbara();
	public void setMsmsD294mbara(Integer msmsD294mbara);
	public Integer getMsmsD294mbarb();
	public void setMsmsD294mbarb(Integer msmsD294mbarb);
	public Integer getMsmsD294mbasb();
	public void setMsmsD294mbasb(Integer msmsD294mbasb);
	public Integer getMsmsD294mbasa();
	public void setMsmsD294mbasa(Integer msmsD294mbasa);
	public String getMsmsLab();
	public void setMsmsLab(String msmsLab);
	public Integer getMsmsS26n24aaas();
	public void setMsmsS26n24aaas(Integer msmsS26n24aaas);
	public Integer getMsmsS26n24aaar();
	public void setMsmsS26n24aaar(Integer msmsS26n24aaar);
	public Integer getMsmsOl3m24n105abeo();
	public void setMsmsOl3m24n105abeo(Integer msmsOl3m24n105abeo);
	public Integer getMsmsB30r();
	public void setMsmsB30r(Integer msmsB30r);
	public Integer getMsmsB30w();
	public void setMsmsB30w(Integer msmsB30w);
	public Integer getMsmsB30t();
	public void setMsmsB30t(Integer msmsB30t);
	public Integer getMsmsD294mabs();
	public void setMsmsD294mabs(Integer msmsD294mabs);
	public Integer getMsmsD29abr();
	public void setMsmsD29abr(Integer msmsD29abr);
	public Integer getMsmsD29abs();
	public void setMsmsD29abs(Integer msmsD29abs);
	public Integer getMsmsS294mabbr();
	public void setMsmsS294mabbr(Integer msmsS294mabbr);
	public Integer getMsmsNorpreg1();
	public void setMsmsNorpreg1(Integer msmsNorpreg1);
	public Integer getMsmsNorpreg5();
	public void setMsmsNorpreg5(Integer msmsNorpreg5);
	public Integer getMsmsNorpreg2();
	public void setMsmsNorpreg2(Integer msmsNorpreg2);
	public Integer getMsmsNorpreg7();
	public void setMsmsNorpreg7(Integer msmsNorpreg7);
	public Integer getMsmsNorpreg6();
	public void setMsmsNorpreg6(Integer msmsNorpreg6);
	public Integer getMsmsOl18b();
	public void setMsmsOl18b(Integer msmsOl18b);
	public Integer getMsmsOl18a();
	public void setMsmsOl18a(Integer msmsOl18a);
}
