package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOMsSaturate extends GTOAnalysisData {
	public Double getC3222r();
	public void setC3222r(Double c3222r);
	public Double getC3222s();
	public void setC3222s(Double c3222s);
	public Double getMsD29absS28abbr();
	public void setMsD29absS28abbr(Double msD29absS28abbr);
	public Double getC253();
	public void setC253(Double c253);
	public Double getC29b3();
	public void setC29b3(Double c29b3);
	public Double getMsD27bar();
	public void setMsD27bar(Double msD27bar);
	public Double getMsD27bas();
	public void setMsD27bas(Double msD27bas);
	public Double getMs9d29bar();
	public void setMs9d29bar(Double ms9d29bar);
	public Double getMs9d29bas();
	public void setMs9d29bas(Double ms9d29bas);
	public String getMsSampleIdVend();
	public void setMsSampleIdVend(String msSampleIdVend);
	public Double getC30b3();
	public void setC30b3(Double c30b3);
	public Double getGammace();
	public void setGammace(Double gammace);
	public Double getMsM32b();
	public void setMsM32b(Double msM32b);
	public Double getMsD28bassR();
	public void setMsD28bassR(Double msD28bassR);
	public Double getMsM32r();
	public void setMsM32r(Double msM32r);
	public Double getMsM32s();
	public void setMsM32s(Double msM32s);
	public Double getX25nor30ab();
	public void setX25nor30ab(Double x25nor30ab);
	public Double getMs1424dmdi();
	public void setMs1424dmdi(Double ms1424dmdi);
	public Double getT23a();
	public void setT23a(Double t23a);
	public Double getT23b();
	public void setT23b(Double t23b);
	public Double getMsM31b();
	public void setMsM31b(Double msM31b);
	public Date getMsQcDate();
	public void setMsQcDate(Date msQcDate);
	public Double getT21();
	public void setT21(Double t21);
	public Double getT22();
	public void setT22(Double t22);
	public Double getC26a3();
	public void setC26a3(Double c26a3);
	public Double getMsD28abs();
	public void setMsD28abs(Double msD28abs);
	public Double getMsD28abr();
	public void setMsD28abr(Double msD28abr);
	public Double getC28n20rRaw();
	public void setC28n20rRaw(Double c28n20rRaw);
	public Date getMsLastUpdate();
	public void setMsLastUpdate(Date msLastUpdate);
	public Double getMsS30aaas();
	public void setMsS30aaas(Double msS30aaas);
	public Double getMsS30aaar();
	public void setMsS30aaar(Double msS30aaar);
	public Double getC34b3();
	public void setC34b3(Double c34b3);
	public Double getC26i20s();
	public void setC26i20s(Double c26i20s);
	public Double getC26i20r();
	public void setC26i20r(Double c26i20r);
	public Double getMsC30norC29hom();
	public void setMsC30norC29hom(Double msC30norC29hom);
	public Double getC35a3();
	public void setC35a3(Double c35a3);
	public Double getNh29a();
	public void setNh29a(Double nh29a);
	public String getMsIqmCode();
	public void setMsIqmCode(String msIqmCode);
	public Date getMsDate();
	public void setMsDate(Date msDate);
	public Double getMs8s28abbr();
	public void setMs8s28abbr(Double ms8s28abbr);
	public Double getMs8s28abbs();
	public void setMs8s28abbs(Double ms8s28abbs);
	public Double getMsC2717bTnh();
	public void setMsC2717bTnh(Double msC2717bTnh);
	public Double getC203();
	public void setC203(Double c203);
	public Double getPhyllocladane16a();
	public void setPhyllocladane16a(Double phyllocladane16a);
	public Double getC31a3();
	public void setC31a3(Double c31a3);
	public Double getPhyllocladane16b();
	public void setPhyllocladane16b(Double phyllocladane16b);
	public Double getMsS26bbs();
	public void setMsS26bbs(Double msS26bbs);
	public Double getMsS26bbr();
	public void setMsS26bbr(Double msS26bbr);
	public Double getMsD21();
	public void setMsD21(Double msD21);
	public Double getMsD22();
	public void setMsD22(Double msD22);
	public Double getDiah();
	public void setDiah(Double diah);
	public Double getMsS27aaas();
	public void setMsS27aaas(Double msS27aaas);
	public Double getMsS27aaar();
	public void setMsS27aaar(Double msS27aaar);
	public Double getC3422r();
	public void setC3422r(Double c3422r);
	public Double getC3422s();
	public void setC3422s(Double c3422s);
	public String getMsJobId();
	public void setMsJobId(String msJobId);
	public String getMsLab();
	public void setMsLab(String msLab);
	public Double getMsIstdConc();
	public void setMsIstdConc(Double msIstdConc);
	public Double getC27n20rRaw();
	public void setC27n20rRaw(Double c27n20rRaw);
	public Double getX18aOl();
	public void setX18aOl(Double x18aOl);
	public Double getMsC3117b21aHmor();
	public void setMsC3117b21aHmor(Double msC3117b21aHmor);
	public Double getC29r20sRaw();
	public void setC29r20sRaw(Double c29r20sRaw);
	public Double getC27i20rRaw();
	public void setC27i20rRaw(Double c27i20rRaw);
	public Double getMsH312me();
	public void setMsH312me(Double msH312me);
	public Double getMsD28abrS27aaas();
	public void setMsD28abrS27aaas(Double msD28abrS27aaas);
	public Double getC244();
	public void setC244(Double c244);
	public Double getC243();
	public void setC243(Double c243);
	public Double getMsT23b();
	public void setMsT23b(Double msT23b);
	public Double getMsT23a();
	public void setMsT23a(Double msT23a);
	public Double getMsD27abs();
	public void setMsD27abs(Double msD27abs);
	public Double getMsD27abr();
	public void setMsD27abr(Double msD27abr);
	public Double getMsS28aaar();
	public void setMsS28aaar(Double msS28aaar);
	public Double getMsS28aaas();
	public void setMsS28aaas(Double msS28aaas);
	public Double getC28b3();
	public void setC28b3(Double c28b3);
	public Double getC29Ts();
	public void setC29Ts(Double c29Ts);
	public Double getMsIstd();
	public void setMsIstd(Double msIstd);
	public Double getC27i20sRaw();
	public void setC27i20sRaw(Double c27i20sRaw);
	public Double getHdrimane();
	public void setHdrimane(Double hdrimane);
	public Double getC264();
	public void setC264(Double c264);
	public Double getC263();
	public void setC263(Double c263);
	public Double getC29a3();
	public void setC29a3(Double c29a3);
	public Double getNipimarane();
	public void setNipimarane(Double nipimarane);
	public Double getC29n20sRaw();
	public void setC29n20sRaw(Double c29n20sRaw);
	public Double getMs8s26bbs();
	public void setMs8s26bbs(Double ms8s26bbs);
	public Double getMs8s26bbr();
	public void setMs8s26bbr(Double ms8s26bbr);
	public Double getC29Hop();
	public void setC29Hop(Double c29Hop);
	public Double getC27r20sRaw();
	public void setC27r20sRaw(Double c27r20sRaw);
	public Double getC30a3();
	public void setC30a3(Double c30a3);
	public Double getRdrimane1();
	public void setRdrimane1(Double rdrimane1);
	public Double getRdrimane2();
	public void setRdrimane2(Double rdrimane2);
	public Double getC25a3();
	public void setC25a3(Double c25a3);
	public Double getX25nor31ab();
	public void setX25nor31ab(Double x25nor31ab);
	public Double getDiamantane1m();
	public void setDiamantane1m(Double diamantane1m);
	public Double getC28r3Raw();
	public void setC28r3Raw(Double c28r3Raw);
	public String getMsQcUser();
	public void setMsQcUser(String msQcUser);
	public Double getMsM31();
	public void setMsM31(Double msM31);
	public Double getMsBChol();
	public void setMsBChol(Double msBChol);
	public Double getDiamantane4m();
	public void setDiamantane4m(Double diamantane4m);
	public Double getMsS30abbs();
	public void setMsS30abbs(Double msS30abbs);
	public Double getMsS30abbr();
	public void setMsS30abbr(Double msS30abbr);
	public Double getDiamantane3m();
	public void setDiamantane3m(Double diamantane3m);
	public Double getMsPh183();
	public void setMsPh183(Double msPh183);
	public Double getC29i20sRaw();
	public void setC29i20sRaw(Double c29i20sRaw);
	public Double getC34a3();
	public void setC34a3(Double c34a3);
	public Double getC28r1Raw();
	public void setC28r1Raw(Double c28r1Raw);
	public Double getDiamantane();
	public void setDiamantane(Double diamantane);
	public Double getMsH31r205();
	public void setMsH31r205(Double msH31r205);
	public Double getC28i20rRaw();
	public void setC28i20rRaw(Double c28i20rRaw);
	public Double getBeyerane();
	public void setBeyerane(Double beyerane);
	public Double getC25b3();
	public void setC25b3(Double c25b3);
	public Double getMsH313me();
	public void setMsH313me(Double msH313me);
	public Double getC213();
	public void setC213(Double c213);
	public Double getMsD28barr();
	public void setMsD28barr(Double msD28barr);
	public Double getMsD28bars();
	public void setMsD28bars(Double msD28bars);
	public Double getMs9d28bass();
	public void setMs9d28bass(Double ms9d28bass);
	public Double getMs9d28basr();
	public void setMs9d28basr(Double ms9d28basr);
	public Double getMsD28basr();
	public void setMsD28basr(Double msD28basr);
	public Double getMsD28bass();
	public void setMsD28bass(Double msD28bass);
	public Double getMsC2917a21bNhop();
	public void setMsC2917a21bNhop(Double msC2917a21bNhop);
	public Double getC33b3();
	public void setC33b3(Double c33b3);
	public Double getMs9d28bars();
	public void setMs9d28bars(Double ms9d28bars);
	public Double getMs9d28barr();
	public void setMs9d28barr(Double ms9d28barr);
	public Double getMsS27abbrD29bas();
	public void setMsS27abbrD29bas(Double msS27abbrD29bas);
	public Double getMsS28abbr();
	public void setMsS28abbr(Double msS28abbr);
	public Double getMsS28abbs();
	public void setMsS28abbs(Double msS28abbs);
	public Double getMs48dmdi();
	public void setMs48dmdi(Double ms48dmdi);
	public Double getC27TmB();
	public void setC27TmB(Double c27TmB);
	public Double getC28a3();
	public void setC28a3(Double c28a3);
	public Double getMsTppA();
	public void setMsTppA(Double msTppA);
	public Double getMsTppB();
	public void setMsTppB(Double msTppB);
	public Double getC3122s();
	public void setC3122s(Double c3122s);
	public Double getC3122r();
	public void setC3122r(Double c3122r);
	public Double getMsC282530Bnh();
	public void setMsC282530Bnh(Double msC282530Bnh);
	public Double getMsTrisnorm();
	public void setMsTrisnorm(Double msTrisnorm);
	public Double getC36a3();
	public void setC36a3(Double c36a3);
	public Double getC29Diahop();
	public void setC29Diahop(Double c29Diahop);
	public Double getC28n20sRaw();
	public void setC28n20sRaw(Double c28n20sRaw);
	public Double getMsC30tp2();
	public void setMsC30tp2(Double msC30tp2);
	public Double getMsC30tp1();
	public void setMsC30tp1(Double msC30tp1);
	public Double getMsS22bb();
	public void setMsS22bb(Double msS22bb);
	public String getMsAuthor();
	public void setMsAuthor(String msAuthor);
	public Double getMsD30bas();
	public void setMsD30bas(Double msD30bas);
	public Double getBicadR();
	public void setBicadR(Double bicadR);
	public Double getMsD29bas();
	public void setMsD29bas(Double msD29bas);
	public Double getMsD29bar();
	public void setMsD29bar(Double msD29bar);
	public Double getBicadW();
	public void setBicadW(Double bicadW);
	public Double getBicadT();
	public void setBicadT(Double bicadT);
	public Double getMsPr183();
	public void setMsPr183(Double msPr183);
	public String getMsSvcCode();
	public void setMsSvcCode(String msSvcCode);
	public Date getMsAcqDate();
	public void setMsAcqDate(Date msAcqDate);
	public Double getC27n20sRaw();
	public void setC27n20sRaw(Double c27n20sRaw);
	public Double getMs8s30aaas();
	public void setMs8s30aaas(Double ms8s30aaas);
	public Double getMs8s30aaar();
	public void setMs8s30aaar(Double ms8s30aaar);
	public Double getMs8s29abbs();
	public void setMs8s29abbs(Double ms8s29abbs);
	public Double getMs8s29abbr();
	public void setMs8s29abbr(Double ms8s29abbr);
	public Double getTarax();
	public void setTarax(Double tarax);
	public Double getC29bHop();
	public void setC29bHop(Double c29bHop);
	public Double getC3522s();
	public void setC3522s(Double c3522s);
	public Double getLabdane();
	public void setLabdane(Double labdane);
	public Double getC3522r();
	public void setC3522r(Double c3522r);
	public Double getC36b3();
	public void setC36b3(Double c36b3);
	public Double getMor();
	public void setMor(Double mor);
	public Double getMsD28absS27abbr();
	public void setMsD28absS27abbr(Double msD28absS27abbr);
	public Double getNormor();
	public void setNormor(Double normor);
	public Double getMsH30b();
	public void setMsH30b(Double msH30b);
	public Double getMs8s27abbs();
	public void setMs8s27abbs(Double ms8s27abbs);
	public Double getMs8s27abbr();
	public void setMs8s27abbr(Double ms8s27abbr);
	public Double getMsC2717aTnh();
	public void setMsC2717aTnh(Double msC2717aTnh);
	public Double getC29r20rRaw();
	public void setC29r20rRaw(Double c29r20rRaw);
	public Double getMsHeneico();
	public void setMsHeneico(Double msHeneico);
	public Double getC30Hop();
	public void setC30Hop(Double c30Hop);
	public Double getMs9d27bas();
	public void setMs9d27bas(Double ms9d27bas);
	public Double getMs9d27bar();
	public void setMs9d27bar(Double ms9d27bar);
	public Double getMsH31b();
	public void setMsH31b(Double msH31b);
	public Double getC223();
	public void setC223(Double c223);
	public Double getMsS22();
	public void setMsS22(Double msS22);
	public Double getMsS21();
	public void setMsS21(Double msS21);
	public Double getMsS29aaas();
	public void setMsS29aaas(Double msS29aaas);
	public Double getMsS29aaar();
	public void setMsS29aaar(Double msS29aaar);
	public Double getNtcyclane();
	public void setNtcyclane(Double ntcyclane);
	public Double getC33a3();
	public void setC33a3(Double c33a3);
	public Double getMsC3117b21bHhop();
	public void setMsC3117b21bHhop(Double msC3117b21bHhop);
	public Double getC3322s();
	public void setC3322s(Double c3322s);
	public Double getC3322r();
	public void setC3322r(Double c3322r);
	public Double getX25nor28ab();
	public void setX25nor28ab(Double x25nor28ab);
	public Double getC29dm();
	public void setC29dm(Double c29dm);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getIpimarane();
	public void setIpimarane(Double ipimarane);
	public Double getC31b3();
	public void setC31b3(Double c31b3);
	public String getMsComments();
	public void setMsComments(String msComments);
	public Double getC29n20rRaw();
	public void setC29n20rRaw(Double c29n20rRaw);
	public Double getMs9d27abs();
	public void setMs9d27abs(Double ms9d27abs);
	public Double getMs9d27abr();
	public void setMs9d27abr(Double ms9d27abr);
	public Double getMsD29abs();
	public void setMsD29abs(Double msD29abs);
	public Double getKaurane();
	public void setKaurane(Double kaurane);
	public Double getC193();
	public void setC193(Double c193);
	public Double getC26b3();
	public void setC26b3(Double c26b3);
	public Double getMsD29abr();
	public void setMsD29abr(Double msD29abr);
	public Double getC27Ts();
	public void setC27Ts(Double c27Ts);
	public Double getC27Tm();
	public void setC27Tm(Double c27Tm);
	public Double getMsS21bb();
	public void setMsS21bb(Double msS21bb);
	public Double getMsC3017b21bHop();
	public void setMsC3017b21bHop(Double msC3017b21bHop);
	public Double getC28r4Raw();
	public void setC28r4Raw(Double c28r4Raw);
	public Double getNh30a();
	public void setNh30a(Double nh30a);
	public Double getMsC2917b21bNhop();
	public void setMsC2917b21bNhop(Double msC2917b21bNhop);
	public Double getMsD28barsR();
	public void setMsD28barsR(Double msD28barsR);
	public Double getBcarot();
	public void setBcarot(Double bcarot);
	public Double getTnrh();
	public void setTnrh(Double tnrh);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getMsX12();
	public void setMsX12(Double msX12);
	public Double getMsC3217b21aBhmor();
	public void setMsC3217b21aBhmor(Double msC3217b21aBhmor);
	public Double getC35b3();
	public void setC35b3(Double c35b3);
	public Double getMsX04();
	public void setMsX04(Double msX04);
	public Double getMsX03();
	public void setMsX03(Double msX03);
	public Double getMsX02();
	public void setMsX02(Double msX02);
	public Double getMsX01();
	public void setMsX01(Double msX01);
	public Double getMsX08();
	public void setMsX08(Double msX08);
	public Double getMsX07();
	public void setMsX07(Double msX07);
	public Double getMsX06();
	public void setMsX06(Double msX06);
	public Double getMsX05();
	public void setMsX05(Double msX05);
	public Double getMsX09();
	public void setMsX09(Double msX09);
	public Double getMsX11();
	public void setMsX11(Double msX11);
	public Double getMsX10();
	public void setMsX10(Double msX10);
	public Double getC27r20rRaw();
	public void setC27r20rRaw(Double c27r20rRaw);
	public Double getC29i20rRaw();
	public void setC29i20rRaw(Double c29i20rRaw);
	public String getMsRunNumber();
	public void setMsRunNumber(String msRunNumber);
	public String getMsMethod();
	public void setMsMethod(String msMethod);
	public Double getC28r2Raw();
	public void setC28r2Raw(Double c28r2Raw);
	public Double getMs8s30abbs();
	public void setMs8s30abbs(Double ms8s30abbs);
	public Double getMs8s30abbr();
	public void setMs8s30abbr(Double ms8s30abbr);
	public Double getMsH31s205();
	public void setMsH31s205(Double msH31s205);
	public Double getC28i20sRaw();
	public void setC28i20sRaw(Double c28i20sRaw);
	public String getMsQc();
	public void setMsQc(String msQc);
	public Double getMsT22();
	public void setMsT22(Double msT22);
	public Double getMsT21();
	public void setMsT21(Double msT21);
	public String getMsDataType();
	public void setMsDataType(String msDataType);
	public Double getMs34dmdi();
	public void setMs34dmdi(Double ms34dmdi);
	public Double getX18bOl();
	public void setX18bOl(Double x18bOl);
	public Double getDrimane();
	public void setDrimane(Double drimane);
	public Double getMsS29abbs();
	public void setMsS29abbs(Double msS29abbs);
	public Double getMsS29abbr();
	public void setMsS29abbr(Double msS29abbr);
	public Double getMsS27abbs();
	public void setMsS27abbs(Double msS27abbs);
	public Double getMsS27abbr();
	public void setMsS27abbr(Double msS27abbr);
	public Double getMs49dmdi();
	public void setMs49dmdi(Double ms49dmdi);
	public Double getBnrh();
	public void setBnrh(Double bnrh);
	public Double getMsS23b();
	public void setMsS23b(Double msS23b);
	public Double getMsS23a();
	public void setMsS23a(Double msS23a);
	public Double getC233();
	public void setC233(Double c233);
	public Double getC28dm();
	public void setC28dm(Double c28dm);
}
