package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOMplc extends GTOAnalysisData {
	public String getMplcLab();
	public void setMplcLab(String mplcLab);
	public Date getMplcAcqDate();
	public void setMplcAcqDate(Date mplcAcqDate);
	public Double getMplcTopAroSent();
	public void setMplcTopAroSent(Double mplcTopAroSent);
	public Double getMplcWoIntake();
	public void setMplcWoIntake(Double mplcWoIntake);
	public String getMplcComment();
	public void setMplcComment(String mplcComment);
	public String getMplcAuthor();
	public void setMplcAuthor(String mplcAuthor);
	public Date getMplcUpdatedDate();
	public void setMplcUpdatedDate(Date mplcUpdatedDate);
	public String getMplcUpdatedUser();
	public void setMplcUpdatedUser(String mplcUpdatedUser);
	public Double getMplcWoSat();
	public void setMplcWoSat(Double mplcWoSat);
	public Double getMplcWoAro();
	public void setMplcWoAro(Double mplcWoAro);
	public Date getMplcQcDate();
	public void setMplcQcDate(Date mplcQcDate);
	public String getMplcSampleIdVend();
	public void setMplcSampleIdVend(String mplcSampleIdVend);
	public String getMplcQcUser();
	public void setMplcQcUser(String mplcQcUser);
	public Double getMplcIstdNc21Ppm();
	public void setMplcIstdNc21Ppm(Double mplcIstdNc21Ppm);
	public Double getMplcWoPdp();
	public void setMplcWoPdp(Double mplcWoPdp);
	public String getMplcIqmCode();
	public void setMplcIqmCode(String mplcIqmCode);
	public Double getMplcIstdCholPpm();
	public void setMplcIstdCholPpm(Double mplcIstdCholPpm);
	public String getMplcJobId();
	public void setMplcJobId(String mplcJobId);
	public Double getMplcWoDn();
	public void setMplcWoDn(Double mplcWoDn);
	public String getMplcQcFlag();
	public void setMplcQcFlag(String mplcQcFlag);
	public Date getMplcDate();
	public void setMplcDate(Date mplcDate);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getMplcRunNumber();
	public void setMplcRunNumber(String mplcRunNumber);
	public Double getMplcTopSatSent();
	public void setMplcTopSatSent(Double mplcTopSatSent);
	public String getMplcMethod();
	public void setMplcMethod(String mplcMethod);
	public Double getMplcTopSatOrg();
	public void setMplcTopSatOrg(Double mplcTopSatOrg);
	public Double getMplcTopIntake();
	public void setMplcTopIntake(Double mplcTopIntake);
	public String getMplcCreatedUser();
	public void setMplcCreatedUser(String mplcCreatedUser);
	public Double getMplcTopAroOrg();
	public void setMplcTopAroOrg(Double mplcTopAroOrg);
	public Date getMplcCreatedDate();
	public void setMplcCreatedDate(Date mplcCreatedDate);
	public String getMplcSvcCode();
	public void setMplcSvcCode(String mplcSvcCode);
	public String getSampleId();
	public void setSampleId(String sampleId);
}
