package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOOilPourpoint extends GTOAnalysisData {
	public Date getPpLastUpdate();
	public void setPpLastUpdate(Date ppLastUpdate);
	public String getPpQc();
	public void setPpQc(String ppQc);
	public String getPpValueQualifier();
	public void setPpValueQualifier(String ppValueQualifier);
	public String getPpIqmCode();
	public void setPpIqmCode(String ppIqmCode);
	public String getPpSampleIdVend();
	public void setPpSampleIdVend(String ppSampleIdVend);
	public Date getPpAcqDate();
	public void setPpAcqDate(Date ppAcqDate);
	public Double getPpValue();
	public void setPpValue(Double ppValue);
	public String getPpLab();
	public void setPpLab(String ppLab);
	public Double getPpConf();
	public void setPpConf(Double ppConf);
	public String getPpQcUser();
	public void setPpQcUser(String ppQcUser);
	public String getPpSvcCode();
	public void setPpSvcCode(String ppSvcCode);
	public String getPpRunNumber();
	public void setPpRunNumber(String ppRunNumber);
	public String getPpAuthor();
	public void setPpAuthor(String ppAuthor);
	public String getPpUnits();
	public void setPpUnits(String ppUnits);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getPpComments();
	public void setPpComments(String ppComments);
	public String getPpMethod();
	public void setPpMethod(String ppMethod);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Date getPpQcDate();
	public void setPpQcDate(Date ppQcDate);
	public String getPpJobId();
	public void setPpJobId(String ppJobId);
	public Date getPpUpdatedDate();
	public void setPpUpdatedDate(Date ppUpdatedDate);
	public String getPpCreatedUser();
	public void setPpCreatedUser(String ppCreatedUser);
	public String getPpUpperQual();
	public void setPpUpperQual(String ppUpperQual);
	public String getPpType();
	public void setPpType(String ppType);
	public String getPpUpdatedUser();
	public void setPpUpdatedUser(String ppUpdatedUser);
	public String getPpLabref();
	public void setPpLabref(String ppLabref);
	public String getPpLabrefPage();
	public void setPpLabrefPage(String ppLabrefPage);
	public String getPpLowerQual();
	public void setPpLowerQual(String ppLowerQual);
	public String getPpComment();
	public void setPpComment(String ppComment);
	public String getPpOpid();
	public void setPpOpid(String ppOpid);
	public Double getPpUpper();
	public void setPpUpper(Double ppUpper);
	public Double getPpLower();
	public void setPpLower(Double ppLower);
	public Date getPpCreatedDate();
	public void setPpCreatedDate(Date ppCreatedDate);
	public String getPpQual();
	public void setPpQual(String ppQual);
	public String getPpRequestIdVend();
	public void setPpRequestIdVend(String ppRequestIdVend);
	public String getPpQcFlag();
	public void setPpQcFlag(String ppQcFlag);
}
