package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOOilInorganic extends GTOAnalysisData {
	public Double getIeAsC();
	public void setIeAsC(Double ieAsC);
	public String getIeBeQ();
	public void setIeBeQ(String ieBeQ);
	public Double getIeBeC();
	public void setIeBeC(Double ieBeC);
	public String getIeAsQ();
	public void setIeAsQ(String ieAsQ);
	public String getIeComment();
	public void setIeComment(String ieComment);
	public String getIeSampleIdVend();
	public void setIeSampleIdVend(String ieSampleIdVend);
	public Double getIeRuC();
	public void setIeRuC(Double ieRuC);
	public String getIeRuQ();
	public void setIeRuQ(String ieRuQ);
	public Double getIeHgC();
	public void setIeHgC(Double ieHgC);
	public String getIeHgQ();
	public void setIeHgQ(String ieHgQ);
	public String getIePQ();
	public void setIePQ(String iePQ);
	public Double getIePC();
	public void setIePC(Double iePC);
	public Double getIeRe();
	public void setIeRe(Double ieRe);
	public Double getIeRb();
	public void setIeRb(Double ieRb);
	public Double getIeRh();
	public void setIeRh(Double ieRh);
	public Double getIePt();
	public void setIePt(Double iePt);
	public String getIeQc();
	public void setIeQc(String ieQc);
	public Double getIeSr();
	public void setIeSr(Double ieSr);
	public Double getIeTe();
	public void setIeTe(Double ieTe);
	public Double getIeTh();
	public void setIeTh(Double ieTh);
	public Double getIeTa();
	public void setIeTa(Double ieTa);
	public Double getIeTi();
	public void setIeTi(Double ieTi);
	public Double getIeTl();
	public void setIeTl(Double ieTl);
	public Double getIeRu();
	public void setIeRu(Double ieRu);
	public Double getIeSe();
	public void setIeSe(Double ieSe);
	public Double getIeSb();
	public void setIeSb(Double ieSb);
	public Double getIeSn();
	public void setIeSn(Double ieSn);
	public Double getIeSi();
	public void setIeSi(Double ieSi);
	public Double getIeNiC();
	public void setIeNiC(Double ieNiC);
	public String getIeNiQ();
	public void setIeNiQ(String ieNiQ);
	public Double getIeZn();
	public void setIeZn(Double ieZn);
	public Double getIeZr();
	public void setIeZr(Double ieZr);
	public String getIeReQ();
	public void setIeReQ(String ieReQ);
	public String getIeGeQ();
	public void setIeGeQ(String ieGeQ);
	public Double getIeReC();
	public void setIeReC(Double ieReC);
	public String getIeHtQcUser();
	public void setIeHtQcUser(String ieHtQcUser);
	public Double getIeAuC();
	public void setIeAuC(Double ieAuC);
	public Double getIeMgC();
	public void setIeMgC(Double ieMgC);
	public String getIeMgQ();
	public void setIeMgQ(String ieMgQ);
	public String getIeAuQ();
	public void setIeAuQ(String ieAuQ);
	public Double getIeSiC();
	public void setIeSiC(Double ieSiC);
	public String getIeSiQ();
	public void setIeSiQ(String ieSiQ);
	public String getIeTlQ();
	public void setIeTlQ(String ieTlQ);
	public Double getIeTlC();
	public void setIeTlC(Double ieTlC);
	public String getIeZnQ();
	public void setIeZnQ(String ieZnQ);
	public Date getIeHtQcDate();
	public void setIeHtQcDate(Date ieHtQcDate);
	public Double getIeZnC();
	public void setIeZnC(Double ieZnC);
	public Double getIeSC();
	public void setIeSC(Double ieSC);
	public String getIeSQ();
	public void setIeSQ(String ieSQ);
	public Double getIeBC();
	public void setIeBC(Double ieBC);
	public String getIeBQ();
	public void setIeBQ(String ieBQ);
	public String getIeAuthor();
	public void setIeAuthor(String ieAuthor);
	public String getIeBiQ();
	public void setIeBiQ(String ieBiQ);
	public Double getIeBiC();
	public void setIeBiC(Double ieBiC);
	public String getIeClQ();
	public void setIeClQ(String ieClQ);
	public Double getIeClC();
	public void setIeClC(Double ieClC);
	public Double getIeCuC();
	public void setIeCuC(Double ieCuC);
	public String getIeBaQ();
	public void setIeBaQ(String ieBaQ);
	public Double getIeBaC();
	public void setIeBaC(Double ieBaC);
	public String getIeSvcCode();
	public void setIeSvcCode(String ieSvcCode);
	public String getIeCdQ();
	public void setIeCdQ(String ieCdQ);
	public Double getIeCdC();
	public void setIeCdC(Double ieCdC);
	public String getIeCuQ();
	public void setIeCuQ(String ieCuQ);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getIeBrQ();
	public void setIeBrQ(String ieBrQ);
	public Double getIeBrC();
	public void setIeBrC(Double ieBrC);
	public Double getIeCeC();
	public void setIeCeC(Double ieCeC);
	public Double getIeUC();
	public void setIeUC(Double ieUC);
	public String getIeUQ();
	public void setIeUQ(String ieUQ);
	public Double getIeGaC();
	public void setIeGaC(Double ieGaC);
	public String getIeGaQ();
	public void setIeGaQ(String ieGaQ);
	public Double getIeVC();
	public void setIeVC(Double ieVC);
	public String getIeVQ();
	public void setIeVQ(String ieVQ);
	public Double getIeSeC();
	public void setIeSeC(Double ieSeC);
	public String getIeSeQ();
	public void setIeSeQ(String ieSeQ);
	public String getIeThQ();
	public void setIeThQ(String ieThQ);
	public Double getIeThC();
	public void setIeThC(Double ieThC);
	public String getIeRbQ();
	public void setIeRbQ(String ieRbQ);
	public Double getIeRbC();
	public void setIeRbC(Double ieRbC);
	public Double getIeWC();
	public void setIeWC(Double ieWC);
	public String getIeWQ();
	public void setIeWQ(String ieWQ);
	public Double getIeFC();
	public void setIeFC(Double ieFC);
	public String getIeFQ();
	public void setIeFQ(String ieFQ);
	public String getIeLaQ();
	public void setIeLaQ(String ieLaQ);
	public Double getIeLaC();
	public void setIeLaC(Double ieLaC);
	public Double getIeHfC();
	public void setIeHfC(Double ieHfC);
	public String getIeHfQ();
	public void setIeHfQ(String ieHfQ);
	public String getIeTiQ();
	public void setIeTiQ(String ieTiQ);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getIeTiC();
	public void setIeTiC(Double ieTiC);
	public String getIeTaQ();
	public void setIeTaQ(String ieTaQ);
	public Double getIeTaC();
	public void setIeTaC(Double ieTaC);
	public Date getIeLastUpdate();
	public void setIeLastUpdate(Date ieLastUpdate);
	public Double getIeMnC();
	public void setIeMnC(Double ieMnC);
	public String getIeMnQ();
	public void setIeMnQ(String ieMnQ);
	public String getIeJobId();
	public void setIeJobId(String ieJobId);
	public Date getIeAcqDate();
	public void setIeAcqDate(Date ieAcqDate);
	public Double getIeYC();
	public void setIeYC(Double ieYC);
	public String getIeYQ();
	public void setIeYQ(String ieYQ);
	public Double getIeCrC();
	public void setIeCrC(Double ieCrC);
	public Double getIeNaC();
	public void setIeNaC(Double ieNaC);
	public String getIeCaQ();
	public void setIeCaQ(String ieCaQ);
	public Double getIeCaC();
	public void setIeCaC(Double ieCaC);
	public String getIeCrQ();
	public void setIeCrQ(String ieCrQ);
	public String getIeAlQ();
	public void setIeAlQ(String ieAlQ);
	public Double getIeAlC();
	public void setIeAlC(Double ieAlC);
	public String getIeNaQ();
	public void setIeNaQ(String ieNaQ);
	public Double getIeMoC();
	public void setIeMoC(Double ieMoC);
	public String getIeMoQ();
	public void setIeMoQ(String ieMoQ);
	public Double getIeIC();
	public void setIeIC(Double ieIC);
	public String getIeIQ();
	public void setIeIQ(String ieIQ);
	public String getIeNbQ();
	public void setIeNbQ(String ieNbQ);
	public Double getIeNbC();
	public void setIeNbC(Double ieNbC);
	public Double getIeSrC();
	public void setIeSrC(Double ieSrC);
	public String getIeSrQ();
	public void setIeSrQ(String ieSrQ);
	public String getIeMethod();
	public void setIeMethod(String ieMethod);
	public Double getIeKC();
	public void setIeKC(Double ieKC);
	public String getIeKQ();
	public void setIeKQ(String ieKQ);
	public String getIeLab();
	public void setIeLab(String ieLab);
	public Double getIeSbC();
	public void setIeSbC(Double ieSbC);
	public String getIeSbQ();
	public void setIeSbQ(String ieSbQ);
	public String getIeTeQ();
	public void setIeTeQ(String ieTeQ);
	public String getIeDataType();
	public void setIeDataType(String ieDataType);
	public Double getIeTeC();
	public void setIeTeC(Double ieTeC);
	public Double getIeInC();
	public void setIeInC(Double ieInC);
	public String getIeInQ();
	public void setIeInQ(String ieInQ);
	public String getIeRhQ();
	public void setIeRhQ(String ieRhQ);
	public Double getIeRhC();
	public void setIeRhC(Double ieRhC);
	public String getIeRunNumber();
	public void setIeRunNumber(String ieRunNumber);
	public String getIePbQ();
	public void setIePbQ(String iePbQ);
	public Double getIePbC();
	public void setIePbC(Double iePbC);
	public Double getIeFeC();
	public void setIeFeC(Double ieFeC);
	public String getIeFeQ();
	public void setIeFeQ(String ieFeQ);
	public String getIeAgQ();
	public void setIeAgQ(String ieAgQ);
	public Double getIeAgC();
	public void setIeAgC(Double ieAgC);
	public Double getIePtC();
	public void setIePtC(Double iePtC);
	public String getIePtQ();
	public void setIePtQ(String iePtQ);
	public Date getIeDate();
	public void setIeDate(Date ieDate);
	public String getIeComm();
	public void setIeComm(String ieComm);
	public Double getIePdC();
	public void setIePdC(Double iePdC);
	public Double getIeAl();
	public void setIeAl(Double ieAl);
	public Double getIeAg();
	public void setIeAg(Double ieAg);
	public Double getIeAs();
	public void setIeAs(Double ieAs);
	public Double getIeAu();
	public void setIeAu(Double ieAu);
	public String getIeCoQ();
	public void setIeCoQ(String ieCoQ);
	public Double getIeCd();
	public void setIeCd(Double ieCd);
	public Double getIeCa();
	public void setIeCa(Double ieCa);
	public Double getIeCl();
	public void setIeCl(Double ieCl);
	public Double getIeCo();
	public void setIeCo(Double ieCo);
	public Double getIeCu();
	public void setIeCu(Double ieCu);
	public Double getIeCr();
	public void setIeCr(Double ieCr);
	public Double getIeBe();
	public void setIeBe(Double ieBe);
	public Double getIeBa();
	public void setIeBa(Double ieBa);
	public Double getIeBi();
	public void setIeBi(Double ieBi);
	public Double getIeBr();
	public void setIeBr(Double ieBr);
	public String getIeZrQ();
	public void setIeZrQ(String ieZrQ);
	public Double getIeGe();
	public void setIeGe(Double ieGe);
	public Double getIeCoC();
	public void setIeCoC(Double ieCoC);
	public String getIePdQ();
	public void setIePdQ(String iePdQ);
	public Double getIeFe();
	public void setIeFe(Double ieFe);
	public Double getIeZrC();
	public void setIeZrC(Double ieZrC);
	public Double getIeGa();
	public void setIeGa(Double ieGa);
	public Double getIeIr();
	public void setIeIr(Double ieIr);
	public Double getIeIn();
	public void setIeIn(Double ieIn);
	public Double getIeHf();
	public void setIeHf(Double ieHf);
	public Double getIeHg();
	public void setIeHg(Double ieHg);
	public Double getIeLa();
	public void setIeLa(Double ieLa);
	public Double getIeMo();
	public void setIeMo(Double ieMo);
	public Double getIeMn();
	public void setIeMn(Double ieMn);
	public Double getIeLiC();
	public void setIeLiC(Double ieLiC);
	public String getIeLiQ();
	public void setIeLiQ(String ieLiQ);
	public Double getIeNb();
	public void setIeNb(Double ieNb);
	public Double getIeNa();
	public void setIeNa(Double ieNa);
	public Double getIeNi();
	public void setIeNi(Double ieNi);
	public Double getIeLi();
	public void setIeLi(Double ieLi);
	public Double getIeMg();
	public void setIeMg(Double ieMg);
	public Double getIePb();
	public void setIePb(Double iePb);
	public Double getIePd();
	public void setIePd(Double iePd);
	public String getIeHtIqmCode();
	public void setIeHtIqmCode(String ieHtIqmCode);
	public Double getIeSnC();
	public void setIeSnC(Double ieSnC);
	public String getIeSnQ();
	public void setIeSnQ(String ieSnQ);
	public Double getIeF();
	public void setIeF(Double ieF);
	public Double getIeI();
	public void setIeI(Double ieI);
	public Double getIeK();
	public void setIeK(Double ieK);
	public Double getIeP();
	public void setIeP(Double ieP);
	public Double getIeU();
	public void setIeU(Double ieU);
	public Double getIeV();
	public void setIeV(Double ieV);
	public Double getIeS();
	public void setIeS(Double ieS);
	public Double getIeY();
	public void setIeY(Double ieY);
	public Double getIeW();
	public void setIeW(Double ieW);
	public Double getIeB();
	public void setIeB(Double ieB);
	public Double getIeIrC();
	public void setIeIrC(Double ieIrC);
	public String getIeIrQ();
	public void setIeIrQ(String ieIrQ);
	public Double getWaterIeNiC();
	public void setWaterIeNiC(Double waterIeNiC);
	public String getIePo4Q();
	public void setIePo4Q(String iePo4Q);
	public Double getIePo4C();
	public void setIePo4C(Double iePo4C);
	public String getIeHexQ();
	public void setIeHexQ(String ieHexQ);
	public Double getIePro();
	public void setIePro(Double iePro);
	public Double getIeHexC();
	public void setIeHexC(Double ieHexC);
	public String getWaterIeNiQ();
	public void setWaterIeNiQ(String waterIeNiQ);
	public String getWaterIeComment();
	public void setWaterIeComment(String waterIeComment);
	public Double getIePo4();
	public void setIePo4(Double iePo4);
	public Double getIeGlycC();
	public void setIeGlycC(Double ieGlycC);
	public Double getWaterIeAce();
	public void setWaterIeAce(Double waterIeAce);
	public Double getIeCitric();
	public void setIeCitric(Double ieCitric);
	public String getIeQcUser();
	public void setIeQcUser(String ieQcUser);
	public String getIeCarbQ();
	public void setIeCarbQ(String ieCarbQ);
	public String getIeGlycQ();
	public void setIeGlycQ(String ieGlycQ);
	public Double getIeCarbC();
	public void setIeCarbC(Double ieCarbC);
	public String getWaterIeCarbQ();
	public void setWaterIeCarbQ(String waterIeCarbQ);
	public Double getWaterIeCarbC();
	public void setWaterIeCarbC(Double waterIeCarbC);
	public Double getIeHco3();
	public void setIeHco3(Double ieHco3);
	public String getWaterIeAppear();
	public void setWaterIeAppear(String waterIeAppear);
	public Double getWaterIeCarb();
	public void setWaterIeCarb(Double waterIeCarb);
	public Double getIeHex();
	public void setIeHex(Double ieHex);
	public Integer getIeMethodAcid();
	public void setIeMethodAcid(Integer ieMethodAcid);
	public String getIeAppear();
	public void setIeAppear(String ieAppear);
	public Double getWaterIeNaC();
	public void setWaterIeNaC(Double waterIeNaC);
	public Double getWaterIeForm();
	public void setWaterIeForm(Double waterIeForm);
	public String getWaterIeCaQ();
	public void setWaterIeCaQ(String waterIeCaQ);
	public Double getWaterIeProC();
	public void setWaterIeProC(Double waterIeProC);
	public Double getWaterIeCaC();
	public void setWaterIeCaC(Double waterIeCaC);
	public Double getIeButyC();
	public void setIeButyC(Double ieButyC);
	public Double getWaterIeMoC();
	public void setWaterIeMoC(Double waterIeMoC);
	public String getWaterIeMoQ();
	public void setWaterIeMoQ(String waterIeMoQ);
	public String getIeButyQ();
	public void setIeButyQ(String ieButyQ);
	public String getWaterIeNaQ();
	public void setWaterIeNaQ(String waterIeNaQ);
	public Double getWaterIeGlycC();
	public void setWaterIeGlycC(Double waterIeGlycC);
	public Double getIeMalonC();
	public void setIeMalonC(Double ieMalonC);
	public String getWaterIeGlycQ();
	public void setWaterIeGlycQ(String waterIeGlycQ);
	public String getWaterIeCrQ();
	public void setWaterIeCrQ(String waterIeCrQ);
	public String getIeNo3Q();
	public void setIeNo3Q(String ieNo3Q);
	public Double getWaterIeCrC();
	public void setWaterIeCrC(Double waterIeCrC);
	public String getWaterIeProQ();
	public void setWaterIeProQ(String waterIeProQ);
	public Double getIeNo3C();
	public void setIeNo3C(Double ieNo3C);
	public String getIeMalonQ();
	public void setIeMalonQ(String ieMalonQ);
	public Double getWaterIeVal();
	public void setWaterIeVal(Double waterIeVal);
	public String getIeHco3Q();
	public void setIeHco3Q(String ieHco3Q);
	public Double getIeHco3C();
	public void setIeHco3C(Double ieHco3C);
	public Integer getIeMethodAnion();
	public void setIeMethodAnion(Integer ieMethodAnion);
	public Double getWaterIePb();
	public void setWaterIePb(Double waterIePb);
	public String getWaterIeQc();
	public void setWaterIeQc(String waterIeQc);
	public Double getWaterIeButyC();
	public void setWaterIeButyC(Double waterIeButyC);
	public String getWaterIeMgQ();
	public void setWaterIeMgQ(String waterIeMgQ);
	public String getWaterIePo4Q();
	public void setWaterIePo4Q(String waterIePo4Q);
	public Double getWaterIeMgC();
	public void setWaterIeMgC(Double waterIeMgC);
	public String getWaterIeButyQ();
	public void setWaterIeButyQ(String waterIeButyQ);
	public Double getWaterIeLi();
	public void setWaterIeLi(Double waterIeLi);
	public Double getWaterIeMg();
	public void setWaterIeMg(Double waterIeMg);
	public Double getWaterIeMn();
	public void setWaterIeMn(Double waterIeMn);
	public Double getWaterIeMo();
	public void setWaterIeMo(Double waterIeMo);
	public Double getWaterIeNa();
	public void setWaterIeNa(Double waterIeNa);
	public Double getIeCarb();
	public void setIeCarb(Double ieCarb);
	public Double getWaterIeNi();
	public void setWaterIeNi(Double waterIeNi);
	public Date getWaterIeDate();
	public void setWaterIeDate(Date waterIeDate);
	public String getIeCo3Q();
	public void setIeCo3Q(String ieCo3Q);
	public Double getIeCo3C();
	public void setIeCo3C(Double ieCo3C);
	public Double getWaterIeZn();
	public void setWaterIeZn(Double waterIeZn);
	public Integer getWaterIeMethodCation();
	public void setWaterIeMethodCation(Integer waterIeMethodCation);
	public String getIeAceQ();
	public void setIeAceQ(String ieAceQ);
	public Double getWaterIeSi();
	public void setWaterIeSi(Double waterIeSi);
	public Double getIeAceC();
	public void setIeAceC(Double ieAceC);
	public String getIeUpdatedUser();
	public void setIeUpdatedUser(String ieUpdatedUser);
	public Double getWaterIeSr();
	public void setWaterIeSr(Double waterIeSr);
	public Double getIeVal();
	public void setIeVal(Double ieVal);
	public Date getIeQcDate();
	public void setIeQcDate(Date ieQcDate);
	public Double getWaterIeSo4();
	public void setWaterIeSo4(Double waterIeSo4);
	public String getWaterIeSiQ();
	public void setWaterIeSiQ(String waterIeSiQ);
	public Double getIeH2sC();
	public void setIeH2sC(Double ieH2sC);
	public Double getIeSo4C();
	public void setIeSo4C(Double ieSo4C);
	public Double getWaterIeSiC();
	public void setWaterIeSiC(Double waterIeSiC);
	public Double getWaterIeAlk();
	public void setWaterIeAlk(Double waterIeAlk);
	public String getIeH2sQ();
	public void setIeH2sQ(String ieH2sQ);
	public Double getIeAce();
	public void setIeAce(Double ieAce);
	public String getIeSo4Q();
	public void setIeSo4Q(String ieSo4Q);
	public Double getWaterIeIC();
	public void setWaterIeIC(Double waterIeIC);
	public String getIeCitricQ();
	public void setIeCitricQ(String ieCitricQ);
	public Double getWaterIeBa();
	public void setWaterIeBa(Double waterIeBa);
	public String getWaterIeIQ();
	public void setWaterIeIQ(String waterIeIQ);
	public Double getIeNitriteC();
	public void setIeNitriteC(Double ieNitriteC);
	public Double getIeForm();
	public void setIeForm(Double ieForm);
	public Double getWaterIeNh34C();
	public void setWaterIeNh34C(Double waterIeNh34C);
	public String getIeNitriteQ();
	public void setIeNitriteQ(String ieNitriteQ);
	public Double getIeNh34C();
	public void setIeNh34C(Double ieNh34C);
	public String getWaterIeNh34Q();
	public void setWaterIeNh34Q(String waterIeNh34Q);
	public String getWaterSampleIdVend();
	public void setWaterSampleIdVend(String waterSampleIdVend);
	public String getIeNh34Q();
	public void setIeNh34Q(String ieNh34Q);
	public Double getWaterIeNo3();
	public void setWaterIeNo3(Double waterIeNo3);
	public Double getWaterIeVC();
	public void setWaterIeVC(Double waterIeVC);
	public Double getWaterIeNh34();
	public void setWaterIeNh34(Double waterIeNh34);
	public Date getIeCreatedDate();
	public void setIeCreatedDate(Date ieCreatedDate);
	public Double getWaterIeLiC();
	public void setWaterIeLiC(Double waterIeLiC);
	public Double getWaterIeZnC();
	public void setWaterIeZnC(Double waterIeZnC);
	public Double getIeAlk();
	public void setIeAlk(Double ieAlk);
	public String getWaterIeVQ();
	public void setWaterIeVQ(String waterIeVQ);
	public Double getIeAlkC();
	public void setIeAlkC(Double ieAlkC);
	public String getIeAlkQ();
	public void setIeAlkQ(String ieAlkQ);
	public String getWaterIeCoQ();
	public void setWaterIeCoQ(String waterIeCoQ);
	public Double getWaterIeBr();
	public void setWaterIeBr(Double waterIeBr);
	public Double getWaterIePo4C();
	public void setWaterIePo4C(Double waterIePo4C);
	public Double getWaterIeCd();
	public void setWaterIeCd(Double waterIeCd);
	public Double getWaterIeCoC();
	public void setWaterIeCoC(Double waterIeCoC);
	public Double getWaterIeCa();
	public void setWaterIeCa(Double waterIeCa);
	public Double getWaterIeCl();
	public void setWaterIeCl(Double waterIeCl);
	public Double getWaterIeCo();
	public void setWaterIeCo(Double waterIeCo);
	public Double getWaterIeCu();
	public void setWaterIeCu(Double waterIeCu);
	public Double getWaterIeCr();
	public void setWaterIeCr(Double waterIeCr);
	public Double getWaterIeFe();
	public void setWaterIeFe(Double waterIeFe);
	public String getWaterIeSQ();
	public void setWaterIeSQ(String waterIeSQ);
	public String getWaterIeBQ();
	public void setWaterIeBQ(String waterIeBQ);
	public Double getWaterIeBC();
	public void setWaterIeBC(Double waterIeBC);
	public Double getIeNo3();
	public void setIeNo3(Double ieNo3);
	public Double getWaterIeNitriteC();
	public void setWaterIeNitriteC(Double waterIeNitriteC);
	public String getWaterIeNitriteQ();
	public void setWaterIeNitriteQ(String waterIeNitriteQ);
	public String getIeFormQ();
	public void setIeFormQ(String ieFormQ);
	public Double getIeFormC();
	public void setIeFormC(Double ieFormC);
	public Double getWaterIeButy();
	public void setWaterIeButy(Double waterIeButy);
	public String getWaterIeZnQ();
	public void setWaterIeZnQ(String waterIeZnQ);
	public String getWaterIeLiQ();
	public void setWaterIeLiQ(String waterIeLiQ);
	public String getWaterRequestIdVend();
	public void setWaterRequestIdVend(String waterRequestIdVend);
	public String getWaterIeSrQ();
	public void setWaterIeSrQ(String waterIeSrQ);
	public Double getWaterIeSrC();
	public void setWaterIeSrC(Double waterIeSrC);
	public Double getWaterIeCo3C();
	public void setWaterIeCo3C(Double waterIeCo3C);
	public String getWaterIeNo3Q();
	public void setWaterIeNo3Q(String waterIeNo3Q);
	public String getWaterIeCo3Q();
	public void setWaterIeCo3Q(String waterIeCo3Q);
	public String getWaterIeAceQ();
	public void setWaterIeAceQ(String waterIeAceQ);
	public Double getWaterIeH2s();
	public void setWaterIeH2s(Double waterIeH2s);
	public Double getWaterIeAceC();
	public void setWaterIeAceC(Double waterIeAceC);
	public Double getWaterIeNo3C();
	public void setWaterIeNo3C(Double waterIeNo3C);
	public String getIeValQ();
	public void setIeValQ(String ieValQ);
	public Double getIeValC();
	public void setIeValC(Double ieValC);
	public Date getIeUpdatedDate();
	public void setIeUpdatedDate(Date ieUpdatedDate);
	public Double getWaterIeKC();
	public void setWaterIeKC(Double waterIeKC);
	public Double getWaterIeCo3();
	public void setWaterIeCo3(Double waterIeCo3);
	public Integer getWaterIeMethodAnion();
	public void setWaterIeMethodAnion(Integer waterIeMethodAnion);
	public Double getWaterIeNitrite();
	public void setWaterIeNitrite(Double waterIeNitrite);
	public Double getIeNh34();
	public void setIeNh34(Double ieNh34);
	public String getWaterIeFQ();
	public void setWaterIeFQ(String waterIeFQ);
	public Double getWaterIeFC();
	public void setWaterIeFC(Double waterIeFC);
	public Double getIeSo4();
	public void setIeSo4(Double ieSo4);
	public String getIeOxalQ();
	public void setIeOxalQ(String ieOxalQ);
	public String getWaterIeClQ();
	public void setWaterIeClQ(String waterIeClQ);
	public Double getIeNitrite();
	public void setIeNitrite(Double ieNitrite);
	public Double getWaterIeClC();
	public void setWaterIeClC(Double waterIeClC);
	public String getIeCreatedUser();
	public void setIeCreatedUser(String ieCreatedUser);
	public Double getIeOxalC();
	public void setIeOxalC(Double ieOxalC);
	public Double getIeMalon();
	public void setIeMalon(Double ieMalon);
	public Double getWaterIeHco3C();
	public void setWaterIeHco3C(Double waterIeHco3C);
	public String getWaterIeHco3Q();
	public void setWaterIeHco3Q(String waterIeHco3Q);
	public Integer getIeMethodCation();
	public void setIeMethodCation(Integer ieMethodCation);
	public Double getIeButy();
	public void setIeButy(Double ieButy);
	public Double getWaterIeSC();
	public void setWaterIeSC(Double waterIeSC);
	public Double getWaterIeGlyc();
	public void setWaterIeGlyc(Double waterIeGlyc);
	public String getIeRequestIdVend();
	public void setIeRequestIdVend(String ieRequestIdVend);
	public Double getWaterIeCuC();
	public void setWaterIeCuC(Double waterIeCuC);
	public String getWaterIeCuQ();
	public void setWaterIeCuQ(String waterIeCuQ);
	public String getWaterIeValQ();
	public void setWaterIeValQ(String waterIeValQ);
	public Double getWaterIeHco3();
	public void setWaterIeHco3(Double waterIeHco3);
	public Double getWaterIeValC();
	public void setWaterIeValC(Double waterIeValC);
	public Double getWaterIeCdC();
	public void setWaterIeCdC(Double waterIeCdC);
	public String getWaterIeCdQ();
	public void setWaterIeCdQ(String waterIeCdQ);
	public String getWaterIeAuthor();
	public void setWaterIeAuthor(String waterIeAuthor);
	public Double getIeProC();
	public void setIeProC(Double ieProC);
	public String getIeProQ();
	public void setIeProQ(String ieProQ);
	public Double getIeOxal();
	public void setIeOxal(Double ieOxal);
	public String getWaterIeLab();
	public void setWaterIeLab(String waterIeLab);
	public Integer getIeMethodSulf();
	public void setIeMethodSulf(Integer ieMethodSulf);
	public Double getWaterIeFeC();
	public void setWaterIeFeC(Double waterIeFeC);
	public String getWaterIeKQ();
	public void setWaterIeKQ(String waterIeKQ);
	public Double getWaterIeSo4C();
	public void setWaterIeSo4C(Double waterIeSo4C);
	public String getWaterIeSo4Q();
	public void setWaterIeSo4Q(String waterIeSo4Q);
	public String getWaterIeH2sQ();
	public void setWaterIeH2sQ(String waterIeH2sQ);
	public String getWaterIeFeQ();
	public void setWaterIeFeQ(String waterIeFeQ);
	public Double getWaterIeH2sC();
	public void setWaterIeH2sC(Double waterIeH2sC);
	public Double getWaterIeBaC();
	public void setWaterIeBaC(Double waterIeBaC);
	public Double getWaterIePo4();
	public void setWaterIePo4(Double waterIePo4);
	public String getWaterIeBrQ();
	public void setWaterIeBrQ(String waterIeBrQ);
	public Double getWaterIeBrC();
	public void setWaterIeBrC(Double waterIeBrC);
	public String getWaterIeBaQ();
	public void setWaterIeBaQ(String waterIeBaQ);
	public String getWaterIeFormQ();
	public void setWaterIeFormQ(String waterIeFormQ);
	public Double getWaterIeFormC();
	public void setWaterIeFormC(Double waterIeFormC);
	public String getWaterIeAlkQ();
	public void setWaterIeAlkQ(String waterIeAlkQ);
	public Double getWaterIePro();
	public void setWaterIePro(Double waterIePro);
	public Double getIeCo3();
	public void setIeCo3(Double ieCo3);
	public Double getIeGlyc();
	public void setIeGlyc(Double ieGlyc);
	public Double getWaterIeAlkC();
	public void setWaterIeAlkC(Double waterIeAlkC);
	public String getWaterIePbQ();
	public void setWaterIePbQ(String waterIePbQ);
	public Double getWaterIePbC();
	public void setWaterIePbC(Double waterIePbC);
	public Double getIeH2s();
	public void setIeH2s(Double ieH2s);
	public Double getWaterIeMnC();
	public void setWaterIeMnC(Double waterIeMnC);
	public String getWaterIeMnQ();
	public void setWaterIeMnQ(String waterIeMnQ);
	public Double getWaterIeK();
	public void setWaterIeK(Double waterIeK);
	public Double getWaterIeS();
	public void setWaterIeS(Double waterIeS);
	public Double getWaterIeV();
	public void setWaterIeV(Double waterIeV);
	public Double getWaterIeB();
	public void setWaterIeB(Double waterIeB);
	public Double getWaterIeF();
	public void setWaterIeF(Double waterIeF);
	public Double getWaterIeI();
	public void setWaterIeI(Double waterIeI);
}
