package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOOilSara extends GTOAnalysisData {
	public Double getSaraResinTop();
	public void setSaraResinTop(Double saraResinTop);
	public String getSaraComments();
	public void setSaraComments(String saraComments);
	public Double getSaraNsoMg();
	public void setSaraNsoMg(Double saraNsoMg);
	public Double getSaraAroMg();
	public void setSaraAroMg(Double saraAroMg);
	public Double getSaraTopRat();
	public void setSaraTopRat(Double saraTopRat);
	public Double getSaraAsphPct();
	public void setSaraAsphPct(Double saraAsphPct);
	public String getSaraSampleIdVend();
	public void setSaraSampleIdVend(String saraSampleIdVend);
	public String getSaraQcUser();
	public void setSaraQcUser(String saraQcUser);
	public Double getSaraNs0Top();
	public void setSaraNs0Top(Double saraNs0Top);
	public Date getSaraQcDate();
	public void setSaraQcDate(Date saraQcDate);
	public Double getSaraAroPct();
	public void setSaraAroPct(Double saraAroPct);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Date getSaraAcqDate();
	public void setSaraAcqDate(Date saraAcqDate);
	public Date getSaraLastUpdate();
	public void setSaraLastUpdate(Date saraLastUpdate);
	public String getSaraQc();
	public void setSaraQc(String saraQc);
	public Double getSaraConf();
	public void setSaraConf(Double saraConf);
	public String getSaraJobId();
	public void setSaraJobId(String saraJobId);
	public Double getSaraAsphMg();
	public void setSaraAsphMg(Double saraAsphMg);
	public String getSaraLab();
	public void setSaraLab(String saraLab);
	public Double getSaraNsoPct();
	public void setSaraNsoPct(Double saraNsoPct);
	public String getSaraMethod();
	public void setSaraMethod(String saraMethod);
	public String getSaraAuthor();
	public void setSaraAuthor(String saraAuthor);
	public Double getSaraSatMg();
	public void setSaraSatMg(Double saraSatMg);
	public Double getSaraNsoWho();
	public void setSaraNsoWho(Double saraNsoWho);
	public Double getSaraAsphWho();
	public void setSaraAsphWho(Double saraAsphWho);
	public String getSaraSvcCode();
	public void setSaraSvcCode(String saraSvcCode);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getSaraAsphTop();
	public void setSaraAsphTop(Double saraAsphTop);
	public Double getSaraSatPct();
	public void setSaraSatPct(Double saraSatPct);
	public String getSaraIqmCode();
	public void setSaraIqmCode(String saraIqmCode);
	public String getSaraRunNumber();
	public void setSaraRunNumber(String saraRunNumber);
	public Double getSaraResinWho();
	public void setSaraResinWho(Double saraResinWho);
	public Double getSaraSampMg();
	public void setSaraSampMg(Double saraSampMg);
	public Date getSaraUpdatedDate();
	public void setSaraUpdatedDate(Date saraUpdatedDate);
	public Double getSaraTopTime();
	public void setSaraTopTime(Double saraTopTime);
	public Date getSaraCreatedDate();
	public void setSaraCreatedDate(Date saraCreatedDate);
	public Double getSaraResidueWt();
	public void setSaraResidueWt(Double saraResidueWt);
	public String getSaraIqmFlag();
	public void setSaraIqmFlag(String saraIqmFlag);
	public Double getSaraResidualPct();
	public void setSaraResidualPct(Double saraResidualPct);
	public String getSaraCreatedUser();
	public void setSaraCreatedUser(String saraCreatedUser);
	public String getSaraQcFlag();
	public void setSaraQcFlag(String saraQcFlag);
	public Double getSaraPrecipTime();
	public void setSaraPrecipTime(Double saraPrecipTime);
	public Double getSaraTopPct();
	public void setSaraTopPct(Double saraTopPct);
	public Double getSaraOilPct();
	public void setSaraOilPct(Double saraOilPct);
	public String getSaraUpdatedUser();
	public void setSaraUpdatedUser(String saraUpdatedUser);
	public Double getSaraNsoTop();
	public void setSaraNsoTop(Double saraNsoTop);
}
