package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOOilVisc extends GTOAnalysisData {
	public String getViscJobId();
	public void setViscJobId(String viscJobId);
	public Double getViscConf();
	public void setViscConf(Double viscConf);
	public String getViscComments();
	public void setViscComments(String viscComments);
	public Date getViscLastUpdate();
	public void setViscLastUpdate(Date viscLastUpdate);
	public Integer getViscTemperature();
	public void setViscTemperature(Integer viscTemperature);
	public String getViscLab();
	public void setViscLab(String viscLab);
	public Date getViscQcDate();
	public void setViscQcDate(Date viscQcDate);
	public String getViscRunNumber();
	public void setViscRunNumber(String viscRunNumber);
	public String getViscMethod();
	public void setViscMethod(String viscMethod);
	public Double getViscValue();
	public void setViscValue(Double viscValue);
	public String getViscAuthor();
	public void setViscAuthor(String viscAuthor);
	public String getViscSampleIdVend();
	public void setViscSampleIdVend(String viscSampleIdVend);
	public String getViscQcUser();
	public void setViscQcUser(String viscQcUser);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getViscQc();
	public void setViscQc(String viscQc);
	public String getViscSvcCode();
	public void setViscSvcCode(String viscSvcCode);
	public String getViscValueQualifier();
	public void setViscValueQualifier(String viscValueQualifier);
	public String getViscIqmCode();
	public void setViscIqmCode(String viscIqmCode);
	public String getViscUnits();
	public void setViscUnits(String viscUnits);
	public Date getViscAcqDate();
	public void setViscAcqDate(Date viscAcqDate);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Date getViscDate();
	public void setViscDate(Date viscDate);
	public String getViscQual();
	public void setViscQual(String viscQual);
	public String getViscTempUnits();
	public void setViscTempUnits(String viscTempUnits);
	public String getViscQcFlag();
	public void setViscQcFlag(String viscQcFlag);
	public Integer getViscOpid();
	public void setViscOpid(Integer viscOpid);
	public String getViscLabpage();
	public void setViscLabpage(String viscLabpage);
	public String getViscCreatedUser();
	public void setViscCreatedUser(String viscCreatedUser);
	public Date getViscUpdatedDate();
	public void setViscUpdatedDate(Date viscUpdatedDate);
	public String getViscLabref();
	public void setViscLabref(String viscLabref);
	public Date getViscCreatedDate();
	public void setViscCreatedDate(Date viscCreatedDate);
	public String getViscUpdatedUser();
	public void setViscUpdatedUser(String viscUpdatedUser);
	public String getViscRequestIdVend();
	public void setViscRequestIdVend(String viscRequestIdVend);
}
