package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOOilWax extends GTOAnalysisData {
	public Double getWaxValue();
	public void setWaxValue(Double waxValue);
	public String getWaxLab();
	public void setWaxLab(String waxLab);
	public String getWaxHtIqmCode();
	public void setWaxHtIqmCode(String waxHtIqmCode);
	public String getWaxJobId();
	public void setWaxJobId(String waxJobId);
	public String getWaxAuthor();
	public void setWaxAuthor(String waxAuthor);
	public Date getWaxDate();
	public void setWaxDate(Date waxDate);
	public String getWaxComment();
	public void setWaxComment(String waxComment);
	public Double getWaxConf();
	public void setWaxConf(Double waxConf);
	public Date getWaxLastUpdate();
	public void setWaxLastUpdate(Date waxLastUpdate);
	public String getWaxMethod();
	public void setWaxMethod(String waxMethod);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getWaxHtQcUser();
	public void setWaxHtQcUser(String waxHtQcUser);
	public String getWaxSampleIdVend();
	public void setWaxSampleIdVend(String waxSampleIdVend);
	public Date getWaxAcqDate();
	public void setWaxAcqDate(Date waxAcqDate);
	public String getWaxRunNumber();
	public void setWaxRunNumber(String waxRunNumber);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getWaxSvcCode();
	public void setWaxSvcCode(String waxSvcCode);
	public String getWaxValueQualifier();
	public void setWaxValueQualifier(String waxValueQualifier);
	public Date getWaxHtQcDate();
	public void setWaxHtQcDate(Date waxHtQcDate);
	public String getWaxQc();
	public void setWaxQc(String waxQc);
	public Integer getWaxTemp();
	public void setWaxTemp(Integer waxTemp);
	public Date getWaxQcDate();
	public void setWaxQcDate(Date waxQcDate);
	public String getWaxIqmCode();
	public void setWaxIqmCode(String waxIqmCode);
	public String getWaxLabrefPage();
	public void setWaxLabrefPage(String waxLabrefPage);
	public String getWaxQual();
	public void setWaxQual(String waxQual);
	public String getWaxLabref();
	public void setWaxLabref(String waxLabref);
	public String getWaxTempUnits();
	public void setWaxTempUnits(String waxTempUnits);
	public String getWaxCreatedUser();
	public void setWaxCreatedUser(String waxCreatedUser);
	public String getWaxQcUser();
	public void setWaxQcUser(String waxQcUser);
	public String getWaxUpdatedUser();
	public void setWaxUpdatedUser(String waxUpdatedUser);
	public Date getWaxCreatedDate();
	public void setWaxCreatedDate(Date waxCreatedDate);
}
