package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOOilCloudpoint extends GTOAnalysisData {
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getCpMethodStd();
	public void setCpMethodStd(String cpMethodStd);
	public Double getCpValueStd();
	public void setCpValueStd(Double cpValueStd);
	public Date getCpCreatedDate();
	public void setCpCreatedDate(Date cpCreatedDate);
	public String getCpMethodOth();
	public void setCpMethodOth(String cpMethodOth);
	public Double getCpValueOth();
	public void setCpValueOth(Double cpValueOth);
	public Double getCpConfExt();
	public void setCpConfExt(Double cpConfExt);
	public String getCpQcUser();
	public void setCpQcUser(String cpQcUser);
	public String getCpQcFlag();
	public void setCpQcFlag(String cpQcFlag);
	public String getCpMethodExt();
	public void setCpMethodExt(String cpMethodExt);
	public String getCpRunNumber();
	public void setCpRunNumber(String cpRunNumber);
	public Date getCpQcDate();
	public void setCpQcDate(Date cpQcDate);
	public String getCpCreatedUser();
	public void setCpCreatedUser(String cpCreatedUser);
	public String getCpTempUnits();
	public void setCpTempUnits(String cpTempUnits);
	public String getCpSvcCode();
	public void setCpSvcCode(String cpSvcCode);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getCpLab();
	public void setCpLab(String cpLab);
	public String getCpQualStd();
	public void setCpQualStd(String cpQualStd);
	public Date getCpAcqDate();
	public void setCpAcqDate(Date cpAcqDate);
	public String getCpQualOth();
	public void setCpQualOth(String cpQualOth);
	public Double getCpConfStd();
	public void setCpConfStd(Double cpConfStd);
	public Double getCpConfOth();
	public void setCpConfOth(Double cpConfOth);
	public Date getCpUpdatedDate();
	public void setCpUpdatedDate(Date cpUpdatedDate);
	public String getCpIqmCode();
	public void setCpIqmCode(String cpIqmCode);
	public String getCpQualExt();
	public void setCpQualExt(String cpQualExt);
	public String getCpAuthor();
	public void setCpAuthor(String cpAuthor);
	public String getCpSampleIdVend();
	public void setCpSampleIdVend(String cpSampleIdVend);
	public Double getCpValueExt();
	public void setCpValueExt(Double cpValueExt);
	public String getCpComments();
	public void setCpComments(String cpComments);
	public String getCpUpdatedUser();
	public void setCpUpdatedUser(String cpUpdatedUser);
	public String getCpLabrefPageExt();
	public void setCpLabrefPageExt(String cpLabrefPageExt);
	public String getCpRequestIdVend();
	public void setCpRequestIdVend(String cpRequestIdVend);
	public String getCpLabrefExt();
	public void setCpLabrefExt(String cpLabrefExt);
	public String getCpLabrefOth();
	public void setCpLabrefOth(String cpLabrefOth);
	public String getCpLabrefStd();
	public void setCpLabrefStd(String cpLabrefStd);
	public String getCpLabrefPageStd();
	public void setCpLabrefPageStd(String cpLabrefPageStd);
	public String getCpLabrefPageOth();
	public void setCpLabrefPageOth(String cpLabrefPageOth);
	public String getCpIqmFlag();
	public void setCpIqmFlag(String cpIqmFlag);
}
