package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOPistonCore extends GTOAnalysisData {
	public Double getHg13cCo2();
	public void setHg13cCo2(Double hg13cCo2);
	public Integer getGcUcmGNC2();
	public void setGcUcmGNC2(Integer gcUcmGNC2);
	public Double getAg13cNeoPent();
	public void setAg13cNeoPent(Double ag13cNeoPent);
	public Double getHg13cPropene();
	public void setHg13cPropene(Double hg13cPropene);
	public Double getAg13cNPentane();
	public void setAg13cNPentane(Double ag13cNPentane);
	public Integer getTsfMaxInt();
	public void setTsfMaxInt(Integer tsfMaxInt);
	public Double getHg13cNButane();
	public void setHg13cNButane(Double hg13cNButane);
	public Date getPcLastUpdate();
	public void setPcLastUpdate(Date pcLastUpdate);
	public Double getHg13cMethane();
	public void setHg13cMethane(Double hg13cMethane);
	public String getPcSvcCode();
	public void setPcSvcCode(String pcSvcCode);
	public String getPcQcFlag();
	public void setPcQcFlag(String pcQcFlag);
	public Double getAgCo2();
	public void setAgCo2(Double agCo2);
	public Double getHg13cButenes();
	public void setHg13cButenes(Double hg13cButenes);
	public Double getHg13cNeoPent();
	public void setHg13cNeoPent(Double hg13cNeoPent);
	public Double getAg13cNButane();
	public void setAg13cNButane(Double ag13cNButane);
	public String getPcJobId();
	public void setPcJobId(String pcJobId);
	public Double getHgRmudHs();
	public void setHgRmudHs(Double hgRmudHs);
	public Double getHgDmud();
	public void setHgDmud(Double hgDmud);
	public Double getAg13cPropene();
	public void setAg13cPropene(Double ag13cPropene);
	public Double getHg13cEthane();
	public void setHg13cEthane(Double hg13cEthane);
	public Double getGcPristane();
	public void setGcPristane(Double gcPristane);
	public Double getHgCo2();
	public void setHgCo2(Double hgCo2);
	public Double getAgMethane();
	public void setAgMethane(Double agMethane);
	public Double getHgEthene();
	public void setHgEthene(Double hgEthene);
	public Double getAgIButane();
	public void setAgIButane(Double agIButane);
	public Double getHg13cIButane();
	public void setHg13cIButane(Double hg13cIButane);
	public String getPcIqmCode();
	public void setPcIqmCode(String pcIqmCode);
	public Double getAgNeoPent();
	public void setAgNeoPent(Double agNeoPent);
	public Double getAg13cButenes();
	public void setAg13cButenes(Double ag13cButenes);
	public Double getHgNPentane();
	public void setHgNPentane(Double hgNPentane);
	public Integer getTsfMaxEx();
	public void setTsfMaxEx(Integer tsfMaxEx);
	public Integer getGcUcmLC23();
	public void setGcUcmLC23(Integer gcUcmLC23);
	public Integer getTsfMaxEm();
	public void setTsfMaxEm(Integer tsfMaxEm);
	public Double getAgNButane();
	public void setAgNButane(Double agNButane);
	public Double getHg13cNPentane();
	public void setHg13cNPentane(Double hg13cNPentane);
	public Double getHgNeoPent();
	public void setHgNeoPent(Double hgNeoPent);
	public Double getAg13cEthane();
	public void setAg13cEthane(Double ag13cEthane);
	public Double getAg13cPropane();
	public void setAg13cPropane(Double ag13cPropane);
	public Double getAgNPentane();
	public void setAgNPentane(Double agNPentane);
	public Double getHgEthane();
	public void setHgEthane(Double hgEthane);
	public Double getAgPropane();
	public void setAgPropane(Double agPropane);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getHgMethane();
	public void setHgMethane(Double hgMethane);
	public Double getTsfR1();
	public void setTsfR1(Double tsfR1);
	public Double getHg13cEthene();
	public void setHg13cEthene(Double hg13cEthene);
	public Double getAgIPentane();
	public void setAgIPentane(Double agIPentane);
	public Double getHgPropene();
	public void setHgPropene(Double hgPropene);
	public Double getHgButenes();
	public void setHgButenes(Double hgButenes);
	public String getPcRunNumber();
	public void setPcRunNumber(String pcRunNumber);
	public Double getAgEthene();
	public void setAgEthene(Double agEthene);
	public Double getAg13cCo2();
	public void setAg13cCo2(Double ag13cCo2);
	public Integer getGcUcmTotal();
	public void setGcUcmTotal(Integer gcUcmTotal);
	public Double getHgIPentane();
	public void setHgIPentane(Double hgIPentane);
	public Double getHgIButane();
	public void setHgIButane(Double hgIButane);
	public Double getAg13cEthene();
	public void setAg13cEthene(Double ag13cEthene);
	public String getTsfDatafile();
	public void setTsfDatafile(String tsfDatafile);
	public Double getAgPropene();
	public void setAgPropene(Double agPropene);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getAg13cMethane();
	public void setAg13cMethane(Double ag13cMethane);
	public Double getAgButenes();
	public void setAgButenes(Double agButenes);
	public Double getHgNButane();
	public void setHgNButane(Double hgNButane);
	public Double getAg13cIButane();
	public void setAg13cIButane(Double ag13cIButane);
	public Double getAg13cIPentane();
	public void setAg13cIPentane(Double ag13cIPentane);
	public Date getPcQcDate();
	public void setPcQcDate(Date pcQcDate);
	public Double getHgPropane();
	public void setHgPropane(Double hgPropane);
	public Double getHg13cPropane();
	public void setHg13cPropane(Double hg13cPropane);
	public Double getHg13cIPentane();
	public void setHg13cIPentane(Double hg13cIPentane);
	public String getPcQcUser();
	public void setPcQcUser(String pcQcUser);
	public Double getGcNC30();
	public void setGcNC30(Double gcNC30);
	public Double getGcNC31();
	public void setGcNC31(Double gcNC31);
	public Double getGcNC32();
	public void setGcNC32(Double gcNC32);
	public Double getGcNC33();
	public void setGcNC33(Double gcNC33);
	public Double getGcNC34();
	public void setGcNC34(Double gcNC34);
	public Double getGcNC35();
	public void setGcNC35(Double gcNC35);
	public Double getGcNC36();
	public void setGcNC36(Double gcNC36);
	public Double getAgEthane();
	public void setAgEthane(Double agEthane);
	public Double getGcNC37();
	public void setGcNC37(Double gcNC37);
	public Double getGcNC38();
	public void setGcNC38(Double gcNC38);
	public Double getGcNC39();
	public void setGcNC39(Double gcNC39);
	public Double getGcNC40();
	public void setGcNC40(Double gcNC40);
	public Double getGcNC10();
	public void setGcNC10(Double gcNC10);
	public Double getGcNC11();
	public void setGcNC11(Double gcNC11);
	public Double getGcNC12();
	public void setGcNC12(Double gcNC12);
	public Double getGcNC13();
	public void setGcNC13(Double gcNC13);
	public Double getGcNC14();
	public void setGcNC14(Double gcNC14);
	public Double getGcNC15();
	public void setGcNC15(Double gcNC15);
	public Double getGcNC16();
	public void setGcNC16(Double gcNC16);
	public Double getGcNC17();
	public void setGcNC17(Double gcNC17);
	public Double getGcNC18();
	public void setGcNC18(Double gcNC18);
	public Double getGcNC19();
	public void setGcNC19(Double gcNC19);
	public Double getGcNC20();
	public void setGcNC20(Double gcNC20);
	public Double getGcNC21();
	public void setGcNC21(Double gcNC21);
	public Double getGcNC22();
	public void setGcNC22(Double gcNC22);
	public Double getGcNC23();
	public void setGcNC23(Double gcNC23);
	public Double getGcNC24();
	public void setGcNC24(Double gcNC24);
	public Double getGcNC25();
	public void setGcNC25(Double gcNC25);
	public Double getGcNC26();
	public void setGcNC26(Double gcNC26);
	public Double getGcNC27();
	public void setGcNC27(Double gcNC27);
	public Double getGcNC28();
	public void setGcNC28(Double gcNC28);
	public Double getGcNC29();
	public void setGcNC29(Double gcNC29);
	public Double getGcPhytane();
	public void setGcPhytane(Double gcPhytane);
}
