package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTORockPyro extends GTOAnalysisData {
	public Double getRpS3bco();
	public void setRpS3bco(Double rpS3bco);
	public Date getRpLastUpdate();
	public void setRpLastUpdate(Date rpLastUpdate);
	public Integer getRpTminS2aS2b();
	public void setRpTminS2aS2b(Integer rpTminS2aS2b);
	public Double getRpOiCo2();
	public void setRpOiCo2(Double rpOiCo2);
	public String getRpComments();
	public void setRpComments(String rpComments);
	public String getRpRunNumber();
	public void setRpRunNumber(String rpRunNumber);
	public Date getRpQcDate();
	public void setRpQcDate(Date rpQcDate);
	public Double getRpS4co();
	public void setRpS4co(Double rpS4co);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getRpSampleIdVend();
	public void setRpSampleIdVend(String rpSampleIdVend);
	public Integer getRpHi();
	public void setRpHi(Integer rpHi);
	public Double getRpRcr();
	public void setRpRcr(Double rpRcr);
	public String getRpJobId();
	public void setRpJobId(String rpJobId);
	public String getRpQcUser();
	public void setRpQcUser(String rpQcUser);
	public String getRpQc();
	public void setRpQc(String rpQc);
	public Double getRpOiCo();
	public void setRpOiCo(Double rpOiCo);
	public Double getRpPi();
	public void setRpPi(Double rpPi);
	public Double getRpS5();
	public void setRpS5(Double rpS5);
	public Double getRpS3bco2();
	public void setRpS3bco2(Double rpS3bco2);
	public Integer getRpOi();
	public void setRpOi(Integer rpOi);
	public Double getRpS3b();
	public void setRpS3b(Double rpS3b);
	public Double getRpS2a();
	public void setRpS2a(Double rpS2a);
	public Double getRpS2b();
	public void setRpS2b(Double rpS2b);
	public Double getRpS2a400();
	public void setRpS2a400(Double rpS2a400);
	public String getRpSvcCode();
	public void setRpSvcCode(String rpSvcCode);
	public Integer getRpTmaxS3b();
	public void setRpTmaxS3b(Integer rpTmaxS3b);
	public Integer getRpTmaxS2b();
	public void setRpTmaxS2b(Integer rpTmaxS2b);
	public Integer getRpTmaxS2a();
	public void setRpTmaxS2a(Integer rpTmaxS2a);
	public Double getRpS4co2();
	public void setRpS4co2(Double rpS4co2);
	public String getRpMethod();
	public void setRpMethod(String rpMethod);
	public Date getRpAcqDate();
	public void setRpAcqDate(Date rpAcqDate);
	public String getRpIqmCode();
	public void setRpIqmCode(String rpIqmCode);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getRpGas();
	public void setRpGas(Double rpGas);
	public Double getRpMinc();
	public void setRpMinc(Double rpMinc);
	public Double getRpS2b400();
	public void setRpS2b400(Double rpS2b400);
	public Integer getRevTmax();
	public void setRevTmax(Integer revTmax);
	public String getRpLab();
	public void setRpLab(String rpLab);
	public Double getRevTots3();
	public void setRevTots3(Double revTots3);
	public Double getRevTots2();
	public void setRevTots2(Double revTots2);
	public Double getRevTots1();
	public void setRevTots1(Double revTots1);
	public Double getRpPcr();
	public void setRpPcr(Double rpPcr);
	public String getRpAuthor();
	public void setRpAuthor(String rpAuthor);
	public Integer getRpPrep();
	public void setRpPrep(Integer rpPrep);
	public Integer getRpMethodNew();
	public void setRpMethodNew(Integer rpMethodNew);
	public Integer getRpConfType();
	public void setRpConfType(Integer rpConfType);
	public Integer getRpUom();
	public void setRpUom(Integer rpUom);
	public Integer getRpRecordType();
	public void setRpRecordType(Integer rpRecordType);
}
