package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTORockMacerals extends GTOAnalysisData {
	public String getMacSampleIdVend();
	public void setMacSampleIdVend(String macSampleIdVend);
	public String getMacQc();
	public void setMacQc(String macQc);
	public Integer getMacLiptCutin();
	public void setMacLiptCutin(Integer macLiptCutin);
	public Integer getMacLiptSporiniteMega();
	public void setMacLiptSporiniteMega(Integer macLiptSporiniteMega);
	public Integer getMacInertScler();
	public void setMacInertScler(Integer macInertScler);
	public Integer getMacVit2DesmocolDetr();
	public void setMacVit2DesmocolDetr(Integer macVit2DesmocolDetr);
	public String getMacIqmCode();
	public void setMacIqmCode(String macIqmCode);
	public Integer getMacMineralPyrAggCryst();
	public void setMacMineralPyrAggCryst(Integer macMineralPyrAggCryst);
	public Integer getMacLiptSuber();
	public void setMacLiptSuber(Integer macLiptSuber);
	public String getMacJobId();
	public void setMacJobId(String macJobId);
	public String getMacMethod();
	public void setMacMethod(String macMethod);
	public String getMacBlock();
	public void setMacBlock(String macBlock);
	public String getMacSvcCode();
	public void setMacSvcCode(String macSvcCode);
	public Integer getMacInertFusin();
	public void setMacInertFusin(Integer macInertFusin);
	public String getMacLab();
	public void setMacLab(String macLab);
	public Integer getMacLiptAlgOthr();
	public void setMacLiptAlgOthr(Integer macLiptAlgOthr);
	public Integer getMacLiptAlgTasm();
	public void setMacLiptAlgTasm(Integer macLiptAlgTasm);
	public Integer getMacInert();
	public void setMacInert(Integer macInert);
	public Integer getMacLiptLipto();
	public void setMacLiptLipto(Integer macLiptLipto);
	public Integer getMacVit2DesmocolLayers();
	public void setMacVit2DesmocolLayers(Integer macVit2DesmocolLayers);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Date getMacQcDate();
	public void setMacQcDate(Date macQcDate);
	public Integer getMacLiptAlgBotr();
	public void setMacLiptAlgBotr(Integer macLiptAlgBotr);
	public Integer getMacSomLbLayers();
	public void setMacSomLbLayers(Integer macSomLbLayers);
	public Integer getMacVit1TelocolDetr();
	public void setMacVit1TelocolDetr(Integer macVit1TelocolDetr);
	public Integer getMacLiptAlgMicrPlanc();
	public void setMacLiptAlgMicrPlanc(Integer macLiptAlgMicrPlanc);
	public String getMacStandardComm();
	public void setMacStandardComm(String macStandardComm);
	public Integer getMacSomLbDens();
	public void setMacSomLbDens(Integer macSomLbDens);
	public String getMacQcUser();
	public void setMacQcUser(String macQcUser);
	public String getMacAuthor();
	public void setMacAuthor(String macAuthor);
	public Double getMacAmorphUnspecFl();
	public void setMacAmorphUnspecFl(Double macAmorphUnspecFl);
	public Date getMacAcqDate();
	public void setMacAcqDate(Date macAcqDate);
	public String getMacComment();
	public void setMacComment(String macComment);
	public String getMacComment2();
	public void setMacComment2(String macComment2);
	public Integer getMacLiptSporiniteMicro();
	public void setMacLiptSporiniteMicro(Integer macLiptSporiniteMicro);
	public Integer getMacVit1TelinDetr();
	public void setMacVit1TelinDetr(Integer macVit1TelinDetr);
	public Integer getMacVit();
	public void setMacVit(Integer macVit);
	public Integer getMacLiptExsudatFl();
	public void setMacLiptExsudatFl(Integer macLiptExsudatFl);
	public Integer getMacMineralPyrFram();
	public void setMacMineralPyrFram(Integer macMineralPyrFram);
	public String getMacSrType();
	public void setMacSrType(String macSrType);
	public Integer getMacLiptResin();
	public void setMacLiptResin(Integer macLiptResin);
	public String getMacSemiquan();
	public void setMacSemiquan(String macSemiquan);
	public Double getMacAmorphUnspec();
	public void setMacAmorphUnspec(Double macAmorphUnspec);
	public Integer getMacVit1TelocolLayers();
	public void setMacVit1TelocolLayers(Integer macVit1TelocolLayers);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Integer getMacSomUnspec();
	public void setMacSomUnspec(Integer macSomUnspec);
	public String getMacRunNumber();
	public void setMacRunNumber(String macRunNumber);
	public Integer getMacSomNlbDiff();
	public void setMacSomNlbDiff(Integer macSomNlbDiff);
	public Date getMacDate();
	public void setMacDate(Date macDate);
	public Integer getMacMineralUndef();
	public void setMacMineralUndef(Integer macMineralUndef);
	public Integer getMacLipt();
	public void setMacLipt(Integer macLipt);
	public Integer getMacVit1TelinLayers();
	public void setMacVit1TelinLayers(Integer macVit1TelinLayers);
	public Integer getMacLiptExsudatNonFl();
	public void setMacLiptExsudatNonFl(Integer macLiptExsudatNonFl);
	public Integer getMacSomLbLens();
	public void setMacSomLbLens(Integer macSomLbLens);
	public Integer getMacInertMicrin();
	public void setMacInertMicrin(Integer macInertMicrin);
}
