package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTORockMaceralsV2 extends GTOAnalysisData {
	public Integer getVkaLiptOthCutin();
	public void setVkaLiptOthCutin(Integer vkaLiptOthCutin);
	public Integer getVkaMinPyriteFram();
	public void setVkaMinPyriteFram(Integer vkaMinPyriteFram);
	public String getVkaOrgType();
	public void setVkaOrgType(String vkaOrgType);
	public String getVkaBlockNr();
	public void setVkaBlockNr(String vkaBlockNr);
	public Integer getVkaInert();
	public void setVkaInert(Integer vkaInert);
	public Integer getVkaVitTelo();
	public void setVkaVitTelo(Integer vkaVitTelo);
	public String getVkaRunNumber();
	public void setVkaRunNumber(String vkaRunNumber);
	public Date getVkaUpdatedDate();
	public void setVkaUpdatedDate(Date vkaUpdatedDate);
	public Integer getVkaPybIsoFlHigh();
	public void setVkaPybIsoFlHigh(Integer vkaPybIsoFlHigh);
	public Integer getVkaVitTeloTeli();
	public void setVkaVitTeloTeli(Integer vkaVitTeloTeli);
	public Integer getVkaLiptAmFl();
	public void setVkaLiptAmFl(Integer vkaLiptAmFl);
	public Integer getVkaPybIsoFlMed();
	public void setVkaPybIsoFlMed(Integer vkaPybIsoFlMed);
	public String getVkaAuthor();
	public void setVkaAuthor(String vkaAuthor);
	public Integer getVkaVitGeloCor();
	public void setVkaVitGeloCor(Integer vkaVitGeloCor);
	public String getVkaFile();
	public void setVkaFile(String vkaFile);
	public Integer getVkaVitDetro();
	public void setVkaVitDetro(Integer vkaVitDetro);
	public String getVkaIqmCode();
	public void setVkaIqmCode(String vkaIqmCode);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Integer getVkaZooclastForam();
	public void setVkaZooclastForam(Integer vkaZooclastForam);
	public Integer getVkaInertFusin();
	public void setVkaInertFusin(Integer vkaInertFusin);
	public Integer getVkaPybIsoFlLow();
	public void setVkaPybIsoFlLow(Integer vkaPybIsoFlLow);
	public Integer getVkaLiptAmFlLb();
	public void setVkaLiptAmFlLb(Integer vkaLiptAmFlLb);
	public Integer getVkaLiptAlgLamalg();
	public void setVkaLiptAlgLamalg(Integer vkaLiptAlgLamalg);
	public Integer getFkMethodId();
	public void setFkMethodId(Integer fkMethodId);
	public Integer getVkaTotal();
	public void setVkaTotal(Integer vkaTotal);
	public Integer getVkaInertSemifusin();
	public void setVkaInertSemifusin(Integer vkaInertSemifusin);
	public Integer getVkaLiptOthLipto();
	public void setVkaLiptOthLipto(Integer vkaLiptOthLipto);
	public Integer getVkaPybAnsLDomain();
	public void setVkaPybAnsLDomain(Integer vkaPybAnsLDomain);
	public Integer getVkaLiptOthResin();
	public void setVkaLiptOthResin(Integer vkaLiptOthResin);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Date getVkaDate();
	public void setVkaDate(Date vkaDate);
	public Integer getVkaLiptAlgTUDinoflag();
	public void setVkaLiptAlgTUDinoflag(Integer vkaLiptAlgTUDinoflag);
	public Integer getVkaLiptAmHebLbDens();
	public void setVkaLiptAmHebLbDens(Integer vkaLiptAmHebLbDens);
	public Integer getVkaHcIncl();
	public void setVkaHcIncl(Integer vkaHcIncl);
	public Integer getVkaLiptAmHebDiffuse();
	public void setVkaLiptAmHebDiffuse(Integer vkaLiptAmHebDiffuse);
	public Integer getVkaLiptSpor();
	public void setVkaLiptSpor(Integer vkaLiptSpor);
	public Integer getVkaVit();
	public void setVkaVit(Integer vkaVit);
	public Integer getVkaLiptAlg();
	public void setVkaLiptAlg(Integer vkaLiptAlg);
	public Integer getVkaVitDetroVitro();
	public void setVkaVitDetroVitro(Integer vkaVitDetroVitro);
	public String getVkaSampleIdVend();
	public void setVkaSampleIdVend(String vkaSampleIdVend);
	public Integer getVkaHcInclY();
	public void setVkaHcInclY(Integer vkaHcInclY);
	public Integer getVkaLiptAlgT();
	public void setVkaLiptAlgT(Integer vkaLiptAlgT);
	public Integer getVkaPybAnsDomain();
	public void setVkaPybAnsDomain(Integer vkaPybAnsDomain);
	public Integer getVkaLiptOthExu();
	public void setVkaLiptOthExu(Integer vkaLiptOthExu);
	public Integer getVkaVitTeloCol();
	public void setVkaVitTeloCol(Integer vkaVitTeloCol);
	public Integer getVkaVitGeloGel();
	public void setVkaVitGeloGel(Integer vkaVitGeloGel);
	public Integer getFkDatatypeId();
	public void setFkDatatypeId(Integer fkDatatypeId);
	public Integer getVkaLiptAmFlLbLens();
	public void setVkaLiptAmFlLbLens(Integer vkaLiptAmFlLbLens);
	public Integer getVkaLiptSporMicrospor();
	public void setVkaLiptSporMicrospor(Integer vkaLiptSporMicrospor);
	public Integer getVkaLiptAlgLamalgFila();
	public void setVkaLiptAlgLamalgFila(Integer vkaLiptAlgLamalgFila);
	public Integer getVkaPybIsoNfLow();
	public void setVkaPybIsoNfLow(Integer vkaPybIsoNfLow);
	public Integer getVkaInertMacrinite();
	public void setVkaInertMacrinite(Integer vkaInertMacrinite);
	public Integer getVkaZooclastScolecodont();
	public void setVkaZooclastScolecodont(Integer vkaZooclastScolecodont);
	public Integer getVkaHcInclOr();
	public void setVkaHcInclOr(Integer vkaHcInclOr);
	public Integer getVkaLiptOth();
	public void setVkaLiptOth(Integer vkaLiptOth);
	public Integer getVkaLiptAlgTUMicro();
	public void setVkaLiptAlgTUMicro(Integer vkaLiptAlgTUMicro);
	public Integer getVkaHcInclGr();
	public void setVkaHcInclGr(Integer vkaHcInclGr);
	public Integer getVkaHcInclBl();
	public void setVkaHcInclBl(Integer vkaHcInclBl);
	public String getVkaLab();
	public void setVkaLab(String vkaLab);
	public Date getVkaQcDate();
	public void setVkaQcDate(Date vkaQcDate);
	public Integer getVkaPybIsoNfHigh();
	public void setVkaPybIsoNfHigh(Integer vkaPybIsoNfHigh);
	public Integer getVkaInertInertodet();
	public void setVkaInertInertodet(Integer vkaInertInertodet);
	public Integer getVkaZooclastChitin();
	public void setVkaZooclastChitin(Integer vkaZooclastChitin);
	public Integer getVkaMinPyriteAggrCrystal();
	public void setVkaMinPyriteAggrCrystal(Integer vkaMinPyriteAggrCrystal);
	public Integer getVkaPybIsoNfMed();
	public void setVkaPybIsoNfMed(Integer vkaPybIsoNfMed);
	public Integer getVkaLiptAmFlLbDense();
	public void setVkaLiptAmFlLbDense(Integer vkaLiptAmFlLbDense);
	public Integer getVkaMinSulp();
	public void setVkaMinSulp(Integer vkaMinSulp);
	public Integer getVkaPyrite();
	public void setVkaPyrite(Integer vkaPyrite);
	public String getVkaQcUser();
	public void setVkaQcUser(String vkaQcUser);
	public String getVkaSemiquan();
	public void setVkaSemiquan(String vkaSemiquan);
	public Integer getVkaLiptAlgTCGloeo();
	public void setVkaLiptAlgTCGloeo(Integer vkaLiptAlgTCGloeo);
	public Integer getVkaLiptAlgTCPediastrum();
	public void setVkaLiptAlgTCPediastrum(Integer vkaLiptAlgTCPediastrum);
	public Integer getVkaInertMicrin();
	public void setVkaInertMicrin(Integer vkaInertMicrin);
	public Integer getVkaLiptAmHebLbLayers();
	public void setVkaLiptAmHebLbLayers(Integer vkaLiptAmHebLbLayers);
	public Integer getVkaLiptSporCrassispor();
	public void setVkaLiptSporCrassispor(Integer vkaLiptSporCrassispor);
	public Integer getVkaLiptAm();
	public void setVkaLiptAm(Integer vkaLiptAm);
	public Integer getVkaLiptAlgTULeiosphaer();
	public void setVkaLiptAlgTULeiosphaer(Integer vkaLiptAlgTULeiosphaer);
	public String getVkaComment();
	public void setVkaComment(String vkaComment);
	public Integer getVkaLiptAlgTU();
	public void setVkaLiptAlgTU(Integer vkaLiptAlgTU);
	public Integer getVkaLiptAlgTC();
	public void setVkaLiptAlgTC(Integer vkaLiptAlgTC);
	public Integer getVkaLiptAlgTUTasmanites();
	public void setVkaLiptAlgTUTasmanites(Integer vkaLiptAlgTUTasmanites);
	public Integer getVkaHcInclWY();
	public void setVkaHcInclWY(Integer vkaHcInclWY);
	public String getVkaCreatedUser();
	public void setVkaCreatedUser(String vkaCreatedUser);
	public Date getVkaCreatedDate();
	public void setVkaCreatedDate(Date vkaCreatedDate);
	public Integer getVkaLiptAmHebLb();
	public void setVkaLiptAmHebLb(Integer vkaLiptAmHebLb);
	public Integer getVkaZooclastCollograpto();
	public void setVkaZooclastCollograpto(Integer vkaZooclastCollograpto);
	public Integer getVkaLiptAlgTUAcritarch();
	public void setVkaLiptAlgTUAcritarch(Integer vkaLiptAlgTUAcritarch);
	public String getVkaSvcCode();
	public void setVkaSvcCode(String vkaSvcCode);
	public String getVkaJobId();
	public void setVkaJobId(String vkaJobId);
	public Integer getVkaPybAnsM();
	public void setVkaPybAnsM(Integer vkaPybAnsM);
	public Integer getVkaPybAnsF();
	public void setVkaPybAnsF(Integer vkaPybAnsF);
	public Integer getVkaPybAnsC();
	public void setVkaPybAnsC(Integer vkaPybAnsC);
	public Integer getVkaInertFungi();
	public void setVkaInertFungi(Integer vkaInertFungi);
	public Integer getVkaMinNonSulph();
	public void setVkaMinNonSulph(Integer vkaMinNonSulph);
	public Integer getVkaPybIsoNf();
	public void setVkaPybIsoNf(Integer vkaPybIsoNf);
	public Integer getVkaZooclastTelograpto();
	public void setVkaZooclastTelograpto(Integer vkaZooclastTelograpto);
	public Integer getVkaPybIsoFl();
	public void setVkaPybIsoFl(Integer vkaPybIsoFl);
	public Integer getVkaInertGraphRecycl();
	public void setVkaInertGraphRecycl(Integer vkaInertGraphRecycl);
	public Integer getVkaLiptAmHebLbLens();
	public void setVkaLiptAmHebLbLens(Integer vkaLiptAmHebLbLens);
	public Integer getVkaZooclastGraptolite();
	public void setVkaZooclastGraptolite(Integer vkaZooclastGraptolite);
	public Integer getVkaPk();
	public void setVkaPk(Integer vkaPk);
	public Integer getVkaLiptOthSuber();
	public void setVkaLiptOthSuber(Integer vkaLiptOthSuber);
	public Integer getVkaLiptSporTenuispor();
	public void setVkaLiptSporTenuispor(Integer vkaLiptSporTenuispor);
	public Integer getVkaPybAnsCFlow();
	public void setVkaPybAnsCFlow(Integer vkaPybAnsCFlow);
	public Integer getVkaLiptAlgTCPila();
	public void setVkaLiptAlgTCPila(Integer vkaLiptAlgTCPila);
	public Integer getVkaLiptAmHeb();
	public void setVkaLiptAmHeb(Integer vkaLiptAmHeb);
	public Integer getVkaLiptAlgTCReinschia();
	public void setVkaLiptAlgTCReinschia(Integer vkaLiptAlgTCReinschia);
	public Integer getVkaLiptSporMacrospor();
	public void setVkaLiptSporMacrospor(Integer vkaLiptSporMacrospor);
	public Integer getVkaConfTypeId();
	public void setVkaConfTypeId(Integer vkaConfTypeId);
	public Integer getVkaLiptOthChlor();
	public void setVkaLiptOthChlor(Integer vkaLiptOthChlor);
	public String getVkaUpdatedUser();
	public void setVkaUpdatedUser(String vkaUpdatedUser);
	public Integer getVkaPybAnsVf();
	public void setVkaPybAnsVf(Integer vkaPybAnsVf);
	public Integer getVkaVitDetroCollo();
	public void setVkaVitDetroCollo(Integer vkaVitDetroCollo);
	public Integer getVkaPybAns();
	public void setVkaPybAns(Integer vkaPybAns);
	public String getVkaDomQuantity();
	public void setVkaDomQuantity(String vkaDomQuantity);
	public Integer getVkaLiptAlgTCBotr();
	public void setVkaLiptAlgTCBotr(Integer vkaLiptAlgTCBotr);
	public Integer getVkaLiptAmFlLbLayers();
	public void setVkaLiptAmFlLbLayers(Integer vkaLiptAmFlLbLayers);
	public Integer getVkaVitGelo();
	public void setVkaVitGelo(Integer vkaVitGelo);
	public Integer getVkaLiptAmDiffuse();
	public void setVkaLiptAmDiffuse(Integer vkaLiptAmDiffuse);
}
