package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTORockChemostrat extends GTOAnalysisData {
	public String getCsLitology();
	public void setCsLitology(String csLitology);
	public String getCsRunNumber();
	public void setCsRunNumber(String csRunNumber);
	public Date getCsAcqDate();
	public void setCsAcqDate(Date csAcqDate);
	public String getCsJobId();
	public void setCsJobId(String csJobId);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getCsMo();
	public void setCsMo(Double csMo);
	public Double getCsNd();
	public void setCsNd(Double csNd);
	public Double getCsNb();
	public void setCsNb(Double csNb);
	public Double getCsNi();
	public void setCsNi(Double csNi);
	public Double getCsLu();
	public void setCsLu(Double csLu);
	public Double getCsLa();
	public void setCsLa(Double csLa);
	public Double getCsIn();
	public void setCsIn(Double csIn);
	public Double getCsGe();
	public void setCsGe(Double csGe);
	public Double getCsGd();
	public void setCsGd(Double csGd);
	public Double getCsGa();
	public void setCsGa(Double csGa);
	public Double getCsHo();
	public void setCsHo(Double csHo);
	public Double getCsHg();
	public void setCsHg(Double csHg);
	public Double getCsHf();
	public void setCsHf(Double csHf);
	public Double getCsEu();
	public void setCsEu(Double csEu);
	public Double getCsEr();
	public void setCsEr(Double csEr);
	public Double getCsDy();
	public void setCsDy(Double csDy);
	public Double getCsCe();
	public void setCsCe(Double csCe);
	public Double getCsCd();
	public void setCsCd(Double csCd);
	public Double getCsCs();
	public void setCsCs(Double csCs);
	public Double getCsCr();
	public void setCsCr(Double csCr);
	public Double getCsCo();
	public void setCsCo(Double csCo);
	public Double getCsCl();
	public void setCsCl(Double csCl);
	public Double getCsCu();
	public void setCsCu(Double csCu);
	public Double getCsAg();
	public void setCsAg(Double csAg);
	public Double getCsBi();
	public void setCsBi(Double csBi);
	public Double getCsBe();
	public void setCsBe(Double csBe);
	public Double getCsBr();
	public void setCsBr(Double csBr);
	public Double getCsAs();
	public void setCsAs(Double csAs);
	public Double getCsBa();
	public void setCsBa(Double csBa);
	public Double getCsNa2o();
	public void setCsNa2o(Double csNa2o);
	public String getCsComments();
	public void setCsComments(String csComments);
	public Date getCsLastUpdate();
	public void setCsLastUpdate(Date csLastUpdate);
	public String getCsQcUser();
	public void setCsQcUser(String csQcUser);
	public Date getCsQcDate();
	public void setCsQcDate(Date csQcDate);
	public Double getCsZr();
	public void setCsZr(Double csZr);
	public Double getCsZn();
	public void setCsZn(Double csZn);
	public Double getCsYb();
	public void setCsYb(Double csYb);
	public Double getCsTb();
	public void setCsTb(Double csTb);
	public Double getCsTa();
	public void setCsTa(Double csTa);
	public Double getCsSe();
	public void setCsSe(Double csSe);
	public Double getCsSr();
	public void setCsSr(Double csSr);
	public Double getCsSn();
	public void setCsSn(Double csSn);
	public Double getCsSm();
	public void setCsSm(Double csSm);
	public Double getCsTl();
	public void setCsTl(Double csTl);
	public Double getCsTh();
	public void setCsTh(Double csTh);
	public Double getCsTe();
	public void setCsTe(Double csTe);
	public Double getCsTm();
	public void setCsTm(Double csTm);
	public Double getCsRb();
	public void setCsRb(Double csRb);
	public String getCsQc();
	public void setCsQc(String csQc);
	public Double getCsSc();
	public void setCsSc(Double csSc);
	public Double getCsSb();
	public void setCsSb(Double csSb);
	public Double getCsPr();
	public void setCsPr(Double csPr);
	public Double getCsPd();
	public void setCsPd(Double csPd);
	public Double getCsPb();
	public void setCsPb(Double csPb);
	public String getCsSampleIdVend();
	public void setCsSampleIdVend(String csSampleIdVend);
	public Double getCsFe2o3();
	public void setCsFe2o3(Double csFe2o3);
	public Double getCsAl2o3();
	public void setCsAl2o3(Double csAl2o3);
	public Double getCsMno();
	public void setCsMno(Double csMno);
	public Double getCsMgo();
	public void setCsMgo(Double csMgo);
	public Double getCsSio2();
	public void setCsSio2(Double csSio2);
	public Double getCsK2o();
	public void setCsK2o(Double csK2o);
	public Double getCsTio2();
	public void setCsTio2(Double csTio2);
	public String getCsIqmCode();
	public void setCsIqmCode(String csIqmCode);
	public String getCsColor();
	public void setCsColor(String csColor);
	public Double getCsP2o5();
	public void setCsP2o5(Double csP2o5);
	public Double getCsCao();
	public void setCsCao(Double csCao);
	public String getCsGrainsize();
	public void setCsGrainsize(String csGrainsize);
	public Date getCsDate();
	public void setCsDate(Date csDate);
	public Double getCsSo3();
	public void setCsSo3(Double csSo3);
	public String getCsSvcCode();
	public void setCsSvcCode(String csSvcCode);
	public Double getCsI();
	public void setCsI(Double csI);
	public Double getCsY();
	public void setCsY(Double csY);
	public Double getCsW();
	public void setCsW(Double csW);
	public Double getCsV();
	public void setCsV(Double csV);
	public Double getCsU();
	public void setCsU(Double csU);
	public Double getCsS();
	public void setCsS(Double csS);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public String getCsMethod();
	public void setCsMethod(String csMethod);
}
