package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOSimdis extends GTOAnalysisData {
	public Double getSimdis90T();
	public void setSimdis90T(Double simdis90T);
	public Double getSimdis68T();
	public void setSimdis68T(Double simdis68T);
	public String getSimdisLab();
	public void setSimdisLab(String simdisLab);
	public Double getSimdis55T();
	public void setSimdis55T(Double simdis55T);
	public Double getSimdis42T();
	public void setSimdis42T(Double simdis42T);
	public String getSimdisSvcCode();
	public void setSimdisSvcCode(String simdisSvcCode);
	public Double getSimdis91T();
	public void setSimdis91T(Double simdis91T);
	public Double getSimdis69T();
	public void setSimdis69T(Double simdis69T);
	public Double getSimdis56T();
	public void setSimdis56T(Double simdis56T);
	public Double getSimdis43T();
	public void setSimdis43T(Double simdis43T);
	public Double getSimdis30T();
	public void setSimdis30T(Double simdis30T);
	public Double getSimdis92T();
	public void setSimdis92T(Double simdis92T);
	public Double getSimdis79T();
	public void setSimdis79T(Double simdis79T);
	public Double getSimdis66T();
	public void setSimdis66T(Double simdis66T);
	public Double getSimdis53T();
	public void setSimdis53T(Double simdis53T);
	public Double getSimdis40T();
	public void setSimdis40T(Double simdis40T);
	public Double getSimdis8T();
	public void setSimdis8T(Double simdis8T);
	public Double getSimdis18T();
	public void setSimdis18T(Double simdis18T);
	public Double getSimdis67T();
	public void setSimdis67T(Double simdis67T);
	public Double getSimdis9T();
	public void setSimdis9T(Double simdis9T);
	public Double getSimdis54T();
	public void setSimdis54T(Double simdis54T);
	public Double getSimdis41T();
	public void setSimdis41T(Double simdis41T);
	public Double getSimdisConf();
	public void setSimdisConf(Double simdisConf);
	public String getSampleId();
	public void setSampleId(String simdisSampleId);
	public Date getSimdisDate();
	public void setSimdisDate(Date simdisDate);
	public Double getSimdis19T();
	public void setSimdis19T(Double simdis19T);
	public Double getSimdisSplWt();
	public void setSimdisSplWt(Double simdisSplWt);
	public String getSimdisQc();
	public void setSimdisQc(String simdisQc);
	public Double getSimdis59T();
	public void setSimdis59T(Double simdis59T);
	public Double getSimdis46T();
	public void setSimdis46T(Double simdis46T);
	public Double getSimdis33T();
	public void setSimdis33T(Double simdis33T);
	public Double getSimdis20T();
	public void setSimdis20T(Double simdis20T);
	public Date getSimdisLastUpdate();
	public void setSimdisLastUpdate(Date simdisLastUpdate);
	public Double getSimdis95T();
	public void setSimdis95T(Double simdis95T);
	public Double getSimdis82T();
	public void setSimdis82T(Double simdis82T);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getSimdis47T();
	public void setSimdis47T(Double simdis47T);
	public String getSimdisComment();
	public void setSimdisComment(String simdisComment);
	public Double getSimdis34T();
	public void setSimdis34T(Double simdis34T);
	public Double getSimdis21T();
	public void setSimdis21T(Double simdis21T);
	public Double getSimdis96T();
	public void setSimdis96T(Double simdis96T);
	public Double getSimdis83T();
	public void setSimdis83T(Double simdis83T);
	public Double getSimdis70T();
	public void setSimdis70T(Double simdis70T);
	public Double getSimdis57T();
	public void setSimdis57T(Double simdis57T);
	public Double getSimdis44T();
	public void setSimdis44T(Double simdis44T);
	public String getSimdisMethod();
	public void setSimdisMethod(String simdisMethod);
	public Double getSimdis31T();
	public void setSimdis31T(Double simdis31T);
	public String getSimdisSampleIdVend();
	public void setSimdisSampleIdVend(String simdisSampleIdVend);
	public String getSimdisIqmCode();
	public void setSimdisIqmCode(String simdisIqmCode);
	public Double getSimdis93T();
	public void setSimdis93T(Double simdis93T);
	public Double getSimdis80T();
	public void setSimdis80T(Double simdis80T);
	public Double getSimdis58T();
	public void setSimdis58T(Double simdis58T);
	public Double getSimdis45T();
	public void setSimdis45T(Double simdis45T);
	public Double getSimdis32T();
	public void setSimdis32T(Double simdis32T);
	public String getSimdisJobId();
	public void setSimdisJobId(String simdisJobId);
	public Double getSimdis94T();
	public void setSimdis94T(Double simdis94T);
	public Double getSimdis81T();
	public void setSimdis81T(Double simdis81T);
	public Double getSimdis37T();
	public void setSimdis37T(Double simdis37T);
	public Double getSimdis24T();
	public void setSimdis24T(Double simdis24T);
	public Double getSimdis11T();
	public void setSimdis11T(Double simdis11T);
	public Double getSimdis99T();
	public void setSimdis99T(Double simdis99T);
	public Double getSimdis86T();
	public void setSimdis86T(Double simdis86T);
	public Double getSimdis73T();
	public void setSimdis73T(Double simdis73T);
	public Double getSimdis60T();
	public void setSimdis60T(Double simdis60T);
	public Double getSimdis2T();
	public void setSimdis2T(Double simdis2T);
	public Double getSimdis38T();
	public void setSimdis38T(Double simdis38T);
	public Double getSimdis25T();
	public void setSimdis25T(Double simdis25T);
	public Double getSimdis12T();
	public void setSimdis12T(Double simdis12T);
	public Double getSimdis87T();
	public void setSimdis87T(Double simdis87T);
	public Double getSimdis74T();
	public void setSimdis74T(Double simdis74T);
	public Double getSimdis61T();
	public void setSimdis61T(Double simdis61T);
	public String getSimdisAuthor();
	public void setSimdisAuthor(String simdisAuthor);
	public Double getSimdis39T();
	public void setSimdis39T(Double simdis39T);
	public Double getSimdis3T();
	public void setSimdis3T(Double simdis3T);
	public Double getSimdisRec();
	public void setSimdisRec(Double simdisRec);
	public Double getSimdis48T();
	public void setSimdis48T(Double simdis48T);
	public Double getSimdis35T();
	public void setSimdis35T(Double simdis35T);
	public Double getSimdis22T();
	public void setSimdis22T(Double simdis22T);
	public Double getSimdis97T();
	public void setSimdis97T(Double simdis97T);
	public Double getSimdis84T();
	public void setSimdis84T(Double simdis84T);
	public Double getSimdis71T();
	public void setSimdis71T(Double simdis71T);
	public Double getSimdis49T();
	public void setSimdis49T(Double simdis49T);
	public Double getSimdis36T();
	public void setSimdis36T(Double simdis36T);
	public Double getSimdis23T();
	public void setSimdis23T(Double simdis23T);
	public Double getSimdis10T();
	public void setSimdis10T(Double simdis10T);
	public Double getSimdis98T();
	public void setSimdis98T(Double simdis98T);
	public String getSimdisRunNumber();
	public void setSimdisRunNumber(String simdisRunNumber);
	public Double getSimdis85T();
	public void setSimdis85T(Double simdis85T);
	public Double getSimdis72T();
	public void setSimdis72T(Double simdis72T);
	public Double getSimdis1T();
	public void setSimdis1T(Double simdis1T);
	public Double getSimdis77T();
	public void setSimdis77T(Double simdis77T);
	public Double getSimdis64T();
	public void setSimdis64T(Double simdis64T);
	public Double getSimdis6T();
	public void setSimdis6T(Double simdis6T);
	public Double getSimdis51T();
	public void setSimdis51T(Double simdis51T);
	public String getSimdisQcUser();
	public void setSimdisQcUser(String simdisQcUser);
	public Double getSimdis29T();
	public void setSimdis29T(Double simdis29T);
	public Double getSimdis16T();
	public void setSimdis16T(Double simdis16T);
	public Date getSimdisAcqDate();
	public void setSimdisAcqDate(Date simdisAcqDate);
	public Double getSimdis78T();
	public void setSimdis78T(Double simdis78T);
	public Double getSimdis100T();
	public void setSimdis100T(Double simdis100T);
	public Double getSimdis65T();
	public void setSimdis65T(Double simdis65T);
	public Double getSimdis52T();
	public void setSimdis52T(Double simdis52T);
	public Double getSimdis7T();
	public void setSimdis7T(Double simdis7T);
	public Double getSimdis17T();
	public void setSimdis17T(Double simdis17T);
	public Double getSimdis26T();
	public void setSimdis26T(Double simdis26T);
	public Double getSimdis13T();
	public void setSimdis13T(Double simdis13T);
	public Double getSimdis88T();
	public void setSimdis88T(Double simdis88T);
	public Double getSimdis75T();
	public void setSimdis75T(Double simdis75T);
	public Double getSimdis62T();
	public void setSimdis62T(Double simdis62T);
	public Double getSimdis4T();
	public void setSimdis4T(Double simdis4T);
	public Double getSimdis27T();
	public void setSimdis27T(Double simdis27T);
	public Double getSimdis14T();
	public void setSimdis14T(Double simdis14T);
	public Double getSimdis89T();
	public void setSimdis89T(Double simdis89T);
	public Double getSimdis76T();
	public void setSimdis76T(Double simdis76T);
	public Double getSimdis63T();
	public void setSimdis63T(Double simdis63T);
	public Double getSimdis5T();
	public void setSimdis5T(Double simdis5T);
	public Date getSimdisQcDate();
	public void setSimdisQcDate(Date simdisQcDate);
	public Double getSimdis50T();
	public void setSimdis50T(Double simdis50T);
	public Double getSimdis28T();
	public void setSimdis28T(Double simdis28T);
	public Double getSimdis15T();
	public void setSimdis15T(Double simdis15T);
}
