package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOSimdisHt extends GTOAnalysisData {
	public String getSimdisHtQc();
	public void setSimdisHtQc(String simdisHtQc);
	public String getSimdisHtSampleIdVend();
	public void setSimdisHtSampleIdVend(String simdisHtSampleIdVend);
	public Double getSimdisHtC7();
	public void setSimdisHtC7(Double simdisHtC7);
	public Double getSimdisHtC6();
	public void setSimdisHtC6(Double simdisHtC6);
	public Double getSimdisHtC9();
	public void setSimdisHtC9(Double simdisHtC9);
	public Double getSimdisHtC8();
	public void setSimdisHtC8(Double simdisHtC8);
	public String getSimdisHtIqmCode();
	public void setSimdisHtIqmCode(String simdisHtIqmCode);
	public Double getSimdisHtC38();
	public void setSimdisHtC38(Double simdisHtC38);
	public Double getSimdisHtC37();
	public void setSimdisHtC37(Double simdisHtC37);
	public Double getSimdisHtC39();
	public void setSimdisHtC39(Double simdisHtC39);
	public Double getSimdisHtC34();
	public void setSimdisHtC34(Double simdisHtC34);
	public Double getSimdisHtC33();
	public void setSimdisHtC33(Double simdisHtC33);
	public Double getSimdisHtC36();
	public void setSimdisHtC36(Double simdisHtC36);
	public Double getSimdisHtC35();
	public void setSimdisHtC35(Double simdisHtC35);
	public Double getSimdisHtC30();
	public void setSimdisHtC30(Double simdisHtC30);
	public Double getSimdisHtC32();
	public void setSimdisHtC32(Double simdisHtC32);
	public Double getSimdisHtC31();
	public void setSimdisHtC31(Double simdisHtC31);
	public Double getSimdisHtC49();
	public void setSimdisHtC49(Double simdisHtC49);
	public Double getSimdisHtC48();
	public void setSimdisHtC48(Double simdisHtC48);
	public Double getSimdisHtC45();
	public void setSimdisHtC45(Double simdisHtC45);
	public Double getSimdisHtC44();
	public void setSimdisHtC44(Double simdisHtC44);
	public Double getSimdisHtC47();
	public void setSimdisHtC47(Double simdisHtC47);
	public Double getSimdisHtC46();
	public void setSimdisHtC46(Double simdisHtC46);
	public Double getSimdisHtC41();
	public void setSimdisHtC41(Double simdisHtC41);
	public Double getSimdisHtC40();
	public void setSimdisHtC40(Double simdisHtC40);
	public Double getSimdisHtC43();
	public void setSimdisHtC43(Double simdisHtC43);
	public Double getSimdisHtC42();
	public void setSimdisHtC42(Double simdisHtC42);
	public Double getSimdisHtC59();
	public void setSimdisHtC59(Double simdisHtC59);
	public Double getSimdisHtC56();
	public void setSimdisHtC56(Double simdisHtC56);
	public Double getSimdisHtC55();
	public void setSimdisHtC55(Double simdisHtC55);
	public Double getSimdisHtC58();
	public void setSimdisHtC58(Double simdisHtC58);
	public Double getSimdisHtC57();
	public void setSimdisHtC57(Double simdisHtC57);
	public Double getSimdisHtC52();
	public void setSimdisHtC52(Double simdisHtC52);
	public Double getSimdisHtC51();
	public void setSimdisHtC51(Double simdisHtC51);
	public Double getSimdisHtC54();
	public void setSimdisHtC54(Double simdisHtC54);
	public Double getSimdisHtC53();
	public void setSimdisHtC53(Double simdisHtC53);
	public Double getSimdisHtC50();
	public void setSimdisHtC50(Double simdisHtC50);
	public Double getSimdisHtC67();
	public void setSimdisHtC67(Double simdisHtC67);
	public Double getSimdisHtC66();
	public void setSimdisHtC66(Double simdisHtC66);
	public Double getSimdisHtC69();
	public void setSimdisHtC69(Double simdisHtC69);
	public Double getSimdisHtC68();
	public void setSimdisHtC68(Double simdisHtC68);
	public Double getSimdisHtC63();
	public void setSimdisHtC63(Double simdisHtC63);
	public Double getSimdisHtC62();
	public void setSimdisHtC62(Double simdisHtC62);
	public Double getSimdisHtC65();
	public void setSimdisHtC65(Double simdisHtC65);
	public Double getSimdisHtC64();
	public void setSimdisHtC64(Double simdisHtC64);
	public Double getSimdisHtC61();
	public void setSimdisHtC61(Double simdisHtC61);
	public Double getSimdisHtC60();
	public void setSimdisHtC60(Double simdisHtC60);
	public Double getSimdisHtC78();
	public void setSimdisHtC78(Double simdisHtC78);
	public Double getSimdisHtC77();
	public void setSimdisHtC77(Double simdisHtC77);
	public Double getSimdisHtC79();
	public void setSimdisHtC79(Double simdisHtC79);
	public Double getSimdisHtC74();
	public void setSimdisHtC74(Double simdisHtC74);
	public Double getSimdisHtC73();
	public void setSimdisHtC73(Double simdisHtC73);
	public Double getSimdisHtC76();
	public void setSimdisHtC76(Double simdisHtC76);
	public Double getSimdisHtC75();
	public void setSimdisHtC75(Double simdisHtC75);
	public Double getSimdisHtC70();
	public void setSimdisHtC70(Double simdisHtC70);
	public Double getSimdisHtC72();
	public void setSimdisHtC72(Double simdisHtC72);
	public Double getSimdisHtC71();
	public void setSimdisHtC71(Double simdisHtC71);
	public Double getSimdisHtC89();
	public void setSimdisHtC89(Double simdisHtC89);
	public Double getSimdisHtC88();
	public void setSimdisHtC88(Double simdisHtC88);
	public Double getSimdisHtC85();
	public void setSimdisHtC85(Double simdisHtC85);
	public Double getSimdisHtC84();
	public void setSimdisHtC84(Double simdisHtC84);
	public Double getSimdisHtC87();
	public void setSimdisHtC87(Double simdisHtC87);
	public Double getSimdisHtC86();
	public void setSimdisHtC86(Double simdisHtC86);
	public Double getSimdisHtC81();
	public void setSimdisHtC81(Double simdisHtC81);
	public Double getSimdisHtC80();
	public void setSimdisHtC80(Double simdisHtC80);
	public Double getSimdisHtC83();
	public void setSimdisHtC83(Double simdisHtC83);
	public Double getSimdisHtC82();
	public void setSimdisHtC82(Double simdisHtC82);
	public Double getSimdisHtC90();
	public void setSimdisHtC90(Double simdisHtC90);
	public Double getSimdisHtC99();
	public void setSimdisHtC99(Double simdisHtC99);
	public Double getSimdisHtC96();
	public void setSimdisHtC96(Double simdisHtC96);
	public Double getSimdisHtC95();
	public void setSimdisHtC95(Double simdisHtC95);
	public Double getSimdisHtC98();
	public void setSimdisHtC98(Double simdisHtC98);
	public Double getSimdisHtC97();
	public void setSimdisHtC97(Double simdisHtC97);
	public Double getSimdisHtC92();
	public void setSimdisHtC92(Double simdisHtC92);
	public Double getSimdisHtC91();
	public void setSimdisHtC91(Double simdisHtC91);
	public Double getSimdisHtC94();
	public void setSimdisHtC94(Double simdisHtC94);
	public Double getSimdisHtC93();
	public void setSimdisHtC93(Double simdisHtC93);
	public Double getSimdisHtC16();
	public void setSimdisHtC16(Double simdisHtC16);
	public Double getSimdisHtC15();
	public void setSimdisHtC15(Double simdisHtC15);
	public Double getSimdisHtC18();
	public void setSimdisHtC18(Double simdisHtC18);
	public Double getSimdisHtC17();
	public void setSimdisHtC17(Double simdisHtC17);
	public Double getSimdisHtC12();
	public void setSimdisHtC12(Double simdisHtC12);
	public Double getSimdisHtC11();
	public void setSimdisHtC11(Double simdisHtC11);
	public Double getSimdisHtC14();
	public void setSimdisHtC14(Double simdisHtC14);
	public Double getSimdisHtC13();
	public void setSimdisHtC13(Double simdisHtC13);
	public Double getSimdisHtC10();
	public void setSimdisHtC10(Double simdisHtC10);
	public Double getSimdisHtC19();
	public void setSimdisHtC19(Double simdisHtC19);
	public Double getSimdisHtC27();
	public void setSimdisHtC27(Double simdisHtC27);
	public Double getSimdisHtC26();
	public void setSimdisHtC26(Double simdisHtC26);
	public Double getSimdisHtC29();
	public void setSimdisHtC29(Double simdisHtC29);
	public Double getSimdisHtC28();
	public void setSimdisHtC28(Double simdisHtC28);
	public Double getSimdisHtC23();
	public void setSimdisHtC23(Double simdisHtC23);
	public Double getSimdisHtC22();
	public void setSimdisHtC22(Double simdisHtC22);
	public Double getSimdisHtC25();
	public void setSimdisHtC25(Double simdisHtC25);
	public Double getSimdisHtC24();
	public void setSimdisHtC24(Double simdisHtC24);
	public Double getSimdisHtC21();
	public void setSimdisHtC21(Double simdisHtC21);
	public Double getSimdisHtC20();
	public void setSimdisHtC20(Double simdisHtC20);
	public Date getSimdisHtLastUpdate();
	public void setSimdisHtLastUpdate(Date simdisHtLastUpdate);
	public Date getSimdisHtAcqDate();
	public void setSimdisHtAcqDate(Date simdisHtAcqDate);
	public Double getSimdisHtSampleAmt();
	public void setSimdisHtSampleAmt(Double simdisHtSampleAmt);
	public String getSimdisHtRunNumber();
	public void setSimdisHtRunNumber(String simdisHtRunNumber);
	public Date getSimdisHtQcDate();
	public void setSimdisHtQcDate(Date simdisHtQcDate);
	public String getSimdisHtDatatype();
	public void setSimdisHtDatatype(String simdisHtDatatype);
	public Double getSimdisHtC105();
	public void setSimdisHtC105(Double simdisHtC105);
	public Double getSimdisHtC106();
	public void setSimdisHtC106(Double simdisHtC106);
	public Double getSimdisHtC103();
	public void setSimdisHtC103(Double simdisHtC103);
	public Double getSimdisHtC104();
	public void setSimdisHtC104(Double simdisHtC104);
	public Double getSimdisHtC101();
	public void setSimdisHtC101(Double simdisHtC101);
	public Double getSimdisHtC102();
	public void setSimdisHtC102(Double simdisHtC102);
	public Double getSimdisHtC100();
	public void setSimdisHtC100(Double simdisHtC100);
	public Double getSimdisHtC107();
	public void setSimdisHtC107(Double simdisHtC107);
	public Double getSimdisHtC108();
	public void setSimdisHtC108(Double simdisHtC108);
	public String getSimdisHtQcUser();
	public void setSimdisHtQcUser(String simdisHtQcUser);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getSimdisHtC05();
	public void setSimdisHtC05(Double simdisHtC05);
	public String getSimdisHtComment();
	public void setSimdisHtComment(String simdisHtComment);
	public String getSimdisHtSvcCode();
	public void setSimdisHtSvcCode(String simdisHtSvcCode);
	public Double getSimdisHtRecoveryPct();
	public void setSimdisHtRecoveryPct(Double simdisHtRecoveryPct);
	public Double getSimdisHtConf();
	public void setSimdisHtConf(Double simdisHtConf);
	public Date getSimdisHtDate();
	public void setSimdisHtDate(Date simdisHtDate);
	public String getSimdisHtJobId();
	public void setSimdisHtJobId(String simdisHtJobId);
	public String getRequestId();
	public void setRequestId(String requestId);
	public String getSimdisHtLab();
	public void setSimdisHtLab(String simdisHtLab);
	public Double getSimdisHtWeightCs2();
	public void setSimdisHtWeightCs2(Double simdisHtWeightCs2);
	public String getSimdisHtMethod();
	public void setSimdisHtMethod(String simdisHtMethod);
	public String getSimdisHtAuthor();
	public void setSimdisHtAuthor(String simdisHtAuthor);
}
