package com.shell.siep.gto.persistence.model.raw;

import com.shell.siep.gto.persistence.model.GTOAnalysisData;

import java.util.Date;

public interface GTOWaxDeposition extends GTOAnalysisData {
	public Double getDepFht();
	public void setDepFht(Double depFht);
	public Date getDepUpdatedDate();
	public void setDepUpdatedDate(Date depUpdatedDate);
	public Double getDepToluenewax();
	public void setDepToluenewax(Double depToluenewax);
	public Double getDepConf();
	public void setDepConf(Double depConf);
	public Double getDepAcrate();
	public void setDepAcrate(Double depAcrate);
	public String getDepCreatedUser();
	public void setDepCreatedUser(String depCreatedUser);
	public Double getDepFdiam();
	public void setDepFdiam(Double depFdiam);
	public Double getDepTopped();
	public void setDepTopped(Double depTopped);
	public Double getDepWtemp();
	public void setDepWtemp(Double depWtemp);
	public Double getDepRat();
	public void setDepRat(Double depRat);
	public String getDepSmpTrtmt();
	public void setDepSmpTrtmt(String depSmpTrtmt);
	public String getDepMethod();
	public void setDepMethod(String depMethod);
	public String getDepQcUser();
	public void setDepQcUser(String depQcUser);
	public Date getDepAcqDate();
	public void setDepAcqDate(Date depAcqDate);
	public String getDepComments();
	public void setDepComments(String depComments);
	public Double getDepTestdur();
	public void setDepTestdur(Double depTestdur);
	public Double getDepOtemp();
	public void setDepOtemp(Double depOtemp);
	public String getRequestId();
	public void setRequestId(String requestId);
	public Double getDepCrate();
	public void setDepCrate(Double depCrate);
	public String getDepLabref();
	public void setDepLabref(String depLabref);
	public String getDepDaughter();
	public void setDepDaughter(String depDaughter);
	public String getDepQcFlag();
	public void setDepQcFlag(String depQcFlag);
	public String getDepAuthor();
	public void setDepAuthor(String depAuthor);
	public String getDepLab();
	public void setDepLab(String depLab);
	public Date getDepQcDate();
	public void setDepQcDate(Date depQcDate);
	public Integer getDepSampleIdVend();
	public void setDepSampleIdVend(Integer depSampleIdVend);
	public Integer getDepOpid();
	public void setDepOpid(Integer depOpid);
	public String getDepLabrefPage();
	public void setDepLabrefPage(String depLabrefPage);
	public String getSampleId();
	public void setSampleId(String sampleId);
	public Double getDepOilvol();
	public void setDepOilvol(Double depOilvol);
	public String getDepRunNumber();
	public void setDepRunNumber(String depRunNumber);
	public String getDepTempUnits();
	public void setDepTempUnits(String depTempUnits);
	public String getDepUpdatedUser();
	public void setDepUpdatedUser(String depUpdatedUser);
	public Double getDepSolidb();
	public void setDepSolidb(Double depSolidb);
	public String getDepSvcCode();
	public void setDepSvcCode(String depSvcCode);
	public Date getDepCreatedDate();
	public void setDepCreatedDate(Date depCreatedDate);
	public String getDepProcessRun();
	public void setDepProcessRun(String depProcessRun);
	public Double getDepPtemp();
	public void setDepPtemp(Double depPtemp);
	public Double getDepSrate();
	public void setDepSrate(Double depSrate);
	public String getDepRequestIdVend();
	public void setDepRequestIdVend(String depRequestIdVend);
}
